### ISSUE TITLE
Throwing Aphrodites Serum causes a crash on server 

### ISSUE THREAD

**Issue by DrasticDemise** [P3pp3rF1y/Reliquary#101]
Probably calling some methods on the server world and not the client. http://pastebin.com/tQb0uXGs

**Comment by P3pp3rF1y** [comment]
There was an issue with client only method used there. i have fixed it to use the same one as the other potions. The fixed build is on CF so you can go ahead and download that one.

**Comment by P3pp3rF1y** [comment]
Closing
