### ISSUE TITLE
Shift-clicking empty Pedistal crashes internal server

### ISSUE THREAD

**Issue by Cat-McCatface** [P3pp3rF1y/Reliquary#102]
Was attempting to test XP storage function of Hero Medallion for modpack use. Didn't get expected result. http://pastebin.com/s3D4kr84

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. I would think that I have tested this with all the pedestal testing that I do lately, but apparently not. I will have a fix for it shortly

**Comment by P3pp3rF1y** [comment]
And the fixed build is on CF
