### ISSUE TITLE
Going very fast with the  Glacial Staff leaves ice behind 

### ISSUE THREAD

**Issue by Crazy-KSK** [P3pp3rF1y/Reliquary#108]
http://i.imgur.com/TlX5bfX.jpg
This was accomplished with ic2s QuantumSuit Leggings, quite a niche issue but would still be nice if it was fixed! =)

**Comment by P3pp3rF1y** [comment]
Sorry, didn't forget about this one just isn't the top priority for me at the moment. At a glance I didn't see anything obvious that could be causing frozen blocks to be left behind, but one thought would be that the server was very busy at the time of your walk. Was it lagging when it happened?

**Comment by Crazy-KSK** [comment]
no worries, no lag at all 5ms tick time they are also real blocks that can be mined so no client/server glitch and they do go away if I get close to them again with a staff in my inventory 
I guess I'm just moving so fast out of range of the ice that it doesn't get removed

**Comment by P3pp3rF1y** [comment]
This is now fixed and released on CF
