### ISSUE TITLE
TiCon Swords in Pedestal

### ISSUE THREAD

**Issue by Joust1187** [P3pp3rF1y/Reliquary#111]
Seems like TiCon swords/cleavers don't work in the pedestal.  The Sentient sword from Blood Magic works though, along with the vanilla swords.

**Comment by P3pp3rF1y** [comment]
This is a case of TiCon updating later on in 1.9.4 so I had to comment out the code that includes support for those. Now that I am updating to 1.10 it will be happening again so perhaps I will reinclude once TiCon is in 1.10 as 1.9.4 seems like a versiont that we will leave very quickly given how little changes need to be made for 1.10 port.

**Comment by P3pp3rF1y** [comment]
And because 1.9.4 is so close in code to 1.10 I have tried to include 1.9.4 version of TiCon in and both cleaver and broadsword seem to work properly. So I will likely have another 1.10 release today with this included.

**Comment by P3pp3rF1y** [comment]
This is now released on CF with the new 1.10 version
