### ISSUE TITLE
[1.9.4][Request] Allow Glowing Water potions to be used in dispensers like splash potions.

### ISSUE THREAD

**Issue by Laruae** [P3pp3rF1y/Reliquary#113]
Currently the Glowing Water potion does not work when inserted into a dispenser. Any chance that we could get this changed? Would be nice to have!

**Comment by P3pp3rF1y** [comment]
I will take a look. Should be doable and makes sense that it would work the same way as vanilla splash potions. Also will take care of other Reliquary splash potions when I do this.

**Comment by P3pp3rF1y** [comment]
This enhancement is done and released. All splash potion reliquary items now work in dispenser and so does holy hand grenade
