### ISSUE TITLE
Apothecary Mortar and Cauldron have broken tooltips in WAILA

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#120]
This is not where i should post this right

**Comment by P3pp3rF1y** [comment]
When you say the waila is broken for them what do you mean? no additional information when you put ingredients in?
What mod/mc version is it?

**Comment by ghost** [comment]
It's with an addon for waila or is it wawla I can't  remember which one. The addon adds a thing that shows if the thing is harvestable and the thing that shows if it's harvestable spams in the info window.
MC version 1.8.9

**Comment by ghost** [comment]
It always spams the window doesn't matter what ingredients I put into them.

**Comment by P3pp3rF1y** [comment]
thanks, I will take a look at this

**Comment by Gamerbolts** [comment]
Just to let you know I am having the same issue upon placing down the Apothecary or Apothecary Motor WAILA Harvestability spams that harvest-ability of the item. It seems like those two blocks are changing constantly and Waila keeps thinking it is a new item I am not sure. I have no idea about the world of coding. All I know is while I was in the options for waila I was looking at the Apothecary and I went from 500 fps to 0 quite quickly. Sorry if you already know this. I was just putting my two cents in to see if it could help you better in finding a solution.

**Comment by ghost** [comment]
My FPS did not change but maybe it's because I have a good computer.

**Comment by ghost** [comment]
And yeah it's waila harvestability that's causing the problem.

**Comment by ghost** [comment]
I just realized that you must have a great computer to get 500 FPS.

**Comment by Gamerbolts** [comment]
Any ETA on when the mod will be updated?

**Comment by P3pp3rF1y** [comment]
soon, today or tomorrow

**Comment by Gamerbolts** [comment]
Awesome! Thank you!

**Comment by Gamerbolts** [comment]
Thank you for the update! Works perfectly now

**Comment by P3pp3rF1y** [comment]
No problem happy to fix stuff that people report. (Because that actually shows me that the mod is being used).
