### ISSUE TITLE
Nian Zhus

### ISSUE THREAD

**Issue by Thiana** [P3pp3rF1y/Reliquary#124]
Since you've added a lot more Nian Zhus, could you consider making some balancing options for them available to pack makers? For example, have them 'break' if the player attacks the target type too many times or have them destroyed when the player dies.

Thanks.

**Comment by P3pp3rF1y** [comment]
I am definitely wondering how to balance these a bit. Definitely a player with all of these in the inventory will feel a sudden lack of big part of their inventory. 
A thought I had was to only keep two nian zhus active (rings in baubles or first two in the inventory), but the idea of damaging these every time a player attacks or maybe kills a mob sounds pretty good. I could also make them repairable with the reliquary mob drops in a way that you would only get a little extra mob drops if you continuously killed mobs and repaired nian zhus with their drops. If you have any other ideas let me know as any feedback is welcome.

**Comment by Thiana** [comment]
I do like the idea of them being repairable. That way I can make them expensive up front and then have the ongoing repair cost as a long term balance point. 

Thanks :)

**Comment by P3pp3rF1y** [comment]
Yesterday I have released a new version that introduces Mob Charms - different design and rename of Nian Zhus.
Also adds damaging to them when mob they protect from is killed by player. And adds repairing with the special drops.

**Comment by P3pp3rF1y** [comment]
Closing
