### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by LlubNek** [P3pp3rF1y/Reliquary#125]
I died by TNT while caught in webs.  Before showing the death message or game over screen, Minecraft crashed.  I did not have any Nian Zhus when I died.

I'm using Reliquary-1.10-1.3.2.409.jar, Forge 12.18.0.2005 and Minecraft 1.10.2.

Here's the important bit:
`java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.EntityLiving
    at xreliquary.handler.CommonEventHandler.doHeartZhuCheckOnSetTarget(CommonEventHandler.java:135)
    at xreliquary.handler.CommonEventHandler.onEntityTargetedEvent(CommonEventHandler.java:81)`

crash report:  http://pastebin.com/iRWe0dSy
game output:  http://pastebin.com/YQzgWUh1

**Comment by LlubNek** [comment]
Apparently I didn't die after all.  Still alive (and trapped in webs) when I reentered the world.

**Comment by P3pp3rF1y** [comment]
How was the TNT triggered? flint and steel / redstone / another player? Just trying to understand the test scenario so that I can recreate.

**Comment by LlubNek** [comment]
Spawned already lit by a chance cube.

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest release
