### ISSUE TITLE
[1.9.4] crash after crafting and holding a salmandar eye

### ISSUE THREAD

**Issue by kamyflouge** [P3pp3rF1y/Reliquary#126]
version: forge1.9.4-12.17.0.1976
reliquary:1.9.4-1.3.2.404
optifine:HD-U-B6  

i do have optifine installed . and this is the log 

http://pastebin.com/1NFSLkSv

**Comment by P3pp3rF1y** [comment]
Looks like some block within salamander eye range (3 blocks) isn't registered properly. I am going to change the check in Salamander's eye anyway as it can be simplified and the registration name check omitted there, but the other mod definitely has a problem with registering their block properly.

**Comment by P3pp3rF1y** [comment]
I have released a version that doesn't use registry to check for fire so even if a block isnt registred properly this crash wont happen

**Comment by kamyflouge** [comment]
it was either upgrade extractor from bauble stuff or the workbench from a mod called JACB .
