### ISSUE TITLE
Pedestal not picking up liquids

### ISSUE THREAD

**Issue by Waisse** [P3pp3rF1y/Reliquary#128]
FTB Unstable 1.10 with Reliquary v 1.3.2.406

Pedestal doesn't pick up lava/water :

http://i.imgur.com/uvL9hGV.png

**Comment by P3pp3rF1y** [comment]
You need to have a tank next to it. It won't fill the bucket that's in the pedestal but instead a tank that's adjacent to pedestal. Could you try with that and let me know?

**Comment by Waisse** [comment]
I understand how it work now : 
http://i.imgur.com/lzG0jPx.png
Enderio Fluid Tank set on push/pull will pick up the bucket and put it back on the Pedestal. How convenient !

I suggest either : 

1/ Making the pedestal pick up liquids without needing a tank next to it (so people can automate how they want with pipes)
Or
2/ Adding to the item description that it won't pick up liquids until there's a tank next to it.

Either way awesome mod !

**Comment by P3pp3rF1y** [comment]
You shouldn't need to pull push the bucket as it's always empty bucket anyway and it actually likely makes the pedestal work slower. The only thing it needs is just some tank next to pedestal so that it has where to put the liquid.

**Comment by P3pp3rF1y** [comment]
I will likely include a bit more info in some in-game guide regarding the use of bucket with pedestal and tank as welll as all the other info for pedestal items. I have an enhancement tracked for that #26 .
