### ISSUE TITLE
Shears of winter can not be put in ender io farming station

### ISSUE THREAD

**Issue by Peach774** [P3pp3rF1y/Reliquary#132]
As title says, i expect them to go in and essentialyl, function as regular shears but without durability.

**Comment by palaster** [comment]
They wouldn't go into the ender io farming station, because the ender io farming station will only take modded shears that extend from ItemShears, and the Shears of Winter extend ItemBase, not ItemShears, so they wouldn't be able to be put in the ender io farming station.

**Comment by Peach774** [comment]
Shouldn't they extend itemShears since they are shears?

**Comment by palaster** [comment]
https://github.com/P3pp3rF1y/Reliquary/blob/1.10.2/src/main/java/xreliquary/items/ItemShearsOfWinter.java#L39 , As you can see by that line of code they don't extend ItemShears, but extends ItemBase, which is Reliquary's base item.

**Comment by Peach774** [comment]
That doesn't explain anything to me, I don't speak code well. I'm moreso curious as to why they shouldn't extend ItemShears.

**Comment by palaster** [comment]
They could be easily switched to were they should extends ItemShears, and I almost created a pull request the moment I saw your issue to change it to extends ItemShears, but I didn't know if the underlying code in ItemBase is important enough to copy-paste into the newly extended file.

**Comment by P3pp3rF1y** [comment]
Sorry that I didn't comment on this for quite some time. I actually wasn't sure if I want shears of winter to be usable in farming station. But now I am pretty sure I do.

Converting them to extend ItemShears will have a benefit of them being usable in pedestal as well without additional changes.

I will include this change in one of the next releases.

**Comment by Peach774** [comment]
Awesome, thank you so much!

**Comment by P3pp3rF1y** [comment]
This change is in the latest version of Reliquary that I just uploaded to CF.
