### ISSUE TITLE
Pedestal and Mending Sword

### ISSUE THREAD

**Issue by Nammor** [P3pp3rF1y/Reliquary#142]
When put on a pedestal, a sword with the Mending enchantment doesn't repair itself with experience. I was wondering if this was a feature due to the fact that pedestal don't suck up XP on their own or if it was just not implemented yet ?

**Comment by P3pp3rF1y** [comment]
I have actually never considered that and to be honest I feel like that would be way too OP as even currently pedestal is pretty cheap for automation of mob grinder. 

And you're right that pedestal by itself has no understanding of xp so this would require more logic in it.

**Comment by Nammor** [comment]
Alright I totally understand, thanks for the fast reply ! :)
