### ISSUE TITLE
Reliquary causes NPE in Thaumic Tinkerer?

### ISSUE THREAD

**Issue by iExalt** [P3pp3rF1y/Reliquary#145]
I understand that [this](http://paste.ubuntu.com/23062831) is a Thaumic Tinkerer crash, but removing Reliquary makes it go away. Minecraft loads up fine, but when connecting to a server it crashes.

**Comment by P3pp3rF1y** [comment]
Try getting the latest NotEnoughResources. I fixed something in there today that I believe causes this issue as well.

**Comment by iExalt** [comment]
That fixed it, thank you. Out of curiosity, how are NER, Reliquary, Thaumic Tinkerer, and Galacticraft connected? If you don't mind, could you explain how a 3 line edit to NER fixed this issue?

**Comment by P3pp3rF1y** [comment]
Basically previously NER would cause a creeper to get hurt by lightning to get it displayed as charged. And it only needed this when the newest version of Reliquary (or the one with special drop for charged creeper) was in the pack. 
Problem was that it didn't pass any lightning entity in and both Galacticraft and TT handle hurt events and check what exactly hurt a mob and in both cases they were not prepared for nothing to be passed in the source of the damage (which to be honest should always be filled in as that's how the game works). 

Fix was easy - just mark the creeper as charged without the need to hit it with lightning bolt.
