### ISSUE TITLE
1.10.2 Crash on world load

### ISSUE THREAD

**Issue by MysticAura** [P3pp3rF1y/Reliquary#153]
Forge Version: 2073
Mod Version: Reliquary-1.10.2-1.3.3.496

Issue: Game ctd on world load or creation of new world
Steps to reproduce: Add alkahestry_tome to disabled_items in config

Removing the line again allows normal world load again.

[Crash Log](http://pastebin.com/i235cVLg)

This was a very difficult issue to narrow down. Hopefully it can be resolved in a way which still allows disabling of the tome.

**Comment by P3pp3rF1y** [comment]
So this was a bit of a derp on my side with one of the latest JEI compatibility changes. Fix is easy and done. I am going to release version with this fix in the next two days.

**Comment by MysticAura** [comment]
Derps happen to everyone. Thanks for looking into and resolving it so quickly :+1:

**Comment by P3pp3rF1y** [comment]
closing as the fix for this was already released
