### ISSUE TITLE
Crash before main menu loads

### ISSUE THREAD

**Issue by hexicles** [P3pp3rF1y/Reliquary#154]
Not entirely sure but I think it's some buggy bugginess from JEI and Reliquary

http://pastebin.com/wzsmLnwr

**Comment by P3pp3rF1y** [comment]
To be honest, based on stack trace this seems impossible to happen. So I am guessing that there is some corruption of file happening here.  Could you try to redownload the file and retest?

**Comment by BlueAvian** [comment]
Just Enough Resources is outdated, and there's later versions available that fix said problems. I was running across the same crash, until I narrowed down the specifics. The regular release (0.4.8.48) is entirely stable, from what I can tell from messing around.

**Comment by P3pp3rF1y** [comment]
Thanks for the comment, I thought I have dependencies set correctly to depend on the JER version that won't crash, but apparently not. Anyway closing this as this is an issue gone in past with the time that passed since the Reliquary / JER update to loot tables processing.
