### ISSUE TITLE
Alkahestry Tome Config

### ISSUE THREAD

**Issue by tikisri** [P3pp3rF1y/Reliquary#157]
When adding Fuels to the Tome of Alchestry, If adding Multiple entries of the same item with different metadata when Minecraft loads it rewrites the config leaving only the last entry as a fuel

example 

```
I:"silentgems:Gem" <
     0
     16
 >

I:"silentgems:Gem" <
     1
     16
 >

```

---

with these 2 entries the first entry is removed leaving only the second entry

**Comment by P3pp3rF1y** [comment]
Welp, my bad. Somehow I didn't realize that the first part is used as a key in a collection and thus it will only use one of them. I will move the meta part to the name (delimited by pipe symbol - e.g. "silentgems:Gem|1") should have a fix for this in a release in the next few days
