### ISSUE TITLE
Tome of alkahest IC2 problem

### ISSUE THREAD

**Issue by Peca21** [P3pp3rF1y/Reliquary#160]
You can't dupe IC2 ingots using Tome of alkahest, but JEI says you can.
Not sure if ic or reliquary problem.

Reliquary-1.10.2-1.3.3.521
industrialcraft-2-2.6.30-ex110
Forge-12.18.1.2073
Edit; Pack is FTB Unstable

**Comment by P3pp3rF1y** [comment]
So yeah, the code for ore dictionary items wasn't working properly. It's fixed now and thus it works with ic2 steel as well. I will be releasing another build later this week likely with this fix included.
