### ISSUE TITLE
Crash on minecraft start - why?? :(

### ISSUE THREAD

**Issue by lordshade88** [P3pp3rF1y/Reliquary#161]
I've tryed to take out other mods but cant get it to work, since a couple of ver. ago. i waited to see if a new ver. would fix it but no luck. the only thing i could do to get minecraft to start was remove reliq.
Maybe/probably/most likelely, ok i AM missing something derping it up, if someone could give me a hand or hint XP. thanks.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.0.2.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  LoadingPlugin (Quark-r1.0-55.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  offlineskins (OfflineSkins-1.10-v1.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  IC2core (industrialcraft-2-2.6.37-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 9/8/16 11:47 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: xreliquary/loot/EntityPowered
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:255)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: xreliquary/loot/EntityPowered
    at xreliquary.loot.EntityPowered$Serializer.<init>(EntityPowered.java:47)
    at xreliquary.init.ModLoot.init(ModLoot.java:33)
    at xreliquary.Reliquary.preInit(Reliquary.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: xreliquary.loot.EntityPowered
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 39 more
Caused by: java.lang.NoClassDefFoundError: jeresources/api/conditionals/ICustomEntityProperty
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 41 more
Caused by: java.lang.ClassNotFoundException: jeresources.api.conditionals.ICustomEntityProperty
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 45 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 355914864 bytes (339 MB) / 1089986560 bytes (1039 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2073 Optifine OptiFine_1.10.2_HD_U_C2 89 mods loaded, 89 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2073.jar) 
    UCH Forge{12.18.1.2073} [Minecraft Forge](forge-1.10.2-12.18.1.2073.jar) 
    UCH Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.1.0.2.jar) 
    UCH OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)](minecraft.jar) 
    UCH LunatriusCore{1.1.2.36} [LunatriusCore](0-LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCH Schematica{1.7.8.151} [Schematica](0-Schematica-1.10.2-1.7.8.151-universal.jar) 
    UCH cei{1.3} [Chunk Edge Indicator](1.10-chunkedgeindicator-1.3.jar) 
    UCH ambidextrous{1.0} [Ambidextrous](ambidextrous-1.0.jar) 
    UCH Aroma1997CoreHelper{1.1.0.2} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.1.0.2.jar) 
    UCH AromaBackup{1.0.1.1} [AromaBackup](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCH AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCH Psi{r1.0-39} [Psi](Psi-r1.0-39.jar) 
    UCH Quark{r1.0-55} [Quark](Quark-r1.0-55.jar) 
    UCH AutoRegLib{1.0-1} [AutoRegLib](AutoRegLib-1.0-1.jar) 
    UCH backpack{3.0.1} [Backpack](backpack-3.0.1-1.10.2.jar) 
    UCH bagginses{2.4.2d} [Bagginses](Bagginses-1.10.2-3.0.4b.jar) 
    UCH Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCH bdlib{1.12.2.10} [BD Lib](bdlib-1.12.2.10-mc1.10.2.jar) 
    UCH BiomesOPlenty{5.0.0.2082} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2082-universal.jar) 
    UCH guideapi{@VERSION@} [Guide-API](Guide-API-1.10.2-2.0.2-45.jar) 
    UCH ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCH mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
    UCH tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct](TConstruct-1.10.2-2.4.0.jar) 
    UCH immersiveengineering{${version}} [Immersive Engineering](ImmersiveEngineering-0.10-40.jar) 
    UCH JEI{3.9.0.247} [Just Enough Items](jei_1.10.2-3.9.0.247.jar) 
    UCH BloodMagic{1.9.4-2.0.4-58} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.4-58.jar) 
    UCH Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9.4-1.4.1.jar) 
    UCH Botania{r1.8-321} [Botania](Botania-unofficial.r1.8-321.jar) 
    UCH Bullseye{1.0.3} [Bullseye](Bullseye-1.9.4-1.0.3.jar) 
    UCH Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCH mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UCH CharsetLib{0.3.0-pre15} [â€½](Charset-0.3.0-pre15.jar) 
    UCH CharsetAudio{0.3.0-pre15} [â™«](Charset-0.3.0-pre15.jar) 
    UCH CharsetCarts{0.3.0-pre15} [U](Charset-0.3.0-pre15.jar) 
    UCH CharsetDecoration{0.3.0-pre15} [âš?](Charset-0.3.0-pre15.jar) 
    UCH CharsetDrama{0.3.0-pre15} [!](Charset-0.3.0-pre15.jar) 
    UCH CharsetFarming{0.3.0-pre15} [;](Charset-0.3.0-pre15.jar) 
    UCH CharsetGates{0.3.0-pre15} [&](Charset-0.3.0-pre15.jar) 
    UCH CharsetPipes{0.3.0-pre15} [|](Charset-0.3.0-pre15.jar) 
    UCH CharsetStorage{0.3.0-pre15} [#](Charset-0.3.0-pre15.jar) 
    UCH CharsetTweaks{0.3.0-pre15} [*](Charset-0.3.0-pre15.jar) 
    UCH CharsetWires{0.3.0-pre15} [+](Charset-0.3.0-pre15.jar) 
    UCH CharsetWrench{0.3.0-pre15} [/](Charset-0.3.0-pre15.jar) 
    UCH chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-MC1.9.4-0.0.6.33.jar) 
    UCH chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1.jar) 
    UCH ElecCore{1.5.303} [ElecCore](ElecCore-1.9.4-1.5.303.jar) 
    UCH IC2{2.6.37-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.37-ex110.jar) 
    UCH OpenComputers{1.6.0.3-rc.1} [OpenComputers](OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    UCH deepresonance{1.2.2} [DeepResonance](deepresonance-1.10-1.2.2.jar) 
    UCH endercore{1.10.2-0.4.1.54-beta} [EnderCore](EnderCore-1.10.2-0.4.1.54-beta.jar) 
    UCH Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCH EnderIO{1.10.2-3.0.1.104_beta} [Ender IO](EnderIO-1.10.2-3.0.1.104_beta.jar) 
    UCH EnderZoo{1.10-1.2.3.43} [Ender Zoo](EnderZoo-1.10-1.2.3.43.jar) 
    UCH flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks](flatcoloredblocks-mc1.10-v4.1.jar) 
    UCH forestry{5.2.9.242} [Forestry](forestry_1.10.2-5.2.9.242.jar) 
    UCH gearswap{1.2.6} [Gear Swapper](gearswap-1.9.4-1.2.6.jar) 
    UCH gendustry{1.6.4.19} [GenDustry](gendustry-1.6.4.19-mc1.10.2.jar) 
    UCH graves{1.10.2-b28-universal} [Graves Mod](Graves-1.10.2-b28-universal.jar) 
    UCH inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCH ironchest{1.10.2-7.0.9.796} [Iron Chest](ironchest-1.10.2-7.0.9.796.jar) 
    UCH itemscroller{0.5.1} [Item Scroller](itemscroller-1.10.2-0.5.1.jar) 
    UCH JEFB{1.0.3} [Just Enough Forestry Bees](jefb_1.10.2-1.0.3.jar) 
    UCH journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCH jeresources{0.4.6.44} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.6.44.jar) 
    UCH llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded](LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
    UCH minemenu{1.4.4} [MineMenu](MineMenu-1.10.X-1.4.4.B9-universal.jar) 
    UCH testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCH Morpheus{1.10.2-3.1.7} [Morpheus](Morpheus-1.10.2-3.1.7.jar) 
    UCH notenoughwands{1.3.6} [Not Enough Wands](notenoughwands-1.10-1.3.6.jar) 
    UCH ObsidianPlates{1.1.1} [Obsidian Plates](ObsidianPlates-1.1.1_1.9.4.jar) 
    UCH offlineskins{1.10-v1} [OfflineSkins](OfflineSkins-1.10-v1.jar) 
    UCH harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
    UCH ProjectE{1.10.2-PE1.0.6B} [ProjectE](ProjectE-1.10.2-PE1.0.6B.jar) 
    UCH randomthings{3.7.5} [Random Things](RandomThings-MC1.10.2-3.7.5.jar) 
    UCE xreliquary{1.10.2-1.3.3.521} [Reliquary](Reliquary-1.10.2-1.3.3.521.jar) 
    UCH rftools{5.22} [RFTools](rftools-1.10-5.22.jar) 
    UCH rftoolsdim{4.30beta48} [RFTools Dimensions](rftoolsdim-1.10-4.30beta48.jar) 
    UCH roots{0.202} [Roots](roots-1.10.2-0.202.0.jar) 
    UCH seedcopy{3.0.2} [SeedCopy](SeedCopy-1.9-3.0.2.jar) 
    UCH Signals{1.0} [Signals](Signals-1.10.2-0.4.3-universal.jar) 
    UCH SimpleDimensions{1.3} [Simple Dimensions](SimpleDimensions-MC1.10-1.3.jar) 
    UCH simpleretrogen{4.0.1+8} [Simple Retrogen](simpleretrogen-1.10-4.0.1+8.jar) 
    UCH SolarFluxReborn{1.1r} [Solar Flux Reborn](SolarFluxReborn_1.10.2-1.1r.jar) 
    UCH StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCH theoneprobe{1.0.15} [The One Probe](theoneprobe-1.10-1.0.15.jar) 
    UCH waystones{2.0.3} [Waystones](Waystones_1.10.2-2.0.3.jar) 
    UCH Zoology{1.0} [Zoology](zoology-1.10-alpha-1.0.0.jar) 
    UCH UniDict{1.10.2-1.8c} [UniDict](UniDict-1.10.2-1.8c.jar) 
    Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.0.2.jar)

LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (Quark-r1.0-55.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
offlineskins (OfflineSkins-1.10-v1.jar)
  lain.mods.skins.asm.ASMTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.37-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon R7 200 Series'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * AromaBackupAPI (1.0) from AromaBackup-1.9.4-1.0.1.1.jar
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.4-58.jar
    * BotaniaAPI (79) from Botania-unofficial.r1.8-321.jar
    * CharsetAPI (0.1) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Audio (0.0) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Lib (0.2) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Pipes (0.3) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Storage (0.1) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Tape (0.0) from Charset-0.3.0-pre15.jar
    * CharsetAPI|Wires (0.3) from Charset-0.3.0-pre15.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.33.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.33.jar
    * ChiselsAndBitsAPI (11.7.0) from chiselsandbits-12.1.jar
    * CoFHAPI (1.8.9R1.2.0B1) from ImmersiveEngineering-0.10-40.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from EnderIO-1.10.2-3.0.1.104_beta.jar
    * CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.10-2.0.1.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.10-1.2.2.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.303.jar
    * EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.104_beta.jar
    * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.104_beta.jar
    * EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.104_beta.jar
    * EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.104_beta.jar
    * ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|core (5.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|greenhouse (5.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.9.242.jar
    * ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.9.242.jar
    * gendustryAPI (2.3.0) from gendustry-1.6.4.19-mc1.10.2.jar
    * Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
    * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-40.jar
    * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-40.jar
    * jeresources|API (0.4.6.44) from JustEnoughResources-1.10.2-0.4.6.44.jar
    * journeymap|client-api (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-display (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-event (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-model (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-util (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * JustEnoughItemsAPI (4.1.0) from jei_1.10.2-3.9.0.247.jar
    * McJtyLib (1.10-2.0.1) from mcjtylib-1.10-2.0.1.jar
    * OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * ProjectEAPI (1.9.4-1.0.0) from ProjectE-1.10.2-PE1.0.6B.jar
    * PsiAPI (2) from Psi-r1.0-39.jar
    * SchematicaAPI (1.1) from 0-Schematica-1.10.2-1.7.8.151-universal.jar
    * SchematicaAPI|Events (1.1) from 0-Schematica-1.10.2-1.7.8.151-universal.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
              * Optifine is installed. This is NOT supported.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Luis/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.1.jar!/cofh/api/energy/TileEnergyHandler.class

OptiFine Version: OptiFine_1.10.2_HD_U_C2
Render Distance Chunks: 10
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13416 Compatibility Profile Context 15.300.1025.1001
OpenGlRenderer: AMD Radeon R7 200 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 6
```

**Comment by P3pp3rF1y** [comment]
have you tried updating just enough resources to much newer version? Looks like I don't have dependencies setup properly for that, but the version you have there is very old and there have been quite a few releases of JER in the meantime.

**Comment by lordshade88** [comment]
Well Sr. I updates a couple of mods today, and JER was one of them. Now it doesnt crash so i guess it was as you thought. Thanks for making the time to check my post, have a cookie!

**Comment by P3pp3rF1y** [comment]
thanks for letting me know
