### ISSUE TITLE
Feature Request:  Token/Item that gives a regeneration buff (when placed in a pedestal)

### ISSUE THREAD

**Issue by mahldcat** [P3pp3rF1y/Reliquary#162]
(Main) Usage Case:

Player wants to make use of Blood Magic, which requires taking hits to their health bar (and on 1.10 requires a LOT of food to maintain natural regen).  

Instead, they put down a pedestal + regen item next to their altar, which gives them a regen in a 2-3 block radius, and they can bootstrap things a bit faster....

**Comment by P3pp3rF1y** [comment]
So far all the items that work in pedestal also do similar stuff when just in hand. 
So what item would this be for regen? And to give permanent regen I would think it should be very expensive.

An alternative in Reliquary is brewing potions which can give you pretty long regen so unless that item makes a lot of sense to get added I would consider potion the proper way to go.
