### ISSUE TITLE
[1.3.3.521] Crash with latest TiC version

### ISSUE THREAD

**Issue by SPMoo66** [P3pp3rF1y/Reliquary#163]
Not 100% sure if this is yours or Boni's... Sorry if I'm handing this to the wrong person

http://pastebin.com/1VQX031s

**Comment by P3pp3rF1y** [comment]
That is mine. Looks like boni moved some stuff around so I have to make a change on my side to adjust for that.

**Comment by bonii-xx** [comment]
I had a look at your code. What you're doing is generally not very... smart.
Go and use ObjectHolder to get the actual item instances injected, and compare against those instead of relying on classes.

**Comment by P3pp3rF1y** [comment]
@bonii-xx Will take a look at that. To be honest I am not even sure why I'm not simply keeping a list of Item instances there as I don't see a reason for classes either. Maybe I got too carried away by the second part where I actually do need classes as I need to create instances of wrappers for every pedestal where the item is used.

**Comment by P3pp3rF1y** [comment]
This is resolved in the latest release. I am keeping the ObjectHolder note in my things to refactor list so that should take care of that part.
