### ISSUE TITLE
[Feature request] Disable showing Alkahestry Tome recipes in JEI if it's disabled

### ISSUE THREAD

**Issue by rigerc** [P3pp3rF1y/Reliquary#165]
It's pretty confusing for new players to see the recipes without seeing the tome in JEI, maybe the tome's JEI integration could be a conditional feature?

Keep up the great work :)

**Comment by P3pp3rF1y** [comment]
This is actually the case when tome is disabled using reliquary's config. I don't believe I have a way of telling that something else (some other mod) has disabled my item after I have enabled it. 
So modpacks where this is an issue should use the config option to disable it.

Let me know if this is not the case and the config option doesn't work in your case.

**Comment by rigerc** [comment]
Yeah, config option doesn't seem to work for me. I'm using this:

```

    # List of items and blocks that are supposed to be disabled. By default this is empty, but you can use the names of the blocks and items (e.g. "fertile_lilypad", "wraith_node", "glacial_staff") in this list and mod will not register those. It will also not register any recipes that include whatever is disabled. [default: ]
    S:disabled_items_blocks <
        "alkahestry_tome",
        "interdiction_torch",
        "fertile_lilypad"
     >
```

It did work at some point.

**Comment by P3pp3rF1y** [comment]
it should be (no parentheses or commas)
    S:disabled_items_blocks <
        alkahestry_tome
        interdiction_torch
        fertile_lilypad
     >

**Comment by rigerc** [comment]
Ah, that explains it! Thanks. I was going off the example, so maybe it's a bit confusing :)
