### ISSUE TITLE
Witch Hats still dropping

### ISSUE THREAD

**Issue by MrAmericanMike** [P3pp3rF1y/Reliquary#167]
So I set on the configs:

> ```
> I:witch_hat_base=0
> I:witch_hat_looting=0
> ```

But the hats still dropping when killing witches.

Version Reliquary-1.10.2-1.3.3.521

Not sure what could be causing it, if it's a bug on the mod itself, or maybe the iteraction with other mods in the pack I'm using it.

Well, if you need any more information let me know ;)

**Comment by P3pp3rF1y** [comment]
These config settings are no longer used. They are in your configs as relics from the past and are not generated in new ones.

The new implementation uses loot tables similar to vanilla ones.

I have never done that, but you should be able to override these similar to how textures can be overriden. Search for loot tables on minecraft wiki. 
The ones for Reliquary can be found here https://github.com/P3pp3rF1y/Reliquary/tree/1.10.2/src/main/resources/assets/xreliquary/loot_tables/inject/entities

**Comment by MrAmericanMike** [comment]
Thanks a lot, gonna take a look into that ;)
