### ISSUE TITLE
Baubles API appears to be an outdated version

### ISSUE THREAD

**Issue by MercuriusXeno** [P3pp3rF1y/Reliquary#168]
Since an update to the Baubles API, Reliquary is now trying to access a method the API either renamed or moved. (re: http://pastebin.com/WT9DichG)

**Comment by P3pp3rF1y** [comment]
Thanks for reporting, but the last version of baubles on curseforge is from May 19th and that is the one I am testing and building against. 

Is it possible that Forgecraft has a not public yet build of baubles?

**Comment by P3pp3rF1y** [comment]
Just checked Baubles on github and yes Azanor made some updates there, particularly got rid of using IInventory and started using IBaublesItemHandler as a return type instead. 
So I will need to fix this just need to figure out how I am going to do that when I only refer to external dependencies and there's currently no public build of Baubles that I know of.

**Comment by P3pp3rF1y** [comment]
Latest release has support for official Baubles release with item handler implementation.
