### ISSUE TITLE
Tome of Alkahestry not working on server

### ISSUE THREAD

**Issue by MrNinja93** [P3pp3rF1y/Reliquary#172]
Tome of Alkahestry works in singleplayer as expected but not on a multiplayer server, Unless I'm being an idiot doing something wrong.

Config on server is the same as client config (Same mod versions too) , Tome isn't disabled in config, no minetweaker disabling etc. 

Config client and server side link if you want to check (Github confirmed they were identical, also both are autogenerated config from jar file)

https://github.com/MrNinja93/MinecraftConfigs/blob/master/xreliquary.cfg

---
#### Affected Versions:

Minecraft: 1.10.2
Forge 2094
Reliquary  568

**Comment by P3pp3rF1y** [comment]
In what way does it not work for you? crafting / charging / discharging / duplicating ? I have just retested on my local server and seems to work fine.

**Comment by MrNinja93** [comment]
No idea why it didn't play ball but server generating its own file and client generating their own file separately has seemed to fix the issue despite that config being identical to the ones I provided Client and Server in the first instance. 

For reference incase it is still a bug with config loading it only affected duplicating items, every other aspect of reliquary as far as I could tell worked as intended.

**Comment by P3pp3rF1y** [comment]
Did you check if you could see the duplication recipes in JEI? If they were not there that would suggest there was an issue with loading those from config.
