### ISSUE TITLE
Suggestion: Pedestals with swords ignore tamed pets.

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#174]
I noticed that pets are not ignored by sword pedestals, which can be an issue if you don't remember to make your pets sit or otherwise make sure to stay out of range of the pedestal. I think this would be a useful change.

**Comment by P3pp3rF1y** [comment]
Sounds like a good one. Yeah they don't discriminate so they attack anything that's not a player or boss.
