### ISSUE TITLE
Tome of Alkahestry not duplicating items

### ISSUE THREAD

**Issue by WesCook** [P3pp3rF1y/Reliquary#179]
In the latest version of Reliquary (1.10.2-1.3.3.571), I'm unable to duplicate items using the tome.  I've tested in singleplayer and multiplayer, and have filled the book completely with redstone.

Others have reported the problem here as well:
https://www.reddit.com/r/HermitPack/comments/57o1x5/tome_of_alkahestry_problem/

In my case, I'm playing a pack based on (but not the same as) HermitPack.

**Comment by blisterfingers** [comment]
Can confirm, same version in unmodified HermitCraft pack. Double checked the config and everything looks okay, there's just nothing showing up in the crafting result.

**Comment by P3pp3rF1y** [comment]
That unfortunately is some kind of mod interaction causing this. The tome works correctly in the version that they have in the pack and also the config is correctly setup in there. I unfortunately don't have enough time to debug why Reliquary doesn't work correctly when some packs have issues like this so I would suggest that you let them know about the bug in ftb forum where they track these https://forum.feed-the-beast.com/forum/ftb-presents-hermitpack-1-10-2.253/

**Comment by MrNinja93** [comment]
Saw this bug on the FTB forums and did a quick test and the hermitcraft pack issue is the same as the one I encountered in maintaining a private pack https://github.com/P3pp3rF1y/Reliquary/issues/172 If you provide a config file for reliquary that isnt auto-generated/unchanged it breaks the tomes duping ability for some reason (even if config generated and provided are identical), deleting the config file and letting the mod generate its own fixes the issue and items dupe as intended.

Bug can be reproduced on demand with just reliquary +Forge installed 

**Edit:**

**To reproduce**
1. With a clean install with just Reliquary, allow mod to generate its own config file, load game/world dupe item with tome, should work as normal.
2. Close World/Minecraft copy that config file somewhere.
3. Delete the original file in your config folder.
4. Paste in the file you copied.
5. Load Minecraft/world and attempt to dupe item.

**Comment by MrNinja93** [comment]
Bug is caused by changes made in commit https://github.com/P3pp3rF1y/Reliquary/commit/f681a9700ffb3137963787840eea86368a8d75bf

Versions/commits prior to this don't have the bug. 

Edit: In terms of curse versions, 521 onwards, prior to that configs work fine if imported.

**Comment by P3pp3rF1y** [comment]
I have just tried this copy past method with the newest and it works correctly. I have even tried copy pasting the config from HermitPack and running Reliquary with it and it runs correctly as well. Can you attach the copy pasted version of config that doesn't work for you?

**Comment by MrNinja93** [comment]
Config being auto-generated that works previous to me copy/pasting it into config folder. 

https://github.com/MrNinja93/reliquary-testing/blob/master/xreliquary.cfg

Reliquary: 571
Forge tested with 2094 and 2107 and replicates in both.

**Edit** 
Exported profile from curse https://www.dropbox.com/s/wryki60uqcayda0/Reliquary%20testing-1.0.zip?dl=0 

Config included is currently in "break mode" on my version

**Comment by blisterfingers** [comment]
I can confirm the problem.
1. Added only Reliquary to a pack on Curse.
2. Boot up and all works as expected.
3. Shut down and reboot and it won't work anymore.

Forge 2107, Reliquary 571 and on Windows.

**Comment by MrNinja93** [comment]
Actually yeah just reloading the game breaks it. 

From FTB issues thread user mentioned deleting meta tags ("|0")on tome crafting recipes in config fixes it indefinitely, confirmed by me in my world/config and stacks up with me not being able to replicate the bug pre commit f681a97 which implemented that functionality

**Comment by P3pp3rF1y** [comment]
I have figure out what's causing the issue with new configs not working after restart (I was adding meta part of the item key twice to in memory dictionary on the second and consecutive loads). I have a fix and will release that soon. I will test this with HermitPack it may be the answer to why that is not working, not sure yet.

**Comment by P3pp3rF1y** [comment]
And just tested with HermitPack and in fact that was the issue. I will be releasing the new build either later today or more probably tomorrow so you should get this fix included in there. Of course FTB may take a few more days to update official HermitPack.

**Comment by MrNinja93** [comment]
Yay! Don't actually play Hermitcraft but the fix will do nicely for my private pack which is actually overdue an update.

**Comment by WesCook** [comment]
Thanks for the fix, @P3pp3rF1y!
