### ISSUE TITLE
Tome of Alkahestry Bug

### ISSUE THREAD

**Issue by Hudster2001** [P3pp3rF1y/Reliquary#187]
I'm playing with this mod on the Hermitpack Modpack and I found a bug.

If you crouch while using the tome of Alkahestry, it gives you the item, but the book doesn't use any Redstone.
I now have 2500 Wither stars for free.

**Comment by P3pp3rF1y** [comment]
What version of Reliquary have you got? And does that not happen if you just duplicate the items without using shift?

**Comment by Hudster2001** [comment]
I have version 1.3.3.581.

I tried it without using shift and I could replicate the nether stars without using shift.
So far I managed to get over 15,000 nether stars without the tome losing any power or needing recharged

**Comment by P3pp3rF1y** [comment]
So that is the bug that was fixed in version 585, you just need an updated version of Reliquary then.

**Comment by Hudster2001** [comment]
Excellent. Sorry for the Bug report. As I said, I'm using it in the Hermitpack and their version must be out of date
