### ISSUE TITLE
[Suggestion] Coin of Fortune & Solegnolia (Botania)

### ISSUE THREAD

**Issue by Discomanco** [P3pp3rF1y/Reliquary#189]
Short version: Make Coin of Fortune not draw in items in Solegnolia's radius

Coin of Fortune is great, there are however, certain places where it's required to be off due to how some items are made (Immersive Engineering, Applied Energistics, Botania).
Botania has a flower called Solegnolia, which disables their Ring of Magnetization's magnetic pull in a small radius, which can be super handy for certain areas. I would like to suggest if Solegnolia can affect Coin of Fortune as well, maybe as a config setting?

Or, maybe an item to put on the Pedestal that disables Coin of Fortunes magnetic pull within a certain radius?

**Comment by P3pp3rF1y** [comment]
These are some interesting ideas I will certainly look into implementing at least some of this. 

In terms of immersive engineering that should be set as we have agreed with Blu on attribute that he assigns to item entities on conveyors and thus fortune coin shouldn't be picking them up. Do you mean something else or is this not working for you - that is - is it picking up items from conveyors?

**Comment by Discomanco** [comment]
The issue is mainly with the Crusher. I had thoughts about the conveyor belts too, but my friend assured me that they act like chests, and can't have items pulled from them.
Now the Crusher though, items has to be dropped into them, before being put into the Crushers local storage, whether through belts, droppers or done manually, but the Coin can easily pick them all up before they get that far.
Another "issue" is with Applied Energistics, and the crafting of Pure Crystals and Fluix Crystals. They need to be put in water to grow/merge, and are not immune to a magnetic pull
