### ISSUE TITLE
1.10.2 - Ender Staff Tooltip Incorrect when out of players' hand (Dedicated Server, Multiplayer)

### ISSUE THREAD

**Issue by SephirothWS** [P3pp3rF1y/Reliquary#193]
This is the correct tooltip for this item, it reports I have 12 ender pearls that was absorbed by the staff:
![2016-11-26_10 38 43](https://cloud.githubusercontent.com/assets/9165737/20641803/868b6216-b3c5-11e6-8532-92b178b89446.png)

This is incorrect handling: You mentioned something about this being a dedicated server issue and packet issue where the data about the item doesn't get sent unless its in the players' hand.
![2016-11-26_10 38 48](https://cloud.githubusercontent.com/assets/9165737/20641807/9cf4add2-b3c5-11e6-9de2-3fad7f51e326.png)
![2016-11-26_10 40 24](https://cloud.githubusercontent.com/assets/9165737/20641808/9cf7768e-b3c5-11e6-9717-73f348a1cb1c.png)
![2016-11-26_10 40 53](https://cloud.githubusercontent.com/assets/9165737/20641809/9cfbf59c-b3c5-11e6-96eb-65ace21a756b.png)

**Comment by P3pp3rF1y** [comment]
This is now fixed in 1.12 release. I am not going to fix in previous versions as it requires a forge change which isn't present in those and likely won't be.
