### ISSUE TITLE
[1.11]Rending Gale bug

### ISSUE THREAD

**Issue by Myknakryu** [P3pp3rF1y/Reliquary#196]
Versions:
Forge version: 2188
Minecraft version: 1.11
Reliquary version: 1.3.3.597

What happend:
Game crashed after launching world or connecting to server

How to recreate:
Get Rending Gale, keep it in hand. Save game when Rending Gale is held. Restart game by closing it. Launch the game and the world/server.

Logs:
http://pastebin.com/JZihE8dV

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. Looks like fontRenderer isn't initialized by the time Reliquary tries to render text. I will put some additional checks in to stop this from happening.

**Comment by P3pp3rF1y** [comment]
Closing as it was resolved back in December
