### ISSUE TITLE
Pedestals convert item stacks into a single item

### ISSUE THREAD

**Issue by SharkWipf** [P3pp3rF1y/Reliquary#198]
Same issue as TrainerGuy22/Reliquary#231 but on current 1.10.2 (Reliquary-1.10.2-1.3.3.585.jar). 
Inserting stacks into pedestals, i.e. through the AE2 ME interface for autocrafting, eats the entire stack, but outputs only a single item when removed from the pedestal. 
Best fix would probably not be to output the stack correctly, but to only accept single items as input (like the TCon drying rack).

**Comment by P3pp3rF1y** [comment]
So I am actually unable to recreate this issue. I get a stack of however many items have been inserted into the pedestal. I tried that with hopper and stack of tracks and stack of buckets. 

So in your case is it happening with just the ME interface? And how exactly it works actually? or did you mean storage bus? is it with display only pedestal or the one with the button? What item are you using in the pedestal?

**Comment by SharkWipf** [comment]
I've done some testing, it seems to work fine when one item is inserted at a time (I.E. by using a hopper), however, when more than 1 item is inserted at once the others get lost.  
This happens with both types of pedestals.  
The easiest way I've found to replicate this is by hooking up a chest to a pedestal using an EnderIO item conduit (which transfers 4 items at a time without upgrades), and adding a stack of any item to the chest.  
By the time the chest is empty, taking the item out of the pedestal will only give you back a single item.

**Comment by P3pp3rF1y** [comment]
Thanks for this, looks like I left a bit of code in there from the time I wanted to limit this to stack size 1. Hopper didn't trigger it, but other methods did and thus have deleted the rest. Will be fixed in the next release.

**Comment by SharkWipf** [comment]
Nice! Thanks!
