### ISSUE TITLE
Urgent issue on 1.7.10 that needs to be fixed

### ISSUE THREAD

**Issue by Sunconure11** [P3pp3rF1y/Reliquary#200]
If you have the mod Thaumic Horizons installed, as well as Thaumcraft, and try to craft a golemancer's bell, you will crash with this error (happens only on servers):

http://pastebin.com/hb8J8CUP

**Comment by P3pp3rF1y** [comment]
So I don't really support 1.7.10 anymore and don't really want to get to debugging with multiple mods installed as I have plenty of stuff going on for 1.10.2 and 1.11. Also the only version I have released was back in August and I know that it's used in packs where the other two mods are used and I haven't heard any issues from those.
However I checked the line where it breaks and there could be two things happening - either Tome of Alkahestry was disabled (or removed with mine tweaker) in your pack or the item that's used in the crafting recipe isn't properly registered. If it's the tome that's disabled you could just enable it and ti should start working. Improperly registered item is a different case, which neither of us will be able to fix. 
Anyway if this fails I would just suggest cheat in the bell as this is usually just a one time craft thing.

**Comment by Sunconure11** [comment]
Tome of Alkahestry is enabled. I have an NPC at spawn that distributes them in the event of a crash.

**Comment by P3pp3rF1y** [comment]
Closing as not to be fixed
