### ISSUE TITLE
Crash: java.lang.ClassCastException

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#204]
Don't know if thats already fixed since that crash is not on the latest version, but I couldn't find a closed issue with that crash so I'll post it anyways:

http://pastebin.com/jwqFr7js

**Comment by P3pp3rF1y** [comment]
What bullets have you used? Ones with potion effects or without?

**Comment by P3pp3rF1y** [comment]
Also I have tried recreating this and cannot get it to crash and looking at the code I don't even see how this exception could have happened. Almost as if something else is messing with entity data. So it would definitely help to know the steps to recreate the issue here.

**Comment by ghost** [comment]
Yea of course. I had a quick glance at the file myself, it seems pretty odd indeed. Since that didn't happen to myself (I only run the servers) I'll have to get in touch with the player that reported that crash to get exact details on what he did, but he said it even happens now if he gets near the place of the first crash (don't know yet if it is the same stacktrace tho). All I know at the moment is that he hit a charged creeper with most likely something from this mod.

**Comment by ghost** [comment]
Ah wait a moment, isn't the shot listed in the crash report? (line 59: Entity Type: xreliquary.entityStormShot (xreliquary.entities.shot.EntityStormShot)) So my blind guess to reproduce this would be to target that one at a creeper.

**Comment by P3pp3rF1y** [comment]
So it definitely isn't as simple as that. Just tried it with both storm shots without and with potion effect and neither had any issues. And yes tried it on both creeper and other blocks/entities.

**Comment by ghost** [comment]
I've got the same issue only on xreliquary.entitySeekerShot.  https://www.hastebin.com/arirejojur.rb

In the meantime I tried to kill the entity without success have you found a way to clear this issue from a location?

**Comment by P3pp3rF1y** [comment]
Based on what I can see MCEdit should be able to delete entities and that is probably the only way, because other stuff uses commands only for loaded entities, but by that time it's too late because you crash.

**Comment by P3pp3rF1y** [comment]
Closing as I don't have a solution for this issue and it only affected worlds that had earlier version of Reliquary and then updated after update in early December. Also havent' heard of this lately so it's very likely there is a very minimal number of these worlds still around.
