### ISSUE TITLE
[1.10.2] Reliquary causes server crash when used with Colossalchests

### ISSUE THREAD

**Issue by Morpheus1101** [P3pp3rF1y/Reliquary#205]
Reproduce(Im using MMD-Dev Priv Pack)

ok atm, with the current pack using the latest ColossalChests available from Curse 1.4.1, i hooked up a 9x9 Diamond Colossal Chest with a Builder using silk quarry from rftools, powered by a DraconicEvolution creative power source with a Diamond Chest from iron chests mod on top of the builder connected to the colossal chest via an Item Conduit from EnderIO with maximum speed upgrades in the conduit.

When opening the colossal chest being completely empty, you instantly stop getting updates once you close chest//open chest untill the server kicks the client out(no crash) .. after 10-30sec attempt to rejoin server at which time the server has crashed due to lagging out and watchdog force closing the server(according to console).

Server Generated Crash Report @ https://puu.sh/t1ucs/f0cfee017d.txt

**Comment by P3pp3rF1y** [comment]
Would you be able to send me your player's inventory screenshot? That logic from crash dump only gets triggered if there's item handler in either the chest or player's inventory. That is inly if you have bags or similar items in there. I assume the chest is full of mined ores and such. 
It could also be collosal chests doing something else with item handlers but want to understand the full context first.

**Comment by Morpheus1101** [comment]
Im not sure about my inv at the time, but the colossal chest was empty.  If i had to assume, the only items in my inv would be of those needed to make what i described above

**Comment by P3pp3rF1y** [comment]
so there was a call in my code which actually instead of getting the inventory slots and then looking at their size actually copied the whole inventory behind the scenes before checking the size. And yeah with more than 78k slots that takes quite some time. I have changed that to the direct call to inventory slots which now takes a few milliseconds to query even such a huge inventory. will get you build shortly

**Comment by Morpheus1101** [comment]
thanks :-D

**Comment by P3pp3rF1y** [comment]
And now there is a new build on CF Reliquary-1.10.2-1.3.3.615.jar

**Comment by Morpheus1101** [comment]
This indeed solved the issue and dosent repeat now.  Thankyou for a quick fix :)
