### ISSUE TITLE
[Bug] Looping Crash when Reliquary apothecary cauldron is filled by ExtraUtils mechanical user

### ISSUE THREAD

**Issue by MysticAura** [P3pp3rF1y/Reliquary#208]
MC: 1.10.2
Forge: 2185
Mods Involved: extrautils2-1.10.2-1.1.3a, Reliquary-1.10.2-1.3.3.585

Server put into a crash loop after a mechanical user attempted to put water in the apothecary cauldron. Making a report to both your mods.

[Crash Log](http://pastebin.com/u3NjSfFH)

**Comment by P3pp3rF1y** [comment]
I have this fixed in dev. How fast do you need this released? (I mean is it crashing on your server currently?). 
I could release earlier if there's a need.

**Comment by MysticAura** [comment]
I managed to save the player from the loop by removing the block. So it's not required this second, but soon would be helpful as I have the pack update ready to go with other fixes as well :)  Sorry for having the report on the wrong fork, not sure why curse directed me there.

**Comment by P3pp3rF1y** [comment]
I guess that's because there are two Reliquary projects on there. One of which is for 1.7.10 and less and that's also the one that I don't have access to and directs to the issue tracker where you logged it.
