### ISSUE TITLE
Issue with enchanted Charms and Charm Belt

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#210]
Hello, I don't know if this is deliberate or if it has been corrected by now but any charm will lose its enchantments when it is stored in the charm belt.

EDIT : Version 1.10.2-1.3.3.615

**Comment by P3pp3rF1y** [comment]
that is deliberate and I actually made a change in one of the recent versions to ban the charms from getting any enchantments just to save on confusion

**Comment by ghost** [comment]
Oh, no mending anymore :,(. Thanks for the answer.

**Comment by P3pp3rF1y** [comment]
I believe I have put the condition to ban mending when I first released the charms with damage. If not it was always intention for them to not be affected by mending or unbreaking.
