### ISSUE TITLE
Server crashes when updating to forge build 2224 (works fine in 2214)

### ISSUE THREAD

**Issue by jimmydagumjr** [P3pp3rF1y/Reliquary#211]
I'm updating my forge because a lot of other mods require my forge to be at least build 2223 and whenever I update everything works fine but reliquary. The game works fine if I delete reliquary out of the server's mods but this mod is amazing and I want to keep it.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.7.9.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  LoadingPlugin (Quark-r1.2-74.jar)
  IvToolkit (IvToolkit-1.3.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.0-anarchy.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/21/17 3:13 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Reliquary (xreliquary)
Caused by: java.lang.RuntimeException: Invalid class class xreliquary.entities.EntityLyssaHook no constructor taking net.minecraft.world.World
	at net.minecraftforge.fml.common.registry.EntityEntry.init(EntityEntry.java:55)
	at net.minecraftforge.fml.common.registry.EntityEntry.<init>(EntityEntry.java:43)
	at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:183)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:151)
	at xreliquary.common.CommonProxy.registerEntities(CommonProxy.java:67)
	at xreliquary.common.CommonProxy.init(CommonProxy.java:45)
	at xreliquary.Reliquary.init(Reliquary.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:809)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 630410728 bytes (601 MB) / 1004011520 bytes (957 MB) up to 5298978816 bytes (5053 MB)
	JVM Flags: 16 total; -Xms1G -Xmx5G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2224 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	UCHI	forge{13.20.0.2224} [Minecraft Forge] (forge.jar) 
	UCHI	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	ivtoolkit{1.3.1} [IvToolkit] (minecraft.jar) 
	UCHI	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHI	uncraftingtable{1.7.1-pre3} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre3.jar) 
	UCHI	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHI	actuallyadditions{1.11.2-r96} [Actually Additions] (ActuallyAdditions-1.11.2-r96.jar) 
	UCHI	forgeendertech{2.0.1.0} [forgeendertech] (ForgeEndertech-1.11.2-2.0.1.0.jar) 
	UCHI	adchimneys{1.11.2-2.0.1.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.1.0.jar) 
	UCHI	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCHI	jei{4.2.3.222} [Just Enough Items] (jei_1.11.2-4.2.3.222.jar) 
	UCHI	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHI	tesla{1.3.0.51} [TESLA] (Tesla-1.11-1.3.0.51.jar) 
	UCHI	thedragonlib{1.11.2-2.1.0} [TheDragonLib] (thedragonlib-1.11.2-2.1.0.jar) 
	UCHI	armorplus{1.11.2-9.4.1.2-beta} [ArmorPlus] (armorplus-1.11.2-9.4.1.2-beta.jar) 
	UCHI	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHI	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHI	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.b64.jar) 
	UCHI	psi{r1.1-44} [Psi] (Psi-r1.1-44.jar) 
	UCHI	quark{r1.2-74} [Quark] (Quark-r1.2-74.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	barkifier{1.1} [Barkifier] (Barkifier MC1.11.2 v1.1.jar) 
	UCHI	bdlib{1.13.1.3} [BD Lib] (bdlib-1.13.1.3-mc1.11.2.jar) 
	UCHI	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UCHI	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.0.233+4d933ac.jar) 
	UCHI	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHI	chiselsandbits{13.9} [Chisels & Bits] (chiselsandbits-13.9.jar) 
	UCHI	forestry{5.3.0.27} [Forestry] (forestry_1.11.2-5.3.0.27.jar) 
	UCHI	eleccore{1.6.381} [ElecCore] (ElecCore-1.11-1.6.381.jar) 
	UCHI	deepresonance{1.4.3} [DeepResonance] (deepresonance-1.1x-1.4.3.jar) 
	UCHI	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHI	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
	UCHI	endertanks{1.5.1} [EnderTanks] (endertanks-1.11.0-1.5.1.jar) 
	UCHI	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCHI	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0b.jar) 
	UCHI	environmentaltech{1.11.2-0.11.0c} [Environmental Tech] (environmentaltech-1.11.2-0.11.0c.jar) 
	UCHI	etlunar{1.11.2-0.11.0b} [ET Lunar] (etlunar-1.11.2-0.11.0b.jar) 
	UCHI	extrabitmanipulation{1.11.2-3.0.0} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.0.jar) 
	UCHI	fastleavedecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.11-1.2.3.jar) 
	UCHI	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
	UCHI	reborncore{2.13.1.25} [RebornCore] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHI	reborncore-mcmultipart{2.13.1.25} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHI	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCHI	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.0-anarchy.jar) 
	UCHI	gendustry{1.6.5.3} [GenDustry] (gendustry-1.6.5.3-mc1.11.2.jar) 
	UCHI	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHI	furniture{1.1.3} [How 'Bout That Furniture] (HowBoutThatFurniture-1.2.1.jar) 
	UCHI	waila{1.8.6} [Waila] (Hwyla-1.8.6-B20_1.11.jar) 
	UCHI	infernalmobs{1.7.2} [Infernal Mobs] (InfernalMobs-1.11.2.jar) 
	UCHI	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
	UCHI	jeibees{0.9.0.3} [JEI Bees] (jeibees-0.9.0.3-mc1.11.2.jar) 
	UCHI	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHI	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHI	jurassicraft{2.0.5} [JurassiCraft] (JurassiCraft-2.0.5.jar) 
	UCHI	levels{b2.1.0} [Levels] (Levels 2-1.11.2-b2.1.0.jar) 
	UCHI	teslacorelib{0.1.0} [Tesla Core Lib] (tesla-core-lib-1.11-0.1.0.jar) 
	UCHI	mekfarm{0.0.1} [MekFarm] (mekfarm-1.11-0.1.0.jar) 
	UCHI	mercurius{1.0.1} [Mercurius] (Mercurius-1.11.2-1.0.2.jar) 
	UCHI	minecolonies{1.11-0.6.2306} [MineColonies] (minecolonies-universal-1.11-0.6.2306.jar) 
	UCHI	mobtotems{1.11.2-0.2.2} [Mob Totems] (mobtotems-1.11.2-0.2.2.jar) 
	UCHI	modularrouters{1.11.2-2.0.1} [Modular Routers] (modular-routers-1.11.2-2.0.1.jar) 
	UCHI	morefuelsmod-1.11.x{1.5.2} [§4More Fuels Mod] (morefuelsmod-1.11.x-1.5.2.jar) 
	UCHI	multistorage{1.3.2} [Multi-Storage] (multistorage-1.11.0-1.3.2.jar) 
	UCHI	mysticalagriculture{1.3.9} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.9.jar) 
	UCHI	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHI	notenoughwands{1.5.3} [Not Enough Wands] (notenoughwands-1.1x-1.5.3.jar) 
	UCHI	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UCHI	packingtape{1.11.0-0.6.1} [Packing Tape] (PackingTape-1.11.0-0.6.1.jar) 
	UCHI	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
	UCHI	platforms{1.3.1} [Platforms] (platforms-1.11.0-1.3.1.jar) 
	UCHI	pressure{1.3.1.3} [Pressure Pipes] (pressure-1.3.1.3-mc1.11.2.jar) 
	UCHI	randomthings{3.7.9} [Random Things] (RandomThings-MC1.11.2-3.7.9.jar) 
	UCHI	reccomplex{1.2.7} [Recurrent Complex] (RecurrentComplex-1.2.7.jar) 
	UCHI	refinedstorage{1.3.5} [Refined Storage] (refinedstorage-1.3.5.jar) 
	UCHE	xreliquary{1.11-1.3.3.612} [Reliquary] (Reliquary-1.11-1.3.3.612.jar) 
	UCHI	rftools{5.82} [RFTools] (rftools-1.1x-5.82.jar) 
	UCHI	rftoolscontrol{1.6.4} [RFTools Control] (rftoolsctrl-1.1x-1.6.4.jar) 
	UCHI	rftoolsdim{4.53} [RFTools Dimensions] (rftoolsdim-1.1x-4.53.jar) 
	UCHI	roguelike{1.6.2} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.2.jar) 
	UCHI	roots{0.007} [Roots 2] (roots-2-0.007.jar) 
	UCHI	simplyconveyors{2.1.0} [Simply Conveyors] (SimplyConveyors-2.1.2.jar) 
	UCHI	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCHI	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCHI	supersoundmuffler{1.0.1.4} [Super Sound Muffler] (supersoundmuffler-1.11.2-1.0.1.4.jar) 
	UCHI	tammodized{0.5.2} [TamModized] (TamModized-1.11.2-0.5.2.jar) 
	UCHI	techreborn{2.1.1.42} [TechReborn] (TechReborn-1.11.2-2.1.1.42-universal.jar) 
	UCHI	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.11-1.1.1a.jar) 
	UCHI	voidcraft{0.13.5} [VoidCraft] (VoidCraft-1.11.2-0.13.5.jar) 
	UCHI	wearablebackpacks{2.0.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.0.0.jar) 
	UCHI	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.7.9.jar)
  lumien.randomthings.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
LoadingPlugin (Quark-r1.2-74.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.1.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.0-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
	List of loaded APIs: 
		* actuallyadditionsapi (32) from ActuallyAdditions-1.11.2-r96.jar
		* ArmorPlusApi (2.0) from armorplus-1.11.2-9.4.1.2-beta.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.11-2.1.0.0.b64.jar
		* Baubles|API (1.4.0.1) from mobtotems-1.11.2-0.2.2.jar
		* BetterAchievements|API (0.4.1.44) from BetterAchievements-1.11.2-0.4.1.44.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.9.jar
		* CoFHAPI (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from FluxedRedstone-2.6.0.54.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.4.jar
		* compatlayer (0.1.7) from compatlayer-1.11.2-0.1.7.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.3.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.6.381.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.6.381.jar
		* environmentaltech-api (1.11.2-0.11.0c) from environmentaltech-1.11.2-0.11.0c.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.0.27.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.0.27.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.3-mc1.11.2.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.3.222.jar
		* mcjtylib_ng (2.3.4) from mcjtylib-1.1x-2.3.4.jar
		* pressureAPI (1.3.1.3) from pressure-1.3.1.3-mc1.11.2.jar
		* PsiAPI (3) from Psi-r1.1-44.jar
		* reborncoreAPI (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Fuel (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Power (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Recipe (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Tile (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* techrebornAPI (2.1.1.42) from TechReborn-1.11.2-2.1.1.42-universal.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0b.jar
		* WailaAPI (1.3) from Hwyla-1.8.6-B20_1.11.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by P3pp3rF1y** [comment]
I have just released a port to 1.11.2. So now you should be able to use Reliquary again.
