### ISSUE TITLE
[Feature] Coin of Fortune toggle

### ISSUE THREAD

**Issue by Discomanco** [P3pp3rF1y/Reliquary#213]
Is it possible to get a keybind/easy way to toggle Coin of Fortune?
At the moment, I have to place the Coin of Fortune in my inventory, as opposed to the Baubles slot, because I need to temporarily turn it off quite often (drop something in full inventory / giving/trading something to a friend) - So I need to take it down to my hotbar, have it as my selected item, Shift-right click it, wait for the drop/trade to happen, turn it on again, put the previous item back in.

So my proposals are either:
Give it a keybind, to toggle Coin of Fortune on/off (maybe None by default)
Ctrl-click it to toggle (Or any other modifier + click in bag/bauble to toggle)
Disabled while sneaking (A minor solution - Botania's Ring of Magnetization does this) - Would prefer a toggle though

**Comment by P3pp3rF1y** [comment]
A keybind with None by default is probably what I end up adding for this as it makes sense to allow people setup a quick way to toggle the coin.
I don't like using shift for it as it means that when you're shifting when breaking blocks over void or high heights you have to unshift often to not let blocks fall down.

**Comment by P3pp3rF1y** [comment]
This has been added in 1.11.2 version that is now on CF.

**Comment by Discomanco** [comment]
Any chance of it coming to 1.10.2?

**Comment by P3pp3rF1y** [comment]
so I was going to say that I will add new features to just the latest, but seeing the number of downloads I have decided to still add this and other new stuff to 1.10.2 as well. I have just released a new version on CF with the keybind.
