### ISSUE TITLE
Pedestal dupe

### ISSUE THREAD

**Issue by dashkal16** [P3pp3rF1y/Reliquary#214]
Steps to reproduce:
1. Place pedestal
2. Right click on pedestal with a stack of anything (tested with saplings and apple juice)
3. Notice only one item was removed from your hand.
4. Sneak-right-click on pedestal.
5. Notice you got back the whole stack.

Tested with an instance containing only:
Minecraft 1.10.2
Forge 1.10.2-12.18.3.2185
Reliquary 1.10.2-1.3.3.620
JEI 1.10.2-3.14.2.401

**Comment by Discomanco** [comment]
Confirmed, with Forge 12.18.3.2221
