### ISSUE TITLE
[1.10.2] Server crash when items pass through a hopper connected to a pedestal with a harvest rod

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/Reliquary#218]
https://gist.github.com/Febilian/07a063f7fc1fa297de79d417da352c20

I'm obviously not very good at figuring out how the automated farm with the harvest rod is supposed to work. Hah.

To clarify: I currently have two pedestals set up, one with an activated coin of fortune, and the other with a harvest rod. I was trying to figure out a way to get carrots to go into the harvest rod automatically since I couldn't find documentation on how to do that(if it's possible at all; just having a chest next to the rod's pedestal didn't do anything), and hoppers came to mind, so I slapped one between the two pedestals, facing towards the harvest rod. The server didn't like that very much, apparently!

**Comment by P3pp3rF1y** [comment]
That is certainly the way it should work and that I was testing before. So something must have changed there that now causes this issue. You should also be able to have coin of fortune insert directly into harvest rod on the pedestal next to it.

**Comment by P3pp3rF1y** [comment]
closing for the same reason as #217
