### ISSUE TITLE
[1.10.2] Apothecary Cauldron does not properly accept glowstone dust

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/Reliquary#220]
See, I can right click the cauldron with the glowstone dust, and when I put in the potion essence, WAILA indicates that there is glowstone in the cauldron as well - but the glowstone in my hand has not had its number of items in the stack reduced, and when I actually bottle the potion, it has no indication that it's any more powerful - as though I had not put any glowstone in at all.

Let me know if you'd like me to do some more testing regarding this and I'll see what I can do; there doesn't seem to be anything regarding Reliquary in my log.

EDIT: Perhaps I should mention I'm attempting to make an instant health potion with nothing else on it, its base level is as low as it can get(no II or III or what have you on it). Hence the desire to use glowstone to make it more powerful.

**Comment by Not-February** [comment]
Er, never mind. Apparently I just didn't know how to use the cauldron; after logging back into the world, I'm able to put glowstone in AFTER the potion essence, and it seems to update the cauldron's contents.

I'm leaving this open because it is still a bit confusing that WAILA integration updates with information that isn't valid before the glowstone dust can be accepted.

**Comment by P3pp3rF1y** [comment]
The latest version on CF now has the fix that doesn't allow player to put in anything before essence is inserted.
