### ISSUE TITLE
Incorrect name on item pedestals

### ISSUE THREAD

**Issue by TheDeviantCrafter** [P3pp3rF1y/Reliquary#223]
The item pedestal block has a name that I have to assume is meant to be the tooltip, not the item's name.

They are named "Used as a fancy way to display items." This can be seen in the box that appears when you hover your mouse over an item, in the action bar, and when looking at the block with The One Probe.

[Screenshot](https://i.gyazo.com/1820bd4d13d9dd31b22b9ccfc8d9ea1d.png)

**Comment by TheDeviantCrafter** [comment]
Minecraft version: 1.10.2

Mod version: 1.3.3.639

Forge version: 12.18.3.2254

**Comment by P3pp3rF1y** [comment]
This is now fixed int he latest version available on CF.
