### ISSUE TITLE
Null Pointer exception when using Tome of Alkahestry[1.10]

### ISSUE THREAD

**Issue by Divineaspect** [P3pp3rF1y/Reliquary#225]
https://gist.github.com/Divineaspect/c9a8be2c514c3a8ac534abc56d368f94

This is when, on a server, clicking with the tome of alkahestry
It also isn't absorbing redstone even when so activated.

**Comment by P3pp3rF1y** [comment]
This looks like a wrong configuration in config file. It fails on displaying the item that tome absorbs and uses for duplication of items. By default that's redstone, but it looks to have been overriden.
What is the base_item setting set to in config?

**Comment by Divineaspect** [comment]
https://github.com/belathus/Wanderlust-Renewed/blob/master/config/xreliquary.cfg

So apparently railcraft:ore_magic but we removed railcraft so that'd be throwing a null.
Thank you!
