### ISSUE TITLE
Server crash when in the Nether and (un)equipping the Zombie Pigman charm

### ISSUE THREAD

**Issue by GrokDuckFarmer** [P3pp3rF1y/Reliquary#226]
I crashed the server twice today with angry zombie pigmen in the nether.  The first was after hitting a pigman and then placing the belt with the pigman charm into a bag.  The second when I retrieved that charm and angry pigmen were still about.

https://pastebin.com/W9pkYe0T

**Comment by P3pp3rF1y** [comment]
This is now fixed in the latest version available on CF.
