### ISSUE TITLE
Dummies from MmmMmmMmm and Holy Granades thrown at them crashes the game

### ISSUE THREAD

**Issue by Ristellise** [P3pp3rF1y/Reliquary#231]
Reproduction steps :
1. install Relavent mods
2. Thow hand granades on Dummies... and crash.
[crash-2017-04-19_20.39.12-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/934477/crash-2017-04-19_20.39.12-client.txt)

**Comment by P3pp3rF1y** [comment]
Looks like a combination of incorrect damage type dealt and missing player value caused this. Should be fixed in the next release

**Comment by P3pp3rF1y** [comment]
I have just released a new version on CF with the fix
