### ISSUE TITLE
Holy Hand Grenade throws exceptions when exploding

### ISSUE THREAD

**Issue by CovertJaguar** [P3pp3rF1y/Reliquary#232]
https://cdn.discordapp.com/attachments/296841693460692994/304234770517458944/crash-2017-04-19_20.39.12-client.txt

**Comment by P3pp3rF1y** [comment]
This is a duplicate of #231, I have a fix for it just need to release it.

**Comment by P3pp3rF1y** [comment]
I have just released a new version on CF with the fix
