### ISSUE TITLE
Help with stat.useItem.xreliquary.glacial_staff

### ISSUE THREAD

**Issue by JotCGit** [P3pp3rF1y/Reliquary#234]
Hello,

I'm quite new to the minecraft modding community and to the minecraft vanilla commands. However, I've recently been working on a Forge server that uses kits/classes for PvP. Through tireless research and assistance from those that are much more adept than me, I've finally started finalizing all the backbones of my server through command blocks and, allowing me to get to the fun stuff.

Most recently, I've developed a means of adding 'cooldowns' to certain items in each of my PvP kits. However, upon trying to use these same set of commands via command blocks for a reliquary item, it doesn't seem to do anything. I'm am 99% positive that the commands SHOULD work as I have been successful in using them with 3 other kits. Here are the commands:

/scoreboard players set @a[score_snowballCD_min=1,tag=isMage] snowballCDDummy 20

/replaceitem entity @a[score_snowballCD_min=1,tag=isMage] slot.hotbar.1 minecraft:dye 1 8 {noDrop:1b,display:{Name:"Item on Cooldown"}}

/scoreboard players set @a[score_snowballCD_min=1,tag=isMage] snowballCD 0

/scoreboard players remove @a[score_snowballCDDummy_min=1] snowballCDDummy 1

/replaceitem entity @a[score_snowballCDDummy_min=1,score_snowballCDDummy=1] slot.hotbar.1 xreliquary:glacial_staff 1 0 {noDrop:1b,BlockLocations:[],snowballs:1,enabled:0b}

When I use the glacial staff, it consumes the 1 snowball in its charge instead of following the commands.

**Comment by P3pp3rF1y** [comment]
Sorry, but I have never worked with these commands so I can't really help. But the stuff doesn't do anything extra, just on right click it uses a snowball in its charge. The only thought I have is that the NBT of the staff is different than the one that you're expecting. Also if people use this to freeze water/lava the BlockLocations tag will have locations of frozen blocks so it's likely to not work for you in that case as NBT will be different (well unless I completely misunderstand what the command is doing there)

**Comment by P3pp3rF1y** [comment]
closing
