### ISSUE TITLE
NPE: ticking entity

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/Reliquary#237]
reliquary version: 1.3.3.639
so... I found out what happens (or at least can happen) when you (by removing and replacing the item) disable and reenable a zombie pigman charm when pigmen are angry:  you get a null pointer exception! Congratulations! You win! Seriously though, please fix this if you haven't already.
[crash-2017-05-19_21.16.44-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1015806/crash-2017-05-19_21.16.44-server.txt)

**Comment by P3pp3rF1y** [comment]
This is resolved in build 649 that was released more than a month ago so you just need to update to more recent version.

**Comment by Twisted-Code** [comment]
oh ok. Sorry to trouble you. I should probably update my mods more frequently, eh? Yeah.... the joys of being a custom pack server owner...
