### ISSUE TITLE
Possible Bug: Pedestal with bucket not working with IE metal barrel

### ISSUE THREAD

**Issue by Kaisoul** [P3pp3rF1y/Reliquary#239]
forge-1.10.2-12.18.3.2297
minecraft 1.10.2
ImmersiveEngineering-0.10-58
Reliquary-1.10.2-1.3.3.664

Made a pedestal added a bucket to it and hit the button to turn it on..
had a Metal Barrel from Immersive Engineering near the pedestal and nothing no fluid being moved at all.
Was trying to move a pool of lava.

If you have any idea's or help as to what's going wrong that would be great.

**Comment by P3pp3rF1y** [comment]
It does work with it but for whatever reason the IE barrel is coded so that the block that wants to insert fluid into it must be on the Y axis - that is above or below it. With that configuration I have just confirmed that it works.
