### ISSUE TITLE
the Rending Gale isn't working for me. Am I doing something wrong?

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/Reliquary#243]
I made sure to "empower" the item (shift right clicking so the item glows) but regardless of whether it's empowered or not, I can't seem to fly. Isn't it just supposed to be point-and-rightclick?
usage context is a Forge server with SpongeForge, 3 plugins, and several other mods installed

**Comment by P3pp3rF1y** [comment]
It definitely should work that way and did the last time I checked. 
Have you charged it with feathers?

**Comment by Twisted-Code** [comment]
Yeah I was just about to say: I took another look and noticed the feather fuel count. The information displayed by JEI didn't say anything about feathers, but your overlay is thankfully intuitive :-)

**Comment by Twisted-Code** [comment]
...if a little ambiguous

**Comment by Twisted-Code** [comment]
@P3pp3rF1y You can close this, though before you do you should probably add a mention of the fuel cost to the JEI info tab.

**Comment by P3pp3rF1y** [comment]
yup, will keep this open for now and add something in there so that it's clear

**Comment by Twisted-Code** [comment]
okey-doke. Sounds good 😃

**Comment by Twisted-Code** [comment]
Gee, if only there was a way to hold several stacks of feathers in one slot in my inventory 😜
