### ISSUE TITLE
kicked for flying using the Rending Gale

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/Reliquary#244]
Not much to say here other than list my versions
Minecraft: 1.10
Forge: 2185
SPONGEFORGE: spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar
Reliquary: 1.3.3.664

please give me a heads up when this is fixed (ideally by closing the issue and citing the commit with which it is resolved, as is good practice anyway), because I'd like to switch my server.properties' "allow-flight" back to false once it stops kicking me for no good reason

**Comment by P3pp3rF1y** [comment]
This is something i have fixed previously and don't think I have broken that so I am suspecting some difference with Sponge here. 
Is it kicking you like every time that you fly for a bit longer?

**Comment by Twisted-Code** [comment]
it's kicking me every time I fly for more than about 3 seconds. technically though, every time = 1, as I switched  the variable in server.properties after the first encounter of the issue

**Comment by P3pp3rF1y** [comment]
So I was testing this quite a bit today and can't recreate. I am guessing it may be sponge causing something here, but i am reluctant to start debugging the differences between forge and sponge server.

**Comment by P3pp3rF1y** [comment]
Also let me know if this is still happening to you and perhaps if you can possibly retest with a similar way of flight like Elytra to see if it has issue with sponge as well

**Comment by Twisted-Code** [comment]
@P3pp3rF1y okay, will let you know. I started a new world though, and haven't managed to obtain a   Rending Gale yet.
Interestingly enough, one of the things I'm missing is the slime pearl in the recipe. You would think slimes would be easy to farm, but farming them entails finding a slime chunk. That's okay though, I have a workaround and it involves a certain tech mod

**Comment by P3pp3rF1y** [comment]
So I have found code that was wrong related to checking if the player can fly. Based on what it was doing it actually would allow players flying in cases where they didn't have any charge, but maybe in some cases the calculation turned out denying flight to players who had enough charge. Anyway I have fixed it and will include in the next 1.12 release.

**Comment by P3pp3rF1y** [comment]
Closing this, if you will run into this issue again feel free to open a new issue for that.
