### ISSUE TITLE
NPE entityNeutralShot

### ISSUE THREAD

**Issue by phit** [P3pp3rF1y/Reliquary#245]
Reliquary-1.11.2-1.3.3.653

https://gist.github.com/phit/df2100ae667079868d9831362318095f

be advised server is running Sponge, but I'm not sure if its relevant for this

**Comment by P3pp3rF1y** [comment]
Does this happen every time you try to shoot an animal?

**Comment by phit** [comment]
no, I can't even reproduce it locally right now with just Reliquary and Sponge :/
not sure what exactly happened, I'll ask the person involved with the crash what they did exactly

**Comment by P3pp3rF1y** [comment]
It may be the animal shot. Basically it crashed when it tried to get a death message and something in there wasn't right. So perhaps just naming a mob will help?

**Comment by phit** [comment]
Mh, nametag doesn't change anything, they had apparently used the gun before quite a bit before this without issue, so no idea what happened.

Would it be possible to add a nullcheck with a warning, so it at least doesn't happen again? This put my server in a crash loop until I removed the shot entity in MCEdit, otherwise I probably wouldn't have noticed it.

**Comment by P3pp3rF1y** [comment]
That's not really possible because the issue happens so deep in the mc code and I am still not convinced it's actually the shot that caused it even though you're saying removing entity helped. But the method where it crashed is mostly actually working with the entity that was killed.

**Comment by phit** [comment]
I got [17](https://gist.github.com/phit/fe1f14be6deed777610fe1d7be09faca) of the exact crashes from people loading the area with the shot, so it was definitely the shot since it was fixed when I removed it and nothing else. It's fine if you can't add a nullcheck, maybe this was just a one in a million odd thing. Since I'm not able to reproduce it myself either I'll close it for now. I'll update if I can figure out a reproduction.
