### ISSUE TITLE
Pedestals Destroying All Swords Put On

### ISSUE THREAD

**Issue by BigFriendlyJakey** [P3pp3rF1y/Reliquary#250]
Not sure if it's something I'm doing, but every time I put a sword (can be TiC, Botania, or Vanilla) on a pedestal, it gets deleted, not put in any chests or anything (I thought sword-being-put-in-the-chest would be the case since every time it happens in my survival world, there's usually some sort of magnet-type block nearby. Unfortunately, the sword isn't put in the inventory the magnet-type block is meant to put it in, whether it be the hopper plant from Botania or the Coin of Fortune in another pedestal). Can reproduce in survival world in all different circumstances, but in any other world (whether it be in creative or survival), I cannot reproduce the same outcome. Any help would be appreciated, because I've lost a lot of good TiC Cleavers already :(

**Comment by P3pp3rF1y** [comment]
Are you saying that you simply put a sword in the pedestal and it immediately disappears? Or that it happens after some time it was killing mobs? 
Also which version is that and what pack?

**Comment by BigFriendlyJakey** [comment]
I put a sword in and it immediately disappears (I think the Coin of Fortune is mistaking it for a dropped item and trying to pick it up, but destroying it instead... I don't know, coding ain't my jam).

I'm using Forge version 1.11.2-13.20.1.2388 & Reliquary version 1.11.2-1.3.4.678

**Comment by P3pp3rF1y** [comment]
So I am really not sure what's happening for you there. I have tried many different things and can't recreate that. Also coin of fortune can't pickup the sword from pedestal because it is only rendered at that point and doesn't exist as an entity in world which is the only thing coin of fortune can pickup.
Are you by any chance running pipes/hoppers by the pedestal? It works as an inventory that can be interacted with using these so maybe that's what's happening.

**Comment by P3pp3rF1y** [comment]
Closing as it works for me and there was no response after the question about pipes

**Comment by zirrboy** [comment]
This is 3 years late, and most Modders don't like redoing older versions, but here are my finding on the bug:
Mod Version (mine): 1.12.2-1.3.4.796

Steps to reproduce:
-have one pedestal actively do something (for example one with a Harvest Rod planting crops)
-activate another that has a weapon on it

-> after a few hits, the weapon will disappear
