### ISSUE TITLE
Issue with slime pearls?

### ISSUE THREAD

**Issue by Teslachu** [P3pp3rF1y/Reliquary#252]
So I have killed a ton of purple slimes, blue slimes, and even magma slimes... I am currently in a "garden of glass" map. The mod pack is "Project ozone lite". Now I do not know if this is an issue or not, but I have been trying for days (going from various slime islands in the over world, mining dimension, and the nether, along with hitting up nether fortresses). I have yet to get a single slime pearl, with a tinker's sword that has max looting. I even got a sword out of a quest reward chest that has a looting enchantment level of 69 and tried to use that - still no slime pearls. The sword was called Epeolatry and it is from the Avarita mod (avaritia:skullfire_sword). So I guess my question is if this is working as intended, (which JEI says the slime pearl drops off magma cubes), or if something is wrong here? I did not know if I should report this to you or that mod pack creator. I figured I would start here, since it is your mod and then go over there, if everything is working as it should be.

Now I should note that I did go into creative mode to spawn in some vanilla slimes, and after like 3 I did get slime pearls. However, I have yet to find any normal slimes as I am in a garden of glass over world (basically void) and the mining dimension does not really have biomes. So ya :/

Thank you for any insight that you might be able to provide.

(EDIT: Additional info I forgot to include~ Minecraft version 1.10.2 ~ the version of Reliquary currently being used in the pack is 1.10.2-1.3.3.664)

**Comment by P3pp3rF1y** [comment]
Does it really show that magma cubes drop slime pearls? they are not supposed, only vanilla slimes are supposed to drop slime pearls and magma cubes should only drop molten cores.
I guess you will have to find a slime chunk and kill some slimes there.

**Comment by Teslachu** [comment]
Yes, it does show it that way in JEI. It is odd that it says that, but that it didn't do that. Like I said, I did some testing and saw them only drop from vanilla slimes. I did eventually find a slime chunk and got some, but that took a while. ^^ Thank you for such a quick response. I am including a cropped screen shot of JEI information, on the slime pearl, for you.

[http://i.imgur.com/G64uoWK.png](http://i.imgur.com/G64uoWK.png)


I hope this helps a little. Thank you again for such a quick response.

**Comment by P3pp3rF1y** [comment]
Ohh, my bad, I didn't realize that you mean the JEI description for the slime pearl (thought you're referring to the JER's view of the mob drops).
That's a relic from the point in time when they did drop from magma cubes, but later I found out they were not supposed to and removed the drop, however apparently didn't update the description. 
I will keep this open so that I fix the description to only include vanilla slimes.
