### ISSUE TITLE
Disabling items and blocks, can't get it to work.

### ISSUE THREAD

**Issue by altech6983** [P3pp3rF1y/Reliquary#253]
I am playing Skyfactory 3, 1.10.2. I have added reliquary 1.3.3.664 to the pack and everything was working. I am trying to say as close to skyfactory as I can but wanted to automate dragon's breath and I need the interdiction torch to keep the blocks safe.

I am trying to disable all other items and blocks except for the torch and the items to build it. I have tried several different ways in the config file, some end in "Reliquary failed to initiate recipes." crashes, others load but don't seem to actually disable the items.

S:disabled_items_blocks <
	handgun,
	bullet
>

S:disabled_items_blocks <
	"handgun",
	"bullet"
>

etc.

What is the proper way to do this?

**Comment by P3pp3rF1y** [comment]
The first example that you have there just without the commas. That's how string lists work in forge's configuration files. But you are likely to run into issues if you're disabling everything - I have never tested that and I am pretty sure there are some cases where I don't check for item/block existence before doing some stuff.
The better way would be to disable all recipes using something like crafttweaker. In 1.12 I have removed the ability to disable stuff altogether and crafttweaker is the only way to ban players from using the items legit.

**Comment by altech6983** [comment]
Sweet, thanks. I will do that.
