### ISSUE TITLE
[Bug/Question] Emperor's Chalice

### ISSUE THREAD

**Issue by Timeslice42** [P3pp3rF1y/Reliquary#258]
Version: 1.12-1.3.4.710
I'm unable to drink from this to fill hunger, whether it is activated or not. Is there a config setting for this functionality that I'm missing?

**Comment by P3pp3rF1y** [comment]
Apparently I have removed triggering the drinking by mistake as part of 1.11 port. I have it readded in dev.

**Comment by P3pp3rF1y** [comment]
this fix was released some time ago so closing the issue here.
