### ISSUE TITLE
Adding custom potion ingredients

### ISSUE THREAD

**Issue by Alan19** [P3pp3rF1y/Reliquary#260]
Is it possible to add custom potion ingredients and have them use potion effects from other mods?

**Comment by P3pp3rF1y** [comment]
Check potion_map part of the config, that's where all potion ingredients are defined and you can add more in there. Based on what I can see it should be possible to add potion effects from other mods as well, but I haven't tested that so be prepared for potential crashes. 
If you run into any let me know.

**Comment by Alan19** [comment]
Can you provide some examples on how to add potion effects from other mods? I've used extraalchemy:dislocation but that doesn't seem to work.
