### ISSUE TITLE
Exception Caught error

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#261]
I played my pack for over 3 days without a problem, and today it suddenly refuses to load ([see log](https://paste.ee/p/qQrEx)). I did not change anything (no updates, additions, etc. last change was Saturday to newer forge) so it is very strange.

MC 1.12.2
Forge 2515
Reliq 1.3.4.719

EDIT: I remember Windows updating to the fall creators update last night... couldn't be it, could it?

**Comment by P3pp3rF1y** [comment]
This looks like reliquary file got corrupted as the class it's looking for is there and it should have no issues finding it. Can you try downloading the mod again and see if that helps?

**Comment by ghost** [comment]
No, that didn't help. I did find something else though.
First I tried disabling all other mods one by one, that didn't help either, then I made a new instance with just Reliquary, that worked fine. So I added all other mods one by one again. And it still worked fine. However, I had Botania installed previously (it was disabled in the 'original' pack). So after adding it and then disabling it again, the problem resurfaced. So somehow first enabling Botania, and then disabling it causes this? Does that make sense?

EDIT: that still does not explain why it worked for the past 3 days though...hmm I think I'll just remake the pack and copy over my saves.

**Comment by ghost** [comment]
Ohhh.... found it!

I had Baubles in a subdirectory ('1.12.2') it seems your mod doesn't like that. I placed it directly in the 'mods' folder and now it works again. Still strange why it also did yesterday since I don't think I changed anything, but perhaps I did... I'm getting old.
