### ISSUE TITLE
[1.12.2] Magazine recipes do not work

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#262]
I didn't test all types, but e.g. seeker shots cannot be crafted into a magazine. Surrounding an empty magazine with bullets gives me back an empty magazine.

**Comment by P3pp3rF1y** [comment]
What version have you tested this with? 
Is it in a modpack? 

I have tried testing this in dev, that is with the same code as 1.12.2-1.3.4.719 and I can see the recipes working correctly.

**Comment by ghost** [comment]
I made a fresh instance and tested with just reliquary; and you are right, it works there so it must be a mod conflict. I'll see if I can find which one. I'll close this for now.
