### ISSUE TITLE
Wiki needs detail on the infernal tear

### ISSUE THREAD

**Issue by aahaselgrove** [P3pp3rF1y/Reliquary#264]
As in the title. A table would be good. A quick look at the code suggests that the items it accepts are related to the tome of alkahest, so maybe copy/modify that table?

**Comment by P3pp3rF1y** [comment]
How about a new JEI page that will show levels (or partial levels) that you receive by burning the items. That way even if someone changes configs for these it's going to show the appropriate items and related levels.

**Comment by P3pp3rF1y** [comment]
added JEI integration for infernal tear in the latest release for 1.16.5
