### ISSUE TITLE
Interdiction Torch Only Seems To Work Reliably on Vanilla Mobs

### ISSUE THREAD

**Issue by Boolyman** [P3pp3rF1y/Reliquary#269]
Lycanite Mobs seem to not be effected at all.  And in my last pack, Grimoire of Gaia mobs didn't seem to be effected.  Anyway you can either include them by default, or have the option to add repelled mobs in the config file?

**Comment by P3pp3rF1y** [comment]
So, I am not sure which version you're referring to as this actually differs between versions. 

In 1.10 and before this used to be a whitelist that can be defined in config under "entities_that_can_be_pushed". These were automatically filled in with all entities the first time that config section was generated, if mods were added later their entities didn't get added to the whitelist. The easiest way to get them there is just delete the section and it will just put every single entity in there.

From 1.11.2 this is actually changed to a blacklist "pushable_entities_blacklist" in config. If empty it just pushes every single entity.

**Comment by P3pp3rF1y** [comment]
Has this worked for you?

**Comment by P3pp3rF1y** [comment]
I am going to assume that it worked and close this issue. Feel free to ping me in case you have more questions.
