### ISSUE TITLE
Config keeps on resetting

### ISSUE THREAD

**Issue by Alan19** [P3pp3rF1y/Reliquary#270]
The config file seems to be resetting whenever I open Minecraft, making it impossible to modify the potion recipes. It's resetting even if there's no changes.

**Comment by P3pp3rF1y** [comment]
Looks like I made a bad choice of type to use to store potion map settings. It basically didn't allow any changes to the list of potion ingredient items, only to the effects. 
I have changed that now and will be releasing a build in the next days. However if you want to test this out you can also use a dev build from https://bintray.com/p3pp3rf1y/maven/download_file?file_path=Reliquary-1.12.2-1.3.4.725unstable.jar

**Comment by Alan19** [comment]
The config is still resetting after reloading

**Comment by Alan19** [comment]
It looks like the configs didn't reset but Notepad++ is saying it did

**Comment by Alan19** [comment]
It seems to work now but I'll do some more testing with custom potion effects

**Comment by Alan19** [comment]
I've been getting crashes with Extra Alchemy potions

**Comment by P3pp3rF1y** [comment]
Any crash logs you could share?

**Comment by Alan19** [comment]
The crashes were caused by incorrect potion names. Everything works now but I can't see any potion essences when I search for them in JEI. I have it so that it displays all combinations when looking at ingredient uses.

**Comment by P3pp3rF1y** [comment]
Could you link your config so that I can take a look/test with it?

**Comment by Alan19** [comment]
https://github.com/belathus/Wanderlust-Renewed/blob/master/config/xreliquary.cfg

**Comment by P3pp3rF1y** [comment]
so the ingredients load properly, but what you're hitting here is a setting in JEI that will stop displaying all subtypes of an item if the count of those is greater than a value, by default 500;
Search for I:maxSubtypes in jei config and set that to (much) higher value to see these.

**Comment by P3pp3rF1y** [comment]
btw, I have released the version with corrected loading of potion map from config and have tested your config with that version and could see the potions there
