### ISSUE TITLE
On Certain Worlds: Revolvers do not fire at all!

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#271]
Hiya, idk why this is happening, but I was setting up a build a pvp arena event thing. It was working fine until i tried to fire a revolver into one of the worlds....

It doesn't seem to want to fire for whatever reason? This happens with all revolvers, regardless of level.

Other worlds it works fine in, but for some worlds it doesn't work at all?

I'm not certain why this is happening to be honest. I tried replicating, but on some worlds it works fine, others it doesn't. Its so strange.

**Comment by Akitori** [comment]
update: its caused by doDaylightCycle being set to false. WHY?

**Comment by P3pp3rF1y** [comment]
the reload time on gun is controlled by time that stops running when doDaylightCycle is false. But apparently there's another "total time" which keeps running so I have changed to using that and that fixes this issue. Will have a release of Reliquary with the fix soon.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
