### ISSUE TITLE
Pedestals consume items if broken

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#272]
How to repeat problems.
Get any pedestal (display or automated, doesn't matter)
Put item in. 
Break pedestal. 
Poof your item is gone.

Why doesn't the pedestal drop its inventory? can this be fixed asap?

**Comment by P3pp3rF1y** [comment]
You know that deadlines is the one thing you should never ask mod developers about? 

Anyway looks like the code that spawns itemstacks in the world was borked. I have it fixed in dev and will release soon.

**Comment by Akitori** [comment]
Wow that seemed arrogant of me. The only reason i asked asap is cause I know some of the users on my modpack will break the pedestal and lose the items, i don't mean to rush you. Apologies.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
