### ISSUE TITLE
Rod of Lyssa doesn't work on players?

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#273]
Hey so I've been testing this rod on my server, with help from a friend. I can never seem to get a item off them though, why is that? Is that intentional/a bug?

**Comment by P3pp3rF1y** [comment]
The way it is coded currently it cannot. I will leave this open for a bit of time to think through whether I want this changed so that it can steal from players as well. 
I am leaning to adding that.
