### ISSUE TITLE
Crash when using Flight with Rending Gale.

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#274]
Two separate crashes point the stick as the problem.

[crash-2017-12-10_15.22.55-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1546041/crash-2017-12-10_15.22.55-server.txt)

[crash-2017-12-10_13.28.41-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1546042/crash-2017-12-10_13.28.41-server.txt)

**Comment by P3pp3rF1y** [comment]
I have no idea what's happening there for you. The most I can make out of those crash logs is that for some reason something else is blocking block registry which prevents rending gale code from getting snow layer block state id that it needs for its particles. 

Are you able to recreate this consistently? And is it on dedicated server or single player?

**Comment by Akitori** [comment]
Sort of. It always involves someone using the reliquary rending gale. It's always caused by using the flight option, and it either times out the server or straight up crashes it.

**Comment by Akitori** [comment]
Issue is constantly multiplayer

**Comment by Akitori** [comment]
Wait why is the server calling for particles? wouldn't that be used/needed client side only?

**Comment by P3pp3rF1y** [comment]
The server spawns the particles so that other players can see those and then the clients actually render those for players.

Anyway, I have just retested on a dedicated server and I am unable to recreate. So I still suspect that there's some mod interaction going on that causes this. 
Are you actually able to recreate with just Reliquary?

**Comment by Akitori** [comment]
I've actually been testing extensively on the pack as we released a big update as of late (removing a few mods we never used) and the crashes haven't....occurred since then. 

I've tested a bunch of scenarios users stated caused it, but...Nothing! Not a crash to be found.

If it comes up again I'll at least be certain its mod based. 

Odd though. The only mod we removed was a library mod and some automated redstone mechanics.

**Comment by oddstr13** [comment]
Getting simmilar crash on my modpack.
Planning on doing a full pack update later today, so I'll report back if the crash happens again.

These are server-side crashes.

[crash-2017-11-30_14.51.08-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565044/crash-2017-11-30_14.51.08-server.txt)
[crash-2017-11-30_15.03.02-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565045/crash-2017-11-30_15.03.02-server.txt)
[crash-2017-12-13_15.46.43-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565046/crash-2017-12-13_15.46.43-server.txt)
[crash-2017-12-16_19.01.58-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565047/crash-2017-12-16_19.01.58-server.txt)

**Comment by P3pp3rF1y** [comment]
All I can make of this is that some mod is causing threading issues and Reliquary just gets in the middle of that with a simple get object from registry call. If you can figure out which mod is causing that I can take a look if there's a way to prevent this from happening but it is pretty unlikely there is a way on Reliquary side.

**Comment by Akitori** [comment]
[crash-2017-12-16_17.03.28-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565126/crash-2017-12-16_17.03.28-server.txt)
[crash-2017-12-13_15.44.08-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/1565127/crash-2017-12-13_15.44.08-server.txt)

2 new crashes. No idea what's causing it tbh but I'll send a modlist. Maybe if me and the other dude find what mods we have in common, we can determine the cause.

Also the issue is that its so damn inconsistent. I can't reproduce it on my own, but another one of my users constantly causes the server to crash with it.

Mods in common:
thermalfoundation and cofh addons, bibliocraft, codechickenlib, harvest craft. I'll be testing more and more on server to see if i can duplicate the cause. I have a sinking feeling it might be bibliocraft though.

**Comment by oddstr13** [comment]
Mods in common (none of which are coremods):
 * bibliocraft
 * codechickenlib
 * redstoneflux
 * cofhcore
 * cofhworld
 * jei
 * harvestcraft
 * thermalfoundation
 * thermalexpansion
 * xreliquary
 * thermaldynamics


For reference, this is the line at which the stacktrace leaves Reliquary; [ItemRendingGale.java#L383](https://github.com/P3pp3rF1y/Reliquary/blob/1.12.x/src/main/java/xreliquary/items/ItemRendingGale.java#L383)
Which also seems to be the last line that is consistent between the crashes.

**Comment by Gamerbolts** [comment]
Hello I also am getting this crash on my server. I have a modpack I created for my friends community and people using the rending gale keep timing out or crashing the server.

Here are my crash logs
https://pastebin.com/zDSWQxhH
https://pastebin.com/GuJr22Ga

Mods in common with OP
Bibliocraft
CodeChickenLib
RedstoneFlux
CofhCore
CofhWorld
JEI
ShetiphianCore
MultiStorage
Reliquary
Telepads
Thermal Mods (Expansion, Foundation, Dynamics)

Hope a fix or workaround can be found for this, my users love the rending gale

**Comment by P3pp3rF1y** [comment]
I have released a new version of Reliquary where I am using SNOW block as a source of particle look, which could possibly solve this issue for you, let me know if you're still seeing it.

**Comment by P3pp3rF1y** [comment]
Closing, feel free to open a new issue if you see the crash again
