### ISSUE TITLE
rending gale crashing minecraft while in flight mode

### ISSUE THREAD

**Issue by JBSTheGamer** [P3pp3rF1y/Reliquary#277]
I do not have a crash log. Minecraft version is 1.12.2. Forge version is 1.12.2-forge1.12.2-23.1.2566.
Every time i fly with rending gale it crashes my game. I have reproduced the bug 8 times. Every time is crash. If you have any info please let me know.

**Comment by P3pp3rF1y** [comment]
This is likely same issue as #274, but I will need more than this. If you have a crash log please attach it. 
Are you playing a modpack?
Have you tried recreating with just Reliquary?
Is this Single or Multiplayer?

**Comment by JBSTheGamer** [comment]
I have no crash log. I am not playing a modpack. I will try to recreate with just reliquary. This is singleplayer that im playing on. What it dose is, it says on the one probe tool tip "waiting for server" after trying to use the flight mode. But it dose not crash it supposed to but dose not. When i click save to title though it crashes. After it crashes it dose not give me a crash log. If this happens with just reliquary then its something in your mod that making it crash. I will let you know what will happen.

**Comment by JBSTheGamer** [comment]
I have just tested it in singleplay and multiplayer with this mod. It still crashes my game. I have also tested it with just reliquary in singleplay and multiplayer and its still crashing. Still could not get a crash log cause it did not give me one. So its just your mod thats making it crash when in flight mode with the rending gale.

**Comment by JBSTheGamer** [comment]
I tested it again with the version before the latest version for 1.12.2 reliquary. The game did not crash with that version. But the latest version will crash the game.

**Comment by JBSTheGamer** [comment]
It actually dose still crash my game. Im closing this issue for now. It also still crashes even with the mod alone.

**Comment by P3pp3rF1y** [comment]
I have released a new version of Reliquary where I am using SNOW block as a source of particle look, which could possibly solve this issue for you, let me know if you're still seeing it.

**Comment by P3pp3rF1y** [comment]
Resolving, if you get this crash again feel free to open a new issue
