### ISSUE TITLE
Charm Belt Dupe Bug

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#278]
Version: 1.12.2-1.3.4.728

If you stack two (or more) Charm Belts, you can then put any mob charm inside. When If you then split the stack, you can take the charm out of both new stacks, thus duplicating the charm. Presumably the charm belt shouldn't be stackable?

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. So yeah, I never meant for charm belt to be stackable so I will fix that and that will take care of dupe issue.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest build released on curseforge.
