### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by Soloist1twitch** [P3pp3rF1y/Reliquary#280]
There are 3 recipes in JEI for using 3 Witches Hats in a top to bottom column.  One produces gunpowder, one produces redstone, and the last produces glowstone.  The last one seems to only give gunpowder.  The first two work as intended.

Minecraft version: 1.12.2
Forge version: 14.23.1.2581
Reliquary version: 1.12.2 1.3.4.725

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest build just released on curseforge
