### ISSUE TITLE
[Suggestion] Be able to fill the vanilla cauldron with the Emperor's chalice.

### ISSUE THREAD

**Issue by Charles-Thacher** [P3pp3rF1y/Reliquary#283]
Basically what it says on the tin:
I can't fill the cauldron with the Emperor's Chalice.
I want to fill the cauldron with the Emperor's Chalice.
Can I please be able to fill the cauldron with the Emperor's Chalice?

**Comment by P3pp3rF1y** [comment]
This has been implemented in the latest build just released on curseforge.
