### ISSUE TITLE
[1.12.2] Crash with EndermanEvolution

### ISSUE THREAD

**Issue by p455w0rd** [P3pp3rF1y/Reliquary#284]
The log is here: https://pastebin.com/CZhyXbqy
This is due to assuming that the EntityPlayer param being passed in is always going to be server side.
Simple fix is to do a check to ensure EntityPlayer is an instance of EntityPlayerMP in https://github.com/P3pp3rF1y/Reliquary/blob/1.12.x/src/main/java/xreliquary/items/ItemMobCharm.java#L274

**Comment by P3pp3rF1y** [comment]
I could add that check, but I wonder why you need to call onDeath on entity client side when that seems like something that should only be called server side. 
And actually checking the logic similar to what you have there in vanilla it seems like you are missing isRemote check and follow up return false perhaps this is what it was supposed to be https://github.com/p455w0rd/EndermanEvolution/blob/master/src/main/java/p455w0rd/endermanevo/entity/EntityEvolvedEnderman.java#L147-L149

**Comment by P3pp3rF1y** [comment]
I have seen that you have made a change on your side so I am guessing this is no longer an issue and closing here.
