### ISSUE TITLE
Reliquary causing server to crash?

### ISSUE THREAD

**Issue by deceptaboss** [P3pp3rF1y/Reliquary#288]
[2018-01-31-1_1.log](https://github.com/P3pp3rF1y/Reliquary/files/1691312/2018-01-31-1_1.log)

version 1.12.2

**Comment by P3pp3rF1y** [comment]
Why do you think it's Reliquary causing the crash? Seems like something bigger than a single mod causing that

**Comment by P3pp3rF1y** [comment]
Also can you post logs/fml-{client/server}-latest.log that should hopefully have more info on what's happening

**Comment by deceptaboss** [comment]
I posted it in the technic discord and a bot told me reliquary was the issue. We tried removing it and it still crashed. 
[2018-01-31-1_1.log](https://github.com/P3pp3rF1y/Reliquary/files/1692044/2018-01-31-1_1.log)

**Comment by P3pp3rF1y** [comment]
So if removing Reliquary still doesn't stop this crash from happening I don't know why Reliquary would be the one to blame. Anyway, I can try to point you in the correct direction, but for that I would need the logs/fml-{client/server}-latest.log from when this happened, I believe that what you have posted above is just the log from crash_reports.

**Comment by deceptaboss** [comment]
How would I get that file?

**Comment by P3pp3rF1y** [comment]
there is supposed to be a logs folder in your instance and in it there's either fml-client-latest.log or fml-server-latest.log based on whether you run it as client or server

**Comment by P3pp3rF1y** [comment]
Any feedback on this?

**Comment by P3pp3rF1y** [comment]
Closing due to nonresponsiveness
