### ISSUE TITLE
[1.12.2] Cyclic Torch Launcher/Interdiction Torch conflict

### ISSUE THREAD

**Issue by TherminatorX** [P3pp3rF1y/Reliquary#290]
Firing a Torch Launcher in the AOE of a IntTorch causes a ticking block exception crash, blaming the blacklist (currently empty)

Reliquary v1.3.4.733
Cyclic v1.11.2
https://pastebin.com/fG4FSwDb

**Comment by P3pp3rF1y** [comment]
I have just released a new version that fixes this.
