### ISSUE TITLE
Fluid handling conflict with Ender IO 1.12.2

### ISSUE THREAD

**Issue by poeticbulldozer** [P3pp3rF1y/Reliquary#291]
A couple of folks testing the shiny new 1.12.2 builds of Ender IO have noted crashes on startup involving Reliquary, specifically the Hero's Medallion item. In both cases I personally read, Industrialcraft 2 was also installed and it seemed to cause some sort of fluid handling conflict. Crash logs are linked below.

I did not experience this issue before installing EnderIO, and when I disabled IC2, Reliquary played nice with EnderIO. But it does appear that the bug originates here.

https://pastebin.com/7Gbi5wpp

https://pastebin.com/p76HvUNy

**Comment by P3pp3rF1y** [comment]
Looks like ic2 is doing something fluid containers in between enderio registering xp juice and reliquary getting reference to that fluid. I guess I will just register it in which case enderio's registration will be ignored and Reliquary fluid will be used.

**Comment by poeticbulldozer** [comment]
A comment from the EIO dev on their discord, just in case it may be helpful-

"the problem is that he's holding a hard reference to a fluid instead of letting it be replaced

yes. basically the gentleman's way of letting other mods register their fluid first and only registering yours if they don't doesn't really work
 
if you want another mod to have the first pick, you need to run after that mod by registering at a lower prio (or with a after dependency)

for fluids with blocks you also need to always register your fluid, even if it's a dupe

(not relevant in this case)

his issue is that he's not prepared for his items to be accessed between item registration and his delayed fluid registration"

**Comment by P3pp3rF1y** [comment]
I have just released a new version that fixes this. And yeah my understanding of fluid registration was incorrect, I thought mods can't replace previously registered fluids, but in fact they do exactly that. So now I am letting them do that instead of waiting for their registration and then refer to registry rather than keeping reference to fluid separately.
