### ISSUE TITLE
Interdiction Torch crashes server when grappling hook lands in range

### ISSUE THREAD

**Issue by superfluke** [P3pp3rF1y/Reliquary#294]
Shooting the motorized grappling hook at the interdiction torch will crash the game. 
Crash log: https://paste.ubuntu.com/p/6R9vWpfPX7/
Reliquary-1.12.2-1.3.4.733
Forge 14.23.1.2604

**Comment by P3pp3rF1y** [comment]
Please try with the latest release of Reliquary. This should be already fixed there

**Comment by P3pp3rF1y** [comment]
There was no response to this, but based on the crash log it was fixed in another issue already so closing
