### ISSUE TITLE
Angelheart Vial and Phoenix Down activate before an Angelic Feather would otherwise save the player from a falling death.

### ISSUE THREAD

**Issue by Scorch-Mechanic** [P3pp3rF1y/Reliquary#300]
Totem of Undying and Amulet of Life Saving (from Twilight Forest) function properly.

Basically, put any combination of Angelheart Vial, Phoenix Down, and Angelic Feather in your inventory and fall off a cliff. Watch as vials shatter, phoenix down turns back into angelic feathers, and health is set to low values instead of the Angelic Feather preventing the damage and spending hunger.

[modlist (2).txt](https://github.com/P3pp3rF1y/Reliquary/files/1757012/modlist.2.txt)

**Comment by P3pp3rF1y** [comment]
this is fixed in latest version on curseforge
