### ISSUE TITLE
Mob Charm duplication bug

### ISSUE THREAD

**Issue by Aylin-NL** [P3pp3rF1y/Reliquary#303]
There is a pretty easy way to duplicate mobcharms that you got. All you need is: the type of mob charm that you want to duplicate and 2 (or more) charm belts.

How it works:
When the charm belts are empty or got exactly the same contents, they stack. If you put a charm in the charm belt when you hold multiple belts, the charm will end up in all belts in your hand. 

I discovered the issue in Project Ozone Lite modpack, with the version from 5-22-2017, Relinquary-1.10.2-1.3.3.664.jar file

**Comment by P3pp3rF1y** [comment]
This was actually fixed some time ago. Try Reliquary-1.12.2-1.3.4.733 or newer and you won't be able to do the same.
