### ISSUE TITLE
auto-fishing with pedestal

### ISSUE THREAD

**Issue by BlueMikius** [P3pp3rF1y/Reliquary#308]
When I put a fishing rod on the pedestal it starts fishing, but when it catch the fish doesn't pick up it and I don't get any loot. It's a bug with the fishing rod or just the fishing rod doesn't work on the pedestal?

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. Looks like I had defaults and minimums swapped in config settings. Which meant that default chance to catch anything was set to 0%. I have fixed this in the code, but you will need to change your config to fix this for you as defaults don't override what you have set in config by now. 
fishing_wrapper_success_rate should be set to 80 by default (80% chance to catch the fish/fishable stuff)
