### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Anarcraft** [P3pp3rF1y/Reliquary#31]
This crash only happens with server, client is fine.

http://pastebin.com/R2cUye8N

**Comment by RedBullSlurpie** [comment]
Yeah same here, probably not working right on server side yet. :P

**Comment by meepmeep22** [comment]
We are currently working on this issue. Thanks for the bug report!

**Comment by RedBullSlurpie** [comment]
Is it fixed in alpha 2? Was working on my 1.8.9 modpack, just testing in single player now. :) Can't seem to download alpha 2 though that you released on the site.

**Comment by meepmeep22** [comment]
The Latest build that diddnt error is here, http://builds.meepmeep22.com/browse/RLQ-UNSTABLE-34/artifact/JOB1/Mod-build/Reliquary-1.3.34.jar
It will most likely crash due to its Unstablyness. You can test it out tho :+1:

**Comment by RedBullSlurpie** [comment]
Cheers. Also, I plan on releasing this a while after building the pack, and haven't read the license and what not for this mod yet, but am i available to use it in my modpack publicly when it gets released?

**Comment by RedBullSlurpie** [comment]
Nevermind.. Just read the license.. :)

**Comment by RedBullSlurpie** [comment]
Just tried using the newest version of the unstable Reliquary can't get Minecraft to start without an error, going to stick with old build for now. :)

**Comment by P3pp3rF1y** [comment]
Thanks for reporting the bug. 

Wasn't that obvious in code, but haven't run the server version before releasing so that's very much my bad.

**Comment by RedBullSlurpie** [comment]
All is good! I will check back once a version is released for 1.8.9 that works both client and server. Thanks for all your work and dedication! <3

**Comment by P3pp3rF1y** [comment]
I have released the fixed version at https://bintray.com/artifact/download/p3pp3rf1y/maven/Reliquary-1.3-alpha1.87.jar 

And the same on curseforge as well.
Now back to alpha2...

**Comment by RedBullSlurpie** [comment]
Thank you! <3
