### ISSUE TITLE
[1.7.10] Server crash due to LibSandstone download failing

### ISSUE THREAD

**Issue by Rautherdir** [P3pp3rF1y/Reliquary#314]
Attempting to create a server using Reliquary 1.2.257 fails due to LibSandstone not being available from https://drone.io/github.com/EnderWizards/libsandstone/files/build/libs/LibSandstone-1.0.0.jar

I tried fixing it by manually adding LibSandstone to the server, but that caused the server to crash with the following error:
`java.lang.NoClassDefFoundError: Llib/enderwizards/sandstone/init/Content;`

**Comment by P3pp3rF1y** [comment]
Sorry, I don't support 1.7.10 anymore, but if you have downloaded the version from my curseforge page (https://minecraft.curseforge.com/projects/reliquary-v1-3/files) there should be no dependency on libSandstone there or on deploader that would be trying to load it.
