### ISSUE TITLE
[Suggestion] Visual indicator of a staff's current shift-left click mode

### ISSUE THREAD

**Issue by genandnic** [P3pp3rF1y/Reliquary#319]
I spent a good 10 minutes trying to figure out why my rending gale had stopped working in the middle of a building project, then I realized I had accidentally switched modes. A message above the hotbar that indicates which mode was just switched to could prevent future confusion. A tool-tip on the item indicating it's current mode would also be nice.

**Comment by P3pp3rF1y** [comment]
Are you not seeing the staff's information in HUD? There should be information of its mode and charge in HUD and you can change its position to whatever works for you through hud_positions setting in config.

**Comment by P3pp3rF1y** [comment]
I assume you can actually see the HUD given no response and thus closing.
