### ISSUE TITLE
Harvest Rod set to auto-absorb, placed on upgraded Pedestal crashes server.

### ISSUE THREAD

**Issue by erian-7** [P3pp3rF1y/Reliquary#320]
Playing through on the World of Dragon server and testing Reliquary. After upgrading the Pedestal with diamonds, I placed it, then put the Harvest Rod on top. It worked as expected, fertilizing and harvesting crops. I then set the Harvest Rod to auto-absorb mode. When placed on the Pedestal, the server crashed, and continues to crash if anyone nears that chunk.

**Comment by P3pp3rF1y** [comment]
Could you add a crash log? Without that there's not much I can do.

**Comment by erian-7** [comment]
Yep, I'll try to get one from the server owner.

**Comment by P3pp3rF1y** [comment]
Just to be sure I have retested with rod set to absorb in enabled pedestal and I don't see any issue. Also code wise rod being set to absorb does something only when in player's inventory and has no effect or even get checked when in pedestal.
So the issue you get there must be related to something else. Possibly interaction of pedestal with some kind of pipes?

**Comment by erian-7** [comment]
So far I've been unable to duplicate the error, and it looks like the
server crash logs got wiped. If I can get to occur again, I'll be sure to
shoot you the log but I guess for now it can be closed as a one-off.

**Comment by P3pp3rF1y** [comment]
closing
