### ISSUE TITLE
[Suggestion] Lingering potions work on bullets

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#321]
I kinda wanted to not use the reliquary potion system in favor of another mod. Is there a way to make bullets use lingering potions (vanilla) in their crafting as well?

**Comment by P3pp3rF1y** [comment]
You can create custom recipes to use the vanilla ones for the same purpose. I don't have anything code to enable this as I definitely want players to use Reliquary potion system

**Comment by Akitori** [comment]
How would one do that? Using Minetweaker i suppose?

**Comment by P3pp3rF1y** [comment]
yes that would be minetweaker or crafttweaker. and I am actually going to close this as I don't want to implement this as a feature in Reliquary given that modpack devs can get it done through crafttweaker.
