### ISSUE TITLE
[Bug] Void Tear and Pedestals not playing nice together. Conversion Bug detected!

### ISSUE THREAD

**Issue by Nytale** [P3pp3rF1y/Reliquary#322]
So i was trying to automate my Creeper Farm and i tought i'd use the **_Pedestals_** in conjunction whit the **_Void Tears_**. Set the tears to the items they should absorb but then the issues started, it seems the pedestal whit the **_Coin of Fortune_** always tries to put the items in the pedestal to the **North**(whit void tear on) and items that doesnt go in that **_Void Tear_** simply gets deleted. This happens regardles if the void tear is activated OR the pedestal it is placed on is activated.(obviously the pedestal whit the CoF is activated.)

In the pictures you can see im using a Heroes Medalion aswell but that seems to work as intended, xp gets sucked up and put into it.

**_Update:_** It seems the items doesnt get "deleted" perse', instead they are converted into the item the void tear is holding. So if void tear is storing gunpowder, items gets converted to gunpowder. Tested it in a creative world and lo and behold.. im converting seeds into beacons and diamonds and all that wonderful shite >.<

_**Update again:**_ Fresh install whit only reliquary(1.3.4.760) and the latest version of Forge(14.23.3.2673) still able to reproduce the bug...

### Versions:
MC 1.12.2
MCP 9.42
Forge 14.23.2.2619

### Mods:
Baubles 1.12-1.5.2
BetterFps 1.4.8
blockdrops 1.12.2-1.4.0
Inventory Tweaks 1.64-dev
JEI 1.12.2-4.87.5.147 + JEI Integration/Resources and NEI 1.12.2-2.4.1.233-Universal
Openblocks 1.12.2-1.7.6
OpenModsLib 1.12.2-0.11.5
RandomThings-MC1.12.2-4.1.5
**Reliquary-1.12.2-.1.3.4.760**
SimpleHarves 1.12.2-1.2.6-18

## Pictures:

![2018-04-24_15 33 27](https://user-images.githubusercontent.com/4303849/39190589-2ec55370-47d5-11e8-899e-e6f7bd1c4def.png)
![2018-04-24_15 34 32](https://user-images.githubusercontent.com/4303849/39190600-345b0316-47d5-11e8-9299-82444ee5a1c5.png)
![2018-04-24_15 34 53](https://user-images.githubusercontent.com/4303849/39190609-372b451a-47d5-11e8-8f2a-a294690b5395.png)
![2018-04-24_15 34 56](https://user-images.githubusercontent.com/4303849/39190615-392e68ba-47d5-11e8-9d09-e7f48e061c47.png)

**Comment by P3pp3rF1y** [comment]
Sorry that I haven't commented on this one. This is very odd behavior, I will take a look and try to fix/release ASAP
