### ISSUE TITLE
[1.12.2-1.3.4.760] crashes server while spawing flight particles

### ISSUE THREAD

**Issue by kreezxil** [P3pp3rF1y/Reliquary#323]
this would crash sooner if I turned down my max-tick-time

server crash report: https://gist.github.com/5812d585260fa3977f9def7c5e7ad670

**Comment by ahlexrull** [comment]
I was using the rending gale staff underwater as a fish morph, which may have contributed/caused a server crash.

**Comment by P3pp3rF1y** [comment]
So I have no idea what exactly is happening there for you. Based on the stack trace it crashes in the code which has no chance of slowing down tick speed at all unless something blocks property collection of block snow (which is empty by default). Also rending gale generates only maximum of 8 particles in a tick so I don't see this slowing the server either. 

My guess is that there's either something going wrong on the server and it just happened to crash in this part of the code or that there's really some mod misbehaving and messes with block snow. I have seen previously this block completely missing from block state registry based on crash reports I got so there may be something messing with it.

if you are actually able to recreate this with just reliquary and that morph mod (what's the name?) let me know and I will take a look.

**Comment by kreezxil** [comment]
we're using metamorph by horsewithnoname at
https://minecraft.curseforge.com/projects/metamorph

**Comment by P3pp3rF1y** [comment]
I tried testing with metamorph and am unable to slow down the instance with rending gale at all (apart from getting player moved too quickly messages). Tried with squid and silverfish morphs. 
So I really believe it's some other mod causing this issue for you. If you're actually able to recreate with just reliquary and metamorph let me know.

**Comment by P3pp3rF1y** [comment]
closing as there was no follow up and I can't recreate
