### ISSUE TITLE
[1.12.2 builds 760/763] Altar of Light is... stuck?

### ISSUE THREAD

**Issue by Geethebluesky** [P3pp3rF1y/Reliquary#326]
There seems to be an issue with the Altar of Light; granted I'm new to Reliquary so maybe I did something wrong? Just created the block, fed it enough redstone for the text at the top to appear, but it's been static and unchanging for most of my last playthrough, in addition to displaying a **Format Error**.

I do play with many other mods, not sure what would be useful to post, there's nothing in any logs except for this in **debug.log** which is probably unrelated (?)

>	Line 8542: [21:01:44] [Server thread/TRACE] [FML]:   Registry: 4567 xreliquary:altar xreliquary.items.block.ItemBlockBase@27f6e3f7
	Line 14996: [21:01:44] [Server thread/TRACE] [FML]:   Registry: 2192 xreliquary:blocks/altar net.minecraft.item.crafting.ShapelessRecipes@103b7c54
	Line 17394: [21:01:44] [Server thread/DEBUG] [FML]: Registry Block: Fixed minecraft:blocks id mismatch xreliquary:altar: 433 (init) -> 1101 (map).
	Line 19574: [21:01:44] [Server thread/DEBUG] [FML]: Registry Item: Fixed minecraft:items id mismatch xreliquary:altar: 4567 (init) -> 6392 (map).

![Screencap](https://i.imgur.com/wf9VjIJ.png)

**Comment by P3pp3rF1y** [comment]
Does it have access to sky above? that is in the column above it there can't be any block that blocks light. Also it generates glowstone block on top of it once done so that banner will need to be moved to make place for it.

**Comment by Geethebluesky** [comment]
Ah ok, newbie issue. Thanks for taking the time to explain!
