### ISSUE TITLE
Rending Gale Stops Server(no crash log, just freezes)

### ISSUE THREAD

**Issue by CappleApple** [P3pp3rF1y/Reliquary#327]
When the rending gale is used(and the user is on the ground) the server just freezes with a message of the player moving to fast, and never revives itself.

**Comment by MisterSoandSo** [comment]
I've also gotten the same issues on servers.

**Comment by P3pp3rF1y** [comment]
I will need a bit more of info on this. 
Are you having this issue as part of a pack?
Are you able to recreate with just Reliquary?

I am not able to recreate this in dev at all so I am guessing it's another mod doing something "fancy".

**Comment by MisterSoandSo** [comment]
@P3pp3rF1y I'm using Reliquary-1.12.2-1.3.4.763 with forge version 2703.

The only thing that console would register is that I'm flying too fast and it would go straight into a coma until I actually kill the minecraft java process to allow for reboot on my server.

This is the java parameter that I use to run the server: java -jar -Xmx4G -Xms4G -jar forge-1.12.2-14.23.4.2703-universal.jar nogui-XX:ParallelGCThreads=1

**How I recreated**: I fly around for a long time with an angelic feather in my inventory. Then after a minute or two, the server dies/goes into  a coma.

**Comment by P3pp3rF1y** [comment]
And reliquary is the only mod in the pack?
Also angelic feather? You have that in your inventory while flying with rending gale?

**Comment by MisterSoandSo** [comment]
I have other mods but it seems to be the only one that suspicious.
It only happens when players use the rending gale ... I have another player on my server confirm it.

**Comment by CappleApple** [comment]
It has to do with minecraft anti cheat. I put a mod in the server that
disables it and it eliminated the problem.

**Comment by MisterSoandSo** [comment]
@P3pp3rF1y I probably give you my test results in a day or two. As there are people on my server at the moment of me responding to your question.
@CappleApple  do you have flight-enable  - true on the server setting?

**Comment by ChrisPVille** [comment]
I've noticed something like this on a server I host for a few friends.  I'm not sure if this is related to #274 but I am using 1.3.4.757 as part of the FTB Revelation 1.8.0 pack.

It looks like the main server thread gets into an unresponsive loop of some sort.  The console thread still remains accessible, but commands do nothing in this state.  I dumped [the stack of the entire process](https://github.com/P3pp3rF1y/Reliquary/files/2087474/Minecraft.hang.txt).

Here's the trace for the offending thread:

> "Server thread" #18 prio=5 os_prio=0 tid=0x00007fb7b14a6800 nid=0x509 runnable [0x00007fb769298000]
>    java.lang.Thread.State: RUNNABLE
>         at net.minecraft.world.World.func_175720_a(World.java:1168)
>         at net.minecraft.world.World.func_175688_a(World.java:1147)
>         at xreliquary.items.ItemRendingGale.spawnFlightParticles(ItemRendingGale.java:404)
>         at xreliquary.items.ItemRendingGale.onUsingTick(ItemRendingGale.java:243)
>         at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2668)
>         at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
>         at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
>         at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
> ...
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
>         at java.lang.Thread.run(Thread.java:748)

Again, this may already be solved with #274, and I haven't looked at exactly what version of ItemRendingGale.java I'm living with.  I thought I'd add this in case it's helpful.

**Comment by P3pp3rF1y** [comment]
I have released a new version yesterday that has a performance improvement which should hopefully solve this for you. Could you retest with that and let me know?

**Comment by P3pp3rF1y** [comment]
closing, there was no more feedback on this so the changes probably helped.

**Comment by KosmosPrime** [comment]
I've had this problem just now (version 1.3.4.786). Looking at the JConsole output, I'd like to blame this line:
https://github.com/P3pp3rF1y/Reliquary/blob/57bd2c4ddc79d629664de85068f9326acf779286/src/main/java/xreliquary/items/ItemRendingGale.java#L395
The way I see it, if you are looking exactly along an axis, the aim direction vector will be zero for the other axis. This would cause `factor` to become infinite if you move sideways even slightly. The following loop would then never terminate, because every `int` is smaller than infinity.
I'm not sure what the factor is meant to express, so I can't make a reasonable pull request. I'm currently testing what happens if the division is simply removed and will leave another comment if the bug still happens.
