### ISSUE TITLE
Tome of Alkahestry + Industrial Craft 2 Batch Crafter = Unlimited Charges (Bug + Suggestions/Requests)

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#328]
**Bug:**

Album explaining the specifics: https://imgur.com/a/VXWTYYt

I found this while looking for a way to use an autocrafter to recharge the Tome. The Tome seems to cause a lot of different bugs when it comes to autocrafters. I'd assume this one is more on the IC2 end rather than the Reliquary end so I'll cross post this on their github. But this would be a much smoother way of going around it, 

**Suggestion:** Nerf the Tome so you cannot charge it via a crafting table, but only by absorbing from your inventory. This will prevent any more autocrafting bugs.

**Suggestion:** Add new item: Altar of Alkahestry. 
Potential Crafting Recipe: https://imgur.com/k7JUt1J
The base is octuple compressed cobblestone, which isn't vanilla, but the point is for this to be extremely end-game. Maybe introduce compressed nether stars as a new item or something. The Altar would be able to store store charges by pumping redstone into it. Then any item you place on the Altar would be duplicated as long as there was enough charges. This would allow for it to be automated. 

**Suggestion:** If the Altar or equivalent is introduced, nerf the Tome so it can only reach 256 charges. The equivalent of one Nether Star.

**Suggestion:** Add new item: Missing Pages. (This would be a lot of work though, included as an afterthought)
Going through dungeon chests lets players find missing pages to add to the book. Each missing page would add a new item or set of items that could be duplicated. When you right click the book it would open up its own internal inventory with x-amounts of slots for missing pages. You could make it so the Altar requires a completed book, which would make it much more endgame.

**Comment by P3pp3rF1y** [comment]
First of all overcharging the Tome shouldn't be possible anymore following the changes I have done recently https://github.com/P3pp3rF1y/Reliquary/issues/317.

The other part you're right that IC2 doesn't properly call recipe methods and as a source one it seems to use the tome that was used at the time recipe was defined.

The altar and pages are an interesting thought, but I am not really interested in getting tome closer to EE.

And it is limited to 1000 by default so it's not extremely high, it's just that if auto crafter is broken it may produce results like this, but that breaks more than just tome, I would guess that if you try repairing items by combining them in there and use just a tiny bit broken one to set recipe and then pass almost totally broken ones that you will see those repaired much cheaper than in crafting table.

So I am going to close this one.
