### ISSUE TITLE
Tome of Alkahestry: config options

### ISSUE THREAD

**Issue by belathus** [P3pp3rF1y/Reliquary#330]
As recently as 1.10.2, we had a ton of options for changing recipes using the Tome of Alkahestry in the configs (changing what item charges it, etc.). I don't see them anymore. By chance, will we be getting that capability back, or does it exist in a different way?

I mostly ask since some mods make getting redstone extremely easy (IE: Extra Utilities and its red orchids), making it super easy to charge the tome of alkahestry, and I'd like to change it to use a different type of material. Further, I'd love to add extra things you can duplicate using the tome.

**Comment by P3pp3rF1y** [comment]
These have moved to json recipes with 1.12. Check https://github.com/P3pp3rF1y/Reliquary/tree/1.12.x/src/main/resources/assets/xreliquary/alkahestry
And you should hopefully see a folder config/xreliquary/alkahestry_overrides, which is where the overrides for these go. As soon as you include one of the folders (crafting/charging/drain) in there the default ones are ignored, which means that when you just need to add some you need to include all the default ones in that given folder as well.

But for your case should be enough to include charging folder with the your charging recipe.

Let me know if you will have any questions.  I will leave this open for a bit just in case.

**Comment by belathus** [comment]
Awesome, thanks! I'll work with this over the next few days. I'll ask if I have any issues.

**Comment by P3pp3rF1y** [comment]
Closing, I hope you would have asked or reported issues related to this by now. Feel free to open new issue if you find anything though.

**Comment by JonasDoe** [comment]
You might want to add that to the wiki which is kinda vage about it. ;)
