### ISSUE TITLE
Alkahestry Tome options not found in config

### ISSUE THREAD

**Issue by Icecreep109** [P3pp3rF1y/Reliquary#331]
I am playing in a custom modpack based on a modified version of FTB Revelation.  I am trying to add items to the Alkahestry Tome for ease-of-life reasons, but I can't find the config to edit. In the modpack config folder there is an empty folder labeled alkahestry_overrides, which I assume is the one I need to modify. 
 I need to add an override file to the folder, but I'm not sure what that requires, and what the proper formatting is.

**Comment by P3pp3rF1y** [comment]
Take a look at this #330
