### ISSUE TITLE
[1.12.2] Crash on start up at Linux

### ISSUE THREAD

**Issue by Draskh** [P3pp3rF1y/Reliquary#332]
[crash-2018-06-06_18.17.04-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/2077172/crash-2018-06-06_18.17.04-client.txt)

**Comment by P3pp3rF1y** [comment]
I am a little puzzled by this exception, because the implementation here is the same as the one used by forge to load crafting recipes.

Are you actually able to use minecraft with just forge installed on top of it?

**Comment by Draskh** [comment]
I had the same issue with EnderIO. Look into their repo. They added code complete as label to this issue.

**Comment by P3pp3rF1y** [comment]
The one that you have entered there actually was a very different crash. Could you test if you can run just forge without any additional mods?

**Comment by Draskh** [comment]
I will test that the next days.

**Comment by Alsender** [comment]
OS: Ubuntu 17.10 GNOME 3.26.2 (amd64)
Java: 1.8.0_171
Minecraft 1.12.2
Forge: 14.23.4.2756

I am getting the same [crash](https://gist.github.com/Alsender/ee38fcb5dc85b5ea9b03babd06844027) as NickelHub.  Minecraft runs fine with [forge alone](https://gist.github.com/Alsender/e4ea38b2ac2354d5c193b1f37284b4d9) installed, but crashes as soon as I try to add Reliquary.  Forge also runs fine with [additional mods](https://gist.github.com/Alsender/7bbf8a30eae7b1147a75a523d735dc80) installed as well.

**Comment by P3pp3rF1y** [comment]
I have investigated a bit more and it seems to relate to a corrupted java installation. There are reports of the same issue for forge where reinstalling java fixed it.

So I am going to close and suggest people try to reinstall java if they get this. Let me know if you're able to recreate even after reinstall.
