### ISSUE TITLE
Cauldron particles move when player moves horizontally.

### ISSUE THREAD

**Issue by danibot-dz** [P3pp3rF1y/Reliquary#335]
When the Player moves (not his view) horizontally, the bubbles that appear when inserting Netherwart in the cauldron also move, out of the block and then come back to stop moving. And I think the item "Handgun" .... I understand the idea, and I understand that the mod is yours and that you can do whatever you want in it, but that's a long way from the minecraft vanilla (which has cavernicle technology). I would like you to put the option to disable mod items.

**Comment by P3pp3rF1y** [comment]
So the cauldron particles I will take a look at. 

Handgun is a part of the mod and it's definitely not going away. It's certainly your personal taste that "it doesn't fit MC", I can think of hundreds maybe thousands of other items in modded mc that wouldn't fit in that case. You can either ignore it and not use it or use a mod that is capable of removing recipes (like crafttweaker) to make it uncraftable.

Also a word of advice: Using a lot of caps and repeated letters isn't going to help you at all and even though I am fairly calm guy it almost made me just outright close this issue with no comment.

**Comment by danibot-dz** [comment]
Oh my God, I really hate writing. It's impossible to reinforce an idea without being rude ...
I just used "a lot of caps and repeated letters" because I thought it would reinforce this crap idea.
Sorry, please excuse me.

Now that you said to me I realized that I spoke very imperative mood, all the time.

I just wanted to see this option added in your mod ...
But I already understand that you do not want to.
Thank you.

**Comment by danibot-dz** [comment]
Do you people who speak English do not like that? If so, I did not know. Oh my God, I'm even depressed now ...

**Comment by P3pp3rF1y** [comment]
I took a look at the particles some time ago and couldn't really see anything wrong with them I am guessing it was mod compatibility issue. closing this
