### ISSUE TITLE
Request: Option to prevent the pedestal from counting as a player kill

### ISSUE THREAD

**Issue by TheDeviantCrafter** [P3pp3rF1y/Reliquary#337]
The pack I'm working on is based around interesting automation. For that reason, I want the only killing method that can emulate a player kill to be Open Modular Turrets. These need to be supplied with bullets, which will require a supply line.

I don't want to disable the pedestal entirely. It's too interesting and unique to remove. Unfortunately there doesn't seem to be a way to control this so I may have to.

A config option to stop the sword from working at all would work as well. That might be easier to implement.

**Comment by P3pp3rF1y** [comment]
This would likely involve a lot of code on Reliquary side. Just causing damage to entity using different damage source is easy, but then all enchantments and other stuff doesn't get handled so I would likely have to hack it somehow. I would say just disable it if you absolutely don't want to have pedestal cause player damage.
