### ISSUE TITLE
Void Tear cannot be taken out of ME system from AE2

### ISSUE THREAD

**Issue by Kruimel24** [P3pp3rF1y/Reliquary#338]
Whenever I put a Void Tear into my ME system from AE2, it gets stuck and I'm unable to retrieve it, can't pipe it out, can't take it out, can't use an export bus, nothing works.

**Comment by P3pp3rF1y** [comment]
Have you tried reporting this to AE first? There’s nothing special in void tear’s code that could cause that issue on Reliquary side. Seems more like AE may have issues with capability data on void tear perhaps even though I doubt that one as well.

**Comment by P3pp3rF1y** [comment]
I am guessing this is a non issue given no response.
