### ISSUE TITLE
Question on Pedestals

### ISSUE THREAD

**Issue by Joeburrell64** [P3pp3rF1y/Reliquary#339]
Just a quick question for anyone who can help. I am using All The Mods 3, and the pedestal does not seem to use enchantments that a sword has. I am using a supremium sword with a reaper 5 enchant, yet no Draconic Evolution souls are dropping. Is there a compatability issue?

**Comment by P3pp3rF1y** [comment]
Enchantments definitely get applied as all vanilla ones definitely work, but it's whoever implements the enchantment that also handles how it gets applied. So I am guessing that DE has some kind of condition that prevents fake players from using the enchant possibly.
