### ISSUE TITLE
[Suggestion] More controls in config file to disable different areas of the mod  - Pull request?

### ISSUE THREAD

**Issue by Lothrazar** [P3pp3rF1y/Reliquary#345]
Many modpack devs will have a hard time fitting in the entire mod and may want to disable certain parts of it they deem OP or not relevant, examples are the Tome and the potions.

In the config file there could be one boolean flag for each part of content to disable anything they like.  

Would you be willing to accept a pull request and do a release if i made these code changes and submitted them?

**Comment by LemADEC** [comment]
Any update on this?

**Comment by P3pp3rF1y** [comment]
This was implemented a long time ago, closing ...
