### ISSUE TITLE
[Suggestion] Ender Dragon Charm and Wither Charm

### ISSUE THREAD

**Issue by Griefed** [P3pp3rF1y/Reliquary#346]
Good day!

As the title says, I'd love to have a charm for the Ender Dragon and Wither. Maybe not the Wither, but definitely the Ender Dragon would be awesome. 
I've got my base in The End and I've killed the Ender Dragon about 104 times now (Draconic Evolution stuffs...I've spent so much time on killing that dragon. Never again :D ), but I like the Ender Dragon. It would be awesome to have it fly around without attacking you. As a decoration, if you will.

The charm should be expensive. I mean, it's the Ender Dragon after all! 
Maybe make it possible to deactivate it in a config. Customization is always appreciated.

That is pretty much it!
Thanks for your time, have a nice day.

Cheers,
Griefed

**Comment by P3pp3rF1y** [comment]
Closing this. the charms are not supposed to protect against bosses who are by default excluded. But in dev version I actually have a config for this so anyone can add this (or rather remove dragon/wither from list of blocked entities), would just need to kill a lot of dragons anyway if enabled in there.

**Comment by Griefed** [comment]
Thanks for getting back to this. :)
