### ISSUE TITLE
Rending Gale looses charges

### ISSUE THREAD

**Issue by xenoxsis** [P3pp3rF1y/Reliquary#350]
I have been unable to consistently reproduce this issue. So this issue is merely to bring attention to it, and to learn if others perhaps are experiencing the same issue.

I am logged on all day to my Modern Skyblock 3 server (either playing or afk), and I am often using Rending Gale to move around.

But sometimes it seems that Rending Gale suddently looses charges. It can go from 200 feather charges to zero. Like I said I have not yet found a pattern as to why this might occur (though I will keep a lookout). But maybe someone else is experiencing the same thing.

If you have any specific information I can supply, let me know.

**Comment by P3pp3rF1y** [comment]
Are you using it on a server or playing in single player?
Also when that happens are you moving the rending gale between inventories (chest / backpack) and possibly sorting your inventory with something like inventory tweaks?
Not that this alone would provide me enough info, but helps a bit to narrow it down.

**Comment by xenoxsis** [comment]
Feel free to ask away.

It's on a server. It's doesn't seem to be happening when I do any activities (though I'll watch out for that). I've had it happen a few times when standing still AFK and then when I came back I'd use it. And it seems to have 1 feather worth of charge and then nothing. So I go fill it back up to 299 and everything is fine for a while again.

It happens something like once a day.

I'll have to monitor if it happens when I leave it while holding it or not. If I see any further patterns I'll get back to you.

**Comment by P3pp3rF1y** [comment]
closing, this was likely some kind of inventory interaction issue where capability storage got wiped up. these days inventory mods treat capability storage better and anyway if this happens again i would need more concrete steps to be able to recreate and fix.
