### ISSUE TITLE
Cannot disable existing alkahestry tome recipes

### ISSUE THREAD

**Issue by Lothrazar** [P3pp3rF1y/Reliquary#354]
https://github.com/P3pp3rF1y/Reliquary/issues/330

Related to above. 

I added empty folders inside the overrides folder, but it did not remove any recipes.  I just want to disable everything in the alkahestry tome 
![config](https://user-images.githubusercontent.com/621529/50045468-25015380-0048-11e9-8a8a-5ae23ba5990a.PNG)

**Comment by P3pp3rF1y** [comment]
The way it works is as soon as there's one recipe loaded from the given folder (crafting/charging/drain) that same folder isn't loaded from the default recipes. So if you want to override that category just include your new recipe there. If you wanted to completely disable that then I would say just making tome of alkahestry uncraftable would be the way to go. And if you wanted to get rid of JEI displaying most recipes then I guess just include one in each folder - could be even something ridiculous like charging with bedrock, draining bedrock and duplicating bedrock.

**Comment by P3pp3rF1y** [comment]
closing as this works as expected.
