### ISSUE TITLE
1.12.2 Mob Charm(zombie) Crash error (mod confilct) 

### ISSUE THREAD

**Issue by RoyalRedKing** [P3pp3rF1y/Reliquary#356]
Using a zombie charm with 2 or more zombies with the zombie awareness mod causes a crash. this is happening in a mod pack (Dimension zero) but it has to be a conflict since with the charm they can't see you. then if you hit a zombie and there is more in the area they don't know where you are therefore causing a crash.

**Comment by callmesabs** [comment]
This issue occurs without the Zombie Awareness mod installed.  It isn't a mod interaction.  It also affects blazes.  Please see #355

**Comment by P3pp3rF1y** [comment]
this was fixed before, closing...
