### ISSUE TITLE
Request: Allow pack devs to create custom charms

### ISSUE THREAD

**Issue by TheDeviantCrafter** [P3pp3rF1y/Reliquary#358]
There are plenty of modded mobs that players may want to be invisible to. The base mod only supports vanilla mobs, so I'd like a way to add my own.

I can handle recipes, textures and even creating the actual item through CraftTweaker and ContentTweaker. I'd like to be able to add an item ID and an entity ID to a config somewhere. When the item with the specified item ID is equipped, mobs with the specified entity ID won't be able to see you.

**Comment by P3pp3rF1y** [comment]
closing this, in 1.16 there are now charms registered for all hostile mobs in game and from next version there's going to be a block list for any entity that mod pack dev doesn't want charm for in their modpack
