### ISSUE TITLE
1.10.2 Broke HunterHandGun

### ISSUE THREAD

**Issue by PerilousHeretic** [P3pp3rF1y/Reliquary#359]
Hunter's hand Gun, craftable, can be loaded, won't fire. Everything is being done right, but it won't fire. RIght click does nothing. Controls are all correct.

**Comment by P3pp3rF1y** [comment]
This is likely mod interaction issue as that code hasn't been touched in ages.
Have you got it in a modpack?
Can you try with just Reliquary if so?

**Comment by PerilousHeretic** [comment]
it is not in a modpack, its seperate
is there other mods that i need for it?

**Comment by P3pp3rF1y** [comment]
No other mods are needed.
I have just tested with just reliquary and it works for me. you're right clicking to fire, right?

**Comment by PerilousHeretic** [comment]
Im using it in an Aternos server, 1,10,2, I will show you a list of the mods, dont know if any of them would conflict 
 https://cdn.discordapp.com/attachments/494331707017658368/538415544446091279/unknown.png

**Comment by PerilousHeretic** [comment]
On single player it fires extremely slow. I have used it in a modpack before (Infinity lite) and it fired just fine, beautiful. Do you think any of those mods conflict it in the image list i sent?
