### ISSUE TITLE
Twilight Cloak causes freeze loop interacting with evolved enderman mod

### ISSUE THREAD

**Issue by CaptPanda** [P3pp3rF1y/Reliquary#360]
Uncertain if this belongs here or if this is an issue with Evolved Enderman mod, but while wearing an active twilight cloak, looking at an evolved enderman causes game/server to freeze by infinite looping.

Modpack is 'All the Magic', please find pastebin attached and if I should inform the EE devs instead.

https://pastebin.com/bTt29rhX

**Comment by CaptPanda** [comment]
Mod versions:
Reliquary-1.12.2-1.3.4.780
EndermanEvolution-1.12.2-1.0.15

**Comment by P3pp3rF1y** [comment]
closing this, no longer support 1.12.2 and enderman evolution isn't ported past that.
