### ISSUE TITLE
Void Tear getting stuck

### ISSUE THREAD

**Issue by Cazadorsniper** [P3pp3rF1y/Reliquary#364]
Reliquary-1.12.2-1.3.4.780
It seems when the void tear is turned on it gets stuck in an AE2 me system.

**Comment by Cazadorsniper** [comment]
I'll report this to AE devs too, just saw the closed issue of this.

**Comment by Cazadorsniper** [comment]
Found that it can be removed from the me network through an export bus.

**Comment by P3pp3rF1y** [comment]
yeah this is on AE/Forge side given that they don't track slots I can imagine it's hard to see what stack player tries to take out of the system as the stack on client is different from the one on server. Closing here anyway as there's nothing I can do about this and you have your workaround anyway.
