### ISSUE TITLE
[Crash]  Reliquary-1.12.2-1.3.4.786 Disabling Pedestal causes game to not load

### ISSUE THREAD

**Issue by Akitori** [P3pp3rF1y/Reliquary#375]
Hello.

To duplicate:
1. Go to config files.
2. Disable Pedestal.
3. ???
4. Profit.

Crash Report.
https://pastebin.com/QYsE8R5p

Tested on both Latest and Recommended forges for 1.12. (2824 and 2796 respectively)

**Comment by P3pp3rF1y** [comment]
no longer support 1.12.2 version and this is now reworked in 1.16.5 to proper way of always registering items and instead just disabling recipes / removing items from creative /jei view.
