### ISSUE TITLE
Make Hunter's Handgun's XP scaling to be modified

### ISSUE THREAD

**Issue by MorzanTLD** [P3pp3rF1y/Reliquary#376]
It would be nice if I could modify the max level that the hunter's handgun scales at. Specifically, so I could change the scaling of the handgun that it maxes out at 30 or 60 but has the same max 'power' and just scales slower.

**Comment by P3pp3rF1y** [comment]
this is now a thing in 1.16.5 dev build

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
