### ISSUE TITLE
Void Tear stealing items

### ISSUE THREAD

**Issue by Erhannis** [P3pp3rF1y/Reliquary#378]
This has happened twice in the past half an hour.  I'm playing Modern Skyblock 3.5.0, with Reliquary 1.3.4.780.  I loaded up the void tear with 1000+ menril wood planks, then moved the void tear into my inventory from my hotbar.  I think then I went and looked at a guide for Factory Tech or something.  When I came back, my void tear was no longer sealed, and my menril planks were gone.  Again, this has happened twice in half an hour.

**Comment by P3pp3rF1y** [comment]
I will really need more specific steps on how to recreate this and if that involves moving the void tear into some other inventories it may be likely those inventories are actually deleting its contents as it uses capability storage to track its contents and some inventory mods at least in the past were not prepared for that.
