### ISSUE TITLE
Rending Gale Elytra compat

### ISSUE THREAD

**Issue by KalaMiDeviL** [P3pp3rF1y/Reliquary#380]
Can you make it so the staff lets you keep your gained inertia while the wings are deployed? I hate the fireworks sound wih a passion.

**Comment by KalaMiDeviL** [comment]
Oh, and can you prevent durability use on the elytra during propulsion?

**Comment by P3pp3rF1y** [comment]
probably late for you, but this is now added in 1.16.5 (in dev at the moment)

**Comment by KalaMiDeviL** [comment]
Too late? What are you talking about? This is minecraft. I‘m gonna be playing this game on my own funeral.
Thank you!

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
