### ISSUE TITLE
1.7.10 Tome of Alkahestry no longer properly readable

### ISSUE THREAD

**Issue by Faedelity** [P3pp3rF1y/Reliquary#381]
I think they must have changed something with Guide-API since the last time you updated the book. The text on the main page now runs off to the side on each line, probably due to a change in font size. It's not completely useless, but it looks very bad and can be hard to read if the surroundings are dark. 

I understand you might not still be actively supporting 1.7.10, but I would be willing to provide fixed formatting if you're willing to release an update. Not sure if there are more pages yet (I have only seen the first page), but more pages would not bother me; I like fixing things like this.

**Comment by P3pp3rF1y** [comment]
sorry I don't support 1.7.10 and I don't really want to do a release for that either. Also the tome doesn't really have any useful info even if fixed. it's only really useful in crafting.
