### ISSUE TITLE
Ender staff bypass / missing event

### ISSUE THREAD

**Issue by LemADEC** [P3pp3rF1y/Reliquary#390]
As of Reliquary-1.12.2-1.3.4.796, the Ender staff can be used to enter protected area.
Please use the EnderTeleportEvent cancellable event when teleporting player, like Ender pearls, Endermen and Shulkers do.

**Comment by PiggiesGoSqueal** [comment]
If this is still an issue than +1 on it being fixed for 1.12.2 if 1.12.2 is still in development.

**Comment by P3pp3rF1y** [comment]
not for 1.12.2 at this point but this is now added in 1.16.5 dev build and will be released soon

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
