### ISSUE TITLE
Rending Gale hang/crash

### ISSUE THREAD

**Issue by 7anner** [P3pp3rF1y/Reliquary#391]
I'm having some issues with the Rending Gale crashing a server.  We're running the FTB Unleashed Reloaded modpack (which typically has Rending Gale disabled) so I understand if this is out of scope.
Additionally, I think it would be very nice if the rending gale's speed were configurable.

> java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
> 	at net.minecraft.world.World.func_175720_a(World.java:1169)
> 	at net.minecraft.world.World.func_175688_a(World.java:1148)
> 	at xreliquary.items.ItemRendingGale.spawnFlightParticles(ItemRendingGale.java:403)
> 	at xreliquary.items.ItemRendingGale.onUsingTick(ItemRendingGale.java:242)
> 	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097)
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Unknown Source)

I've got fuller crash data, so let me know if you need anything else.

**Comment by P3pp3rF1y** [comment]
this was fixed in release of august 13th last year
