### ISSUE TITLE
Pyromancer's Staff infinite fireballs bug

### ISSUE THREAD

**Issue by Sarund9** [P3pp3rF1y/Reliquary#392]
when firing the pyromancer's staff it continues to shoot fireballs from that spot. /kill @e does nothing.
Quitting and rejoining fixes it

**Comment by P3pp3rF1y** [comment]
I have no idea how this happened to you. right click spawns exactly one fireball, there's no loop in the item's logic of spawning the fireball so they only thing I can think of is the game somehow decided to continue running right click on pyromancer's staff. likely some mod causing that. closing this anyway as it's pretty old one.
