### ISSUE TITLE
(Suggestion) Allow Void Tear To Work In Containers

### ISSUE THREAD

**Issue by DizzyDJW** [P3pp3rF1y/Reliquary#393]
Allow Void Tears to continue to suck up items in the same container as themselves. I have a vacuum chest that sucks up certain blocks and I'd love it if the void tear could continue sucking the items into itself while in the inventory.

**Comment by P3pp3rF1y** [comment]
There's no way this can be done without some pretty extensive logic which would hack into vanilla chests and wouldn't work with modded inventories anyway so I am not going to add this one.
