### ISSUE TITLE
Bug with Rending Gale and Infernal Tear

### ISSUE THREAD

**Issue by GatoLeyo** [P3pp3rF1y/Reliquary#394]
I'm not really sure how this happen or how to recreate it but I crafted an Infernal tear and it burnt some items as usual but after some uses it stopped working (Im not able to put it on burning mode anymore) I was try right, left, shift right and shift left click and nothing could activate it again, then by some reason this affected my Rending Gale since I'm not able to put it on lightning mode anymore and the weirdest thing of all is that it if I open a new world the Infernal tear and Rending Gale are having the same issue. Any ideas?

Edit:
I'm in the 1.12.2 and using the last version of the mod.
Also I have a lot of mods, I can share them if necessary

**Comment by P3pp3rF1y** [comment]
Lightning mode on rending gale will only activate during thunderstorm. regarding the other stuff I have no idea how that could have happened and would definitely need steps to recreate and limit the mods to just those absolutely necessary to recreate the issues. 
I don't really have time to debug big modpack and figure out what mod may be causing this.

**Comment by P3pp3rF1y** [comment]
Closing as there hasn't been any additional info on how to recreate
