### ISSUE TITLE
Tome of Alkahestry recipes not visible in JEI when potion config is true

### ISSUE THREAD

**Issue by Goldenlion5648** [P3pp3rF1y/Reliquary#397]
after loading the jsons that were shown in the examples, these recipes do not show in JEI. The recipes work, they just aren't visible in JEI

**Comment by P3pp3rF1y** [comment]
What kind of jsons are you loading and in what way? And what examples do you mean actually?

**Comment by Goldenlion5648** [comment]
I used the jsons in resources/alkahestry on this github and put them in the config/xreliquary/alkahestry_overrides folder as shown here
![image](https://user-images.githubusercontent.com/32916571/74578199-2a667080-4f61-11ea-9935-4167ce8d1152.png)

here is the glowstone.json file that was under charging on this github 
![image](https://user-images.githubusercontent.com/32916571/74578268-a365c800-4f61-11ea-8acb-cac424a994dd.png)

**Comment by Goldenlion5648** [comment]
Even after deleting the alkestry_overrides folder, the default recipes still don't show in JEI, but they work

**Comment by Goldenlion5648** [comment]
I finally solved it!
For some reason the tome duping recipes are not visible in JEI when the potion config is set to true "# Disable the potion system including mortar, altar, potions, tipped arrows, and powder
        B:potion=true"

**Comment by P3pp3rF1y** [comment]
So I have tried this and they do work for me correctly so I am guessing that it has something to do with the modpack you have there. Also potion system is enabled by default so that would be fairly easy to spot for pretty much anyone. If you are actually able to recreate this with just Reliquary only or if you can figure out which mod causes this let me know.

**Comment by Goldenlion5648** [comment]
The whole thing about the recipes not showing when the potion config is set to true does happen with only reliquary.

**Comment by P3pp3rF1y** [comment]
Well, I am not sure what to say about that. I have latest versions of reliquary and jei and potion system turned on and all of pressing 'R' or 'U' or left or right click on the tome will get me tabs with crafting and charging recipes for tome. Are you sure you don't have any additional mods in your modpack? And are you running on Forge in SSP or you have something like sponger running or similar?

**Comment by Goldenlion5648** [comment]
I meant when the potion system is set to false then the tome recipes don't show in JEI, but they still work. It seems like the potion system config should not affect the tome

**Comment by P3pp3rF1y** [comment]
In 1.16.5 I have this completely reworked so there no longer should be relation between potion recipes and seeing tome recipes in JEI. will be released soon

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
