### ISSUE TITLE
The Hunter's Handgun is displayed far too big on player's back, using iChun's Backtools mod

### ISSUE THREAD

**Issue by BugmanBugman** [P3pp3rF1y/Reliquary#399]
![2020-03-14_23 29 48](https://user-images.githubusercontent.com/40730042/76695322-ecd23180-664b-11ea-9ce0-3664b5419980.png)

https://www.curseforge.com/minecraft/mc-mods/back-tools

**Comment by P3pp3rF1y** [comment]
You will need to go with this to iChun, the mod doesn't seem to use one of the standard item transformations and thus the gun renders this big. if it used for example transformation for GUI as a base or for item frames it would display alright. But there's nothing I can do on my end and there doesn't seem to any compatibility that can be implemented either, the only thing I can change is the rotation of the gun.
