### ISSUE TITLE
Several mob drop ingredient textures mixed up

### ISSUE THREAD

**Issue by Febilian** [P3pp3rF1y/Reliquary#40]
For example the chelicerae item has the texture of the rib bone(which makes it look identical to the rib bone at a glance), while the withered rib has the intended chelicerae texture, and the actual withered rib texture is nowhere to be found. All the other textures seem to be intact and in the correct places so far from what I can tell.

**Comment by meepmeep22** [comment]
The update to 1.8 for this mod is still in alpha/beta, Some things will be messed up, P3pp3rf1y will repair this soon.

**Comment by P3pp3rF1y** [comment]
My bad/copy paste error - haven't updated the chelicerae json file with correct texture and thus it pointed to the default rib bone and somehow messed up the meta number in the withered rib bone and updated it with 2 instead of 1.

Fixed now, coming up in fixed build on curseforge shortly

**Comment by P3pp3rF1y** [comment]
BTW, if you see anything else please log it here, I am happy to see people playing with the mod and thus want to keep the release version as bug free as possible.
