### ISSUE TITLE
your thing is broken

### ISSUE THREAD

**Issue by fireman55-max** [P3pp3rF1y/Reliquary#400]
ok so.. you see, 1 emerald makes enough red stone for 3 emeralds

**Comment by P3pp3rF1y** [comment]
I am guessing you mean Tome of Alkahestry and no there is no way in either vanilla or reliquary to get 96 redstone that's required to exchange for 3 emeralds.

And second I would like you to stop wasting time of mod developers by creating pretty much hate issues that have no info whatsoever. If you really want to help you need to include way more, like to begin with what you are actually talking about and what version of the mod you have
