### ISSUE TITLE
[1.15] Empty Void Tear crashes when right clicking on a block

### ISSUE THREAD

**Issue by jeremiahwinsley** [P3pp3rF1y/Reliquary#401]
Only happens with an empty tear in SSP. Seems to happen with both empty and filled tears in SMP, but I haven't tested that with only Reliquary installed.

SSP with only Reliquary: [crash-2020-04-06_18.29.46-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/4441258/crash-2020-04-06_18.29.46-client.txt)

SMP with other mods: [crash-2020-04-06_19.29.14-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/4441280/crash-2020-04-06_19.29.14-client.txt)

**Comment by P3pp3rF1y** [comment]
the fix for these issues is now released
