### ISSUE TITLE
Hunter's Handgun causing render errors when used with shaders

### ISSUE THREAD

**Issue by BugmanBugman** [P3pp3rF1y/Reliquary#404]
Version: Reliquary-1.12.2-1.3.4.796.jar
Shaders: Sildur's Vibrant shaders v1.27 Lite
![2020-04-08_15 17 26](https://user-images.githubusercontent.com/40730042/78838801-8fb46c00-79bc-11ea-81fb-0ec1db12f720.png)
![2020-04-08_15 17 24](https://user-images.githubusercontent.com/40730042/78838802-904d0280-79bc-11ea-803b-43006b80cbf5.png)
as you can see, the entire world goes black for some reason

**Comment by P3pp3rF1y** [comment]
There is no special rendering for the gun it's just a regular json model. The only thing I can think of is that it actually is a bit bigger kind of model that then gets scaled down using models display properties and my guess is that the shaders for some reason render the world around you as if you were inside the bigger gun model? But actually it's not that big either as things like pressure plates and show layer use the same scale.
There isn't anything I can do about that and will need to be looked into by optifine or shaders author.
