### ISSUE TITLE
[1.14.4] Server Console Spam: Supplier should not return null value

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/Reliquary#406]
Getting the following message on a fresh server: https://pastebin.com/f8jAfNdZ

The pack I'm using: https://www.curseforge.com/minecraft/modpacks/breath-of-the-wylde
Reliquary version: 1.3.4.947

Thanks for any help you can provide on this.

**Comment by P3pp3rF1y** [comment]
Yup I have fixed this one in 1.15.2 already so I will just need to get the same fix into 1.14.4 together with some additional stuff. Should be out there in a week or so.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release.
