### ISSUE TITLE
Reliquary v1.3 for Minecraft 1.7.10 lily pads of fertility 

### ISSUE THREAD

**Issue by elanvital123** [P3pp3rF1y/Reliquary#407]
I am using a modpack for Minecraft 1.7.10 and the lily pads of fertility do not seem to work on any crops

**Comment by P3pp3rF1y** [comment]
So 1.7.10 version hasn’t been supported for about 4 years now given that there are way newer versions of mc. 
But I am pretty sure lilypads worked in that version so its either the modpack causing it or you just simply expect too much from them - they will speed up growth but it’s not very fast speed up so for example single lilypad probably wouldn’t even make it noticeable if you’re waiting there to see the speed, best way to know they are working is have them cover just part of the field and then you will see that the part will get mature crops earlier than the other. Also multiple lilypads stack in speed.
