### ISSUE TITLE
[1.14.4] Reliquary Client Crash whilst scrolling through JEI. (Curios?)

### ISSUE THREAD

**Issue by Gbergz** [P3pp3rF1y/Reliquary#408]
Title^ (something with Curios?)

Reliquary Version: 1.3.4.947
JEI Version: 6.0.0.27
Forge Version: 28.2.3
MC Version: 1.14.4

Crash-Report: [https://gist.github.com/Gbergz/10ede737cd76232c1b61a82671f22331](https://gist.github.com/Gbergz/10ede737cd76232c1b61a82671f22331)

More Info: As far as I can tell it's crashing every time I try to browse in JEI so it's a repeatable crash.

Any ideas?
- Gbergz

EDIT: Realized this might've already been reported, excuse me if it has.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
