### ISSUE TITLE
Infernal Chalice and Pyromancer's Staff uncraftable

### ISSUE THREAD

**Issue by Febilian** [P3pp3rF1y/Reliquary#41]
Simply because there is no apparent recipe for the Infernal Tear (WIP) item that they require in their recipes(at least as far as JEI is concerned!). Since it's a WIP item in of itself you probably already know that, but a note somewhere regarding that it and its derivative items are not possible to get legitimately for the time being might be nice.

EDIT: Oops, I forgot to say that those aren't the only two items uncraftable because of this, it's just the first page from JEI... Hero's Medallion and Destruction Catalyst are also unobtainable as one might expect.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. The only reason I have left infernal tear in was to allow for crafting the items that require it in their recipes, but obviously I have missed out that its recipe isn't included thus making it pointless.

It is fixed now and there should be a new release build on curseforge shortly.
