### ISSUE TITLE
[1.15.2] [Compat] A player is not provided for the DirectionalPlaceContext used by the LanternOfParanoia

### ISSUE THREAD

**Issue by Laikulo** [P3pp3rF1y/Reliquary#410]
This can result in a crash whenever a mod tries to check something about the player (sneaking, creative mod, etc) and doesn't check for nulls.

While it would be nice if everyone checked for nulls, it might be a good idea to pass the player along, especially for mods that care about who is placing something.

Related issue: https://github.com/jaquadro/StorageDrawers/issues/820

This function:
https://github.com/P3pp3rF1y/Reliquary/blob/b128b3821fda515dadd31a9ae9c964516c16026f/src/main/java/xreliquary/items/LanternOfParanoiaItem.java#L52-L74

**Comment by P3pp3rF1y** [comment]
Well, this is not an easy thing to do - either recalculate placement direction and position to a placement vector or implement a completely new class that's like DirectionalPlaceContext with player passed in. And at the same time getPlayer() of PlacementContext is defined as Nullable so mods absolutely have to be ready for it to be null, there are also implementations in vanilla that use DirectionalPlaceContext so they will return null as well. I will keep this around for a bit if I decide to add something additional in Reliquary, but at this point I am leaning towards just leaving it the way it is.

**Comment by Laikulo** [comment]
Ah, for some reason I thought DirectionalPlaceContext already had that. I've been out of the game for a bit, so I'm a bit rusty on what has what.

As far as this specific interaction, I've opened a PR against Storage Drawers to add a null check, and am currently using that modded mod. I'll look around and see if I spot an easier solution.

**Comment by P3pp3rF1y** [comment]
closing this as it needs to be solved on storage drawers side
