### ISSUE TITLE
1.15.2 Charm Belt Not Craftable

### ISSUE THREAD

**Issue by FallenEagle1** [P3pp3rF1y/Reliquary#412]
Forge Version: 31.1.36
Reliquary Version: 1.15.2-1.3.4.960

Quick crafting bug where the Charm belt is not craftable. The craft shows 3 leather and 5 pig charm fragments to craft.

Looking at nbt tags, it almost looks like the craft is looking for the fragments to not have any nbt tags, instead of ignoring nbt tags in general.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release.
