### ISSUE TITLE
[1.14.4] Rending gale (at least) "capability"/"charge" loss when changing dimensions

### ISSUE THREAD

**Issue by noobanidus** [P3pp3rF1y/Reliquary#413]
I noticed after using a Waystone from the Waystones mod that, while I got the initial flight out of my Rending Gale (and it showed 232 as the charge), it suddenly stopped and displayed 0 as the charge.

I know this is incorrect as it happened previously when I was demonstrating it to someone, and I thought that I'd just used it up, and had only an hour ago recharged it fully with feathers.

In the intervening time I had used a Waystone to get to the End, and then the server had restarted. Logging back in showed full charge on the Rending Gale, but when I used it to fly up in the end, it suddenly showed no charge.

I know that there are issues with items losing capabilities and information when changing dimensions, and I'm wondering if this is perhaps related.

**Comment by noobanidus** [comment]
EDIT: In addition, this did *not* happen when I returned from the end.

EDIT 2: Nor when I returned to the end via another Waystone.

I'm now wondering if it's specifically related to the server restart. Unfortunately, I don't seem to be able to replicate it now.

**Comment by P3pp3rF1y** [comment]
if the server restart didn't save the capability data properly that would be related, but it should be happening during regular world save. I will keep this open for a bit if you happen to replicate the issue.

**Comment by noobanidus** [comment]
Thanks! I'll try to get back to you with more information. The only reason I filed the issue in the first place is that it happened twice in a row within a short period of time, but I don't think I have enough information at this point.

**Comment by noobanidus** [comment]
This does seem to be happening inconsistently on server restart. I have the correct display of the number of feathers locally, but once I attempt flight it immediately resets to zero. I don't seem to be able to replicate it with regularity though, nor rule out cross-mod interaciton.

**Comment by P3pp3rF1y** [comment]
closing this, I am no longer supporting 1.14 version and in addition to no additional leads I am not hearing about this issue from anyone else.
