### ISSUE TITLE
[1.15.2][Suggestion] Pedestal with Shears should harvest Beehive/Bee Nest

### ISSUE THREAD

**Issue by jeremiahwinsley** [P3pp3rF1y/Reliquary#418]
The vanilla (and mods like Buzzier Bees) Bee Nest and Beehive can be sheared when full to produce honey combs, but they do not currently work with the pedestal.

**Comment by GrokDuckFarmer** [comment]
Love this idea.  Since it is a vanilla mechanic, it would be great to enable this with shears, or even with just the Shears of Winter to make it a little bit harder to do.

**Comment by P3pp3rF1y** [comment]
this is now added in dev of 1.16.5 version. even regular shears work but those will get damaged by this use while shears of winter don't

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
