### ISSUE TITLE
[1.15.2] Pedestal+Harverster

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#419]
Setting up a pedestal+harvester farm causes crashes the game.
First, It happens when trying to insert seeds into Pedestal+Harverster (by using hoppers or modded options, crash repeated with botania and mekanism). Inserting only bone meal does not cause crash, nor does inserting items into another pedestal combo (void tear, flying rod). The issue appears to involve only the second inventory slot accessed or the harvester in specific.
It is repeatable. Tested with ~100 mods and then this mod alone (a few times, new worlds). Tested with forge versions 31.1.48 and 31.1.0 (using multimc on linux). 
Older version of the mod does not crash when inserting seeds, but then it does crash when the inventory goes to zero as mentioned on solved #414.
In addition, Harvester sometimes spawn bonemeal out of no where when empty and put into pedestal. This may be related to the crash.
Lastly, the pedestal is instantly destroyed by an empty hand. A pickaxe does harvest the block tho, but it pops too fast.

Crash (only Reliquary loaded): [crash-2020-04-23_15.06.14-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/4526968/crash-2020-04-23_15.06.14-server.txt)

**Comment by P3pp3rF1y** [comment]
this is fixed int the latest release

**Comment by ghost** [comment]
Thank you! The crash is no more.
I tested the new released and i couldn't repeat it. However,  the bonemeal/seed counter is still weird.

I was rather confused at first, but I finally got to consistently repeat it. I hope the text isn't too confusing tho. 
If I have seeds in the harvester but no bonemeal (or i had it there but was used up), when I remove the rod the X seeds transforms into X bone meal. Once the bug is done, I couldn't remove the bone meal, but I could use it. The seeds are deleted but the number (X) stays displayed until I insert a new seed and the counter resets to include only the new seeds.

0 bm | X ws -> remove rod from pedestal -> X bm | X ws (none can be removed, only bm can be used) -> insert N wheat seeds ->  X bm | N ws. 

Also, was the change on the speed to break the pedestal a design choice? I don't remember it breaking with only one punch on survival before. It isn't particularly game breaking, but I found it quite easy to lose the pedestal if not carefully pre-selecting the right tool. May I suggest to increase its "hardness"? (i am not sure what its called)

Anyway, thank you for the fast fix!

**Comment by P3pp3rF1y** [comment]
Thanks for coming back with that comment. I have fixed both the harvester as well as the pedestal hardness issues in the latest releases for 1.15.2 and 1.14.4.

Just for future reference please report these issues as a new bug as I may not check comments for closed issues all the time and wouldn't want the issues to not be resolved just because of that especially when you invest your time in reporting them.

**Comment by ghost** [comment]
I saw it going live on curseforge and finished testing it. Everything is working now, thank you!
Alright, I will keep that in mind for when and if I find anything else. I didn't really know which would be the best way, I didn't want you to miss it, but I also didn't want to sound like a parrot opening too many issues.
