### ISSUE TITLE
[1.14.4] Frozen Cores do not seem to drop

### ISSUE THREAD

**Issue by noobanidus** [P3pp3rF1y/Reliquary#425]
This appears to be confirmed by JER not listing any sources for Frozen Cores (while other drops all have sources listed), and the fact that I creatively tested a stack or two of snow golem spawn eggs with a looting sword and only got snowballs.

I can't rule out that this isn't a cross-mod interaction of some description however. I'm not sure what method you're using to inject loot and it's possible that there's an issue with the null-pool-name addition that plagued grass injection for a long while -- potentially caused by another mod. I'll try to dig through the server logs to see if there's anything of note.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this. Apparently the loot table name has changed from snowman to snow_golem so I had to fix that. Now the frozen cores drop correctly. New version is on CF, should be approved shortly.

**Comment by noobanidus** [comment]
Awesome, thank you!
