### ISSUE TITLE
[Reliquary-1.14.4-1.3.4.969] Charm Belt not crafting

### ISSUE THREAD

**Issue by DWX12** [P3pp3rF1y/Reliquary#428]
Trying to craft a charm belt with Reliquary-1.14.4-1.3.4.969 and I can look up the recipe and the recipe shows up along with being able to place the ingredients into the crafting grid, but there is no output. I tried placing a few different types of charm fragments, but none seem to work.

Also, I see pig charms listed in the recipes through JEI, but I don't see any pig charm fragments. Are they for testing purposes only?

Let me know if you need any further information.

Thank you for this great mod.

**Comment by P3pp3rF1y** [comment]
This was fixed in newer version of Reliquary for 1.14.4. Just download a new version from curseforge.
