### ISSUE TITLE
Request: Infernal Tear override configs

### ISSUE THREAD

**Issue by TheDaftWizard** [P3pp3rF1y/Reliquary#429]
I'm trying to balance my 1.12.2 modpack and I'm finding that it's incredibly easy to abuse the Infernal Tear to get OBSCENE amounts of EXP with ingots. Because of the nature of my modpack I want to keep exp more or less regulated.

I looked into the configs and found absolutely nothing that could help me other than that the tear is tied to the Tome of Alkahestry values. src/main/java/xreliquary/items/ItemInfernalTear.java says this:

		if(!(recipe.getRecipeOutput().getCount() == 33 && recipe.getChargeNeeded() == 4)) {
			if(InventoryHelper.consumeItem(this.getStackFromTear(ist), player)) {
				player.addExperience((int) (Math.ceil((((double) recipe.getChargeNeeded()) / (double) (recipe.getRecipeOutput().getCount() - 1)) / 256d * 500d)));
			}

With some in-game testing and double-checking my math, it looks like the important part is the `2*(redstone cost) / (2*(gain - 1))`. The math just doesn't seem fair in my opinion, because this means a piece of obsidian will give only 4 exp, whereas a single iron ingot gives 64, which is above level 5. A stack of tin ingots puts me well above level 40. I like how expensive it is to copy ingots, but the obscene amount of EXP you can get from having an abundance of ingots is problematic for me. Currently my only solutions are to either remove the Tome's ability to copy ingots, or make ingots so much cheaper to copy that mining becomes inefficient in comparison.

I'd like to be able to either set the burnable items & exp values independently of the Tome's values, or disable certain items from being burnable entirely. Preferably the former, as it would be nice to set a particular "theme" of items that are burnable VS clonable. I imagine it could be done in a way similar to how Alkahestry Overrides are handled, with an extra folder? Either way, hopefully you're still supporting the 1.12.2 version. Thanks!

**Comment by P3pp3rF1y** [comment]
I am not updating 1.12.2 anymore, but in dev version of 1.16.5 has a separate configuration for infernal tear for mapping items to experience

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
