### ISSUE TITLE
altar of light not working

### ISSUE THREAD

**Issue by LocoMinerDad** [P3pp3rF1y/Reliquary#430]
Minecraft 15.2
forged 31.2.0
mod version .995 and .991
changed config to make it glowstone  in one minute as part of troubleshooting, random add time also one minute
issue: I add three glowstone and altar symbol changes, no particles appear. I waited a whole minecraft day, nothing happened.  The next day I used the command time set day and the altar started working instantly. The following day it did not work. I used time set command again and it worked. It only appears to work when I set time to day. Its like it cant till if its day or night.

please fix.

**Comment by Geethebluesky** [comment]
Is your Altar indoors, or does it have blocks above it?

I ran into the same issue a long time ago, under #326, it was me not understanding the Altar is meant to be outside with only sky above it.

**Comment by P3pp3rF1y** [comment]
The altar needs to only have air blocks above (see the sky) and will only work during the day as indicated by particles going from it.
