### ISSUE TITLE
Hunter's Handgun Slow Rate of Fire

### ISSUE THREAD

**Issue by squidinkspaghetti** [P3pp3rF1y/Reliquary#431]
The Hunter's Handgun's rate of fire is extremely slow. While holding down my right click, it fires at about one shot per second, about the time it takes for the muzzle flare to fade. The attack animation repeatedly takes place but no shots will fire until the muzzle flare is gone.
I'm posting this as an issue because at one point it was firing at a much quicker rate. I updated to the latest release, Reliquary-1.15.2-1.3.4.995, and it now fires much more slowly.
I tried running MC with only this mod installed and was able to replicate the issue in doing so.
I checked the config options but don't see anything concerning modifying rate of fire or reload.
If I'm missing something or there's a quick fix, I'm happy to fiddle with values. I just need you to point me in the right direction.

**Comment by P3pp3rF1y** [comment]
Rate of fire is dependent on number of experience levels you have. The more you do the faster. it's the fastest at level 20 or more. I am closing this, but if that still doesn't work for you let me know
