### ISSUE TITLE
looting

### ISSUE THREAD

**Issue by benbenlaw** [P3pp3rF1y/Reliquary#432]
any sort of looting cause mobs to drop huge amounts of reliquary items

enchant with looting = Profit

**Comment by P3pp3rF1y** [comment]
Can you define what looting level you have and what means huge amounts of reliquary items per mob? 
And is this with just Reliquary in the pack? 

I just fail to see how something that's about 1 in 10 chance to drop without looting and with looting multiplier that gets it to about 1 in 4 chance with looting III could get you "huge amount of drops".

And it would also help if you shared which version of Reliquary that is.

**Comment by P3pp3rF1y** [comment]
And just saw your other issue open for ATM 5 and retested with just Reliquary and definitely getting expected amount of drops - 1 in 4 with looting III. Closing
