### ISSUE TITLE
[Suggestion] Some Void Tear tweaks.

### ISSUE THREAD

**Issue by TheUnderTaker11** [P3pp3rF1y/Reliquary#434]
As it currently stands, the void tear is unwieldy to use. But a few simply changes could really help with that.
1. Add a mode that DOESN'T leave 1 stack in the inventory at all times, but still absorbs.
2. Give feedback in chat on what mode the player is now on (So shift right click to go between the now 3 modes, and chat will tell you what current mode you are on, as well as the tooltip)
3. Make the stack it puts in your inventory prioritize the reverse slot, or at least have a config option for it. When I want to move a stack from my hotbar to my normal inventory, it is impossible without shift clicking.
4. Have the void tear check the item you are holding in your mouse. When I pick up a stack it shouldn't immediately put a new one in the inventory, cause I just wanted to move the stack somewhere else in my inventory.

**Comment by P3pp3rF1y** [comment]
What version are you actually speaking of? 
Because 1.12, 1.14, 1.15 all have mode that absorbs without leaving stack in the inventory and they display current settings of the tear in the GUI.
I will take a look at the remaining two,

**Comment by TheUnderTaker11** [comment]
Well there is no gui besides the tooltip, and there is no way described
ANYWHERE on how to change to it a mode that doesn't leave a stack.

The wiki needs to be edited to tell me how to cause no combination of right-click + shift will ever get it to this mode.

**Comment by TheUnderTaker11** [comment]
And I am in 1.14.4, sorry I forgot to mention that.

**Comment by TheUnderTaker11** [comment]
And I was randomly right clicking and shit and somehow got it to be in the mode that doesn't leave a stack.
And the fact the GUI tells you that is simply not true.

And for the in chat indication, the reason is so that you don't have to open your inventory every single mode change to know what mode you are in, even if it did actually tell you the mode.

![image](https://user-images.githubusercontent.com/16872377/83445943-80c5c500-a413-11ea-97ef-a0e9fb7f27fe.png)

**Comment by P3pp3rF1y** [comment]
So you don't get this in your GUI? (this is screenshot from 1.14.4) Shows you both info about contents of the void tear as well as the mode and the mode switching is the same as for all the other tools that have multiple modes (shift - leftclick). But I guess a comment about that in void tear's tooltip would make sense anyway.
![image](https://user-images.githubusercontent.com/2079526/83452405-edaf7e00-a458-11ea-9120-89342f5bf815.png)

**Comment by TheUnderTaker11** [comment]
Shift Left click, okay, yea that needs to be written somewhere to know it's even an option.

And that GUI does show up, I just didn't notice it.

**Comment by P3pp3rF1y** [comment]
1.16.5 dev version now has a bit more descriptive tooltip

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
