### ISSUE TITLE
[Suggestion] Make Coin of Fortune keybind say in chat if it was just enabled/disabled.

### ISSUE THREAD

**Issue by TheUnderTaker11** [P3pp3rF1y/Reliquary#435]
This will be a super simple quality of life change. Just make it tell you in chat if you just enabled or disabled the magnet.

(Or a more difficult option would be doing something like this. The tool mode message pops up for a bit then fades away.)
![image](https://user-images.githubusercontent.com/16872377/83446473-59bbc300-a414-11ea-886e-6b0ee19a5031.png)

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
