### ISSUE TITLE
Game crashes when trying to enter the Midnight dimension

### ISSUE THREAD

**Issue by SpencerMeow** [P3pp3rF1y/Reliquary#437]
Heres the log 
[crash-2020-06-07_11.37.52-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/4742497/crash-2020-06-07_11.37.52-client.txt)

**Comment by P3pp3rF1y** [comment]
To be honest I am not sure what's happening for you. I have tried entering midnight with no crashes and where it crashes for you is a place where it shouldn't be happening unless something was changed. so the only thing I can suspect is that one of the core mods you have in the pack makes a change there that's incompatible with other mods. I am going to close but if you happen to recreate with just midnight and Reliquary feel free to reopen.
