### ISSUE TITLE
[1.14.4] Drinking condensed potions gives you a null/generic undrinkable generic potion instead of an empty vial

### ISSUE THREAD

**Issue by optionboom** [P3pp3rF1y/Reliquary#438]
Drinking any condensed potion gives the player a white condensed potion with no effects while in survival. I assume they're instead supposed to give an empty vial.

**Comment by optionboom** [comment]
I'm not proficient with Eclipse or Forge so I wasn't able to figure how to make the change myself, but it seems to be simply because PotionItem creates a new Potion with no nbt data on use, instead of just creating an empty_potion_vial, which is a different item.

Also, from the looks of it this also happens in 1.15.

**Comment by MFernflower** [comment]
I can confirm this happens in 1.15

**Comment by P3pp3rF1y** [comment]
Fixed in latest version.
