### ISSUE TITLE
Crash on Crafting Holy Hand Grenades

### ISSUE THREAD

**Issue by SilentChaos512** [P3pp3rF1y/Reliquary#44]
Getting a crash when crafting Holy Hand Grenades. It seems that there is some ItemStack that is returning null from getItem(). A user of one of my mods posted the issue on my GitHub (link to issue below) because one of my recipe handlers was in the stack trace. After adding some null checks to my mod, the game still crashes, just in a different place.

Here's my latest crash report: http://pastebin.com/iifp3k0z
Original issue (includes link to crash report I was given): https://github.com/SilentChaos512/SilentGems/issues/12

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. The reason is condensed potion that gets returned as a byproduct. Didn't have that included in this release and didn't realize it gets returned anywhere.
Now added and should be in a fixed build shortly.
