### ISSUE TITLE
[1.14.4] Charm belt recipe asks for unobtainable "Pig Charm Fragment"

### ISSUE THREAD

**Issue by Bindsome** [P3pp3rF1y/Reliquary#440]
![image](https://user-images.githubusercontent.com/67029894/84837674-88799200-afed-11ea-9e0d-517538b1502e.png)

**Comment by P3pp3rF1y** [comment]
Just update to the latest version of the mod which has the fix for this - you can use any fragment in the belt recipe and latest version shows that correctly in JEI
