### ISSUE TITLE
Recipe's Not working/Vials Cant fill

### ISSUE THREAD

**Issue by Rieze1** [P3pp3rF1y/Reliquary#441]
Recently Added this mod to my game & find that most of the recipe's dont allow me to craft the items at all & the Condensed vials cannot be filled with water at all.

**Comment by P3pp3rF1y** [comment]
So I have no idea what you're talking about here. No idea what version of the mod it is and as far as I can see recipes work correctly in 1.12.2, 1.14 and 1.15. Also why do you think you should be able to fill condensed vial with water?

**Comment by Rieze1** [comment]
Umm then how to i get a filled vial? and as to recipes not working, I notice with all mods i use, I need to craft the item before it shows in my table, but When I tried to craft ur items the only ones that gave me something to obtain were the vials and a few other items & im on 1.15.2

________________________________

**Comment by P3pp3rF1y** [comment]
Vials are filled with potion from apothecary cauldron (check JEI for recipes) and I have no idea what your issue with recipes is. it's likely an interaction with another mod as it definitely works correctly with just Reliquary and Reliquary mostly uses standard recipes the same ones that vanilla does so I am going to close. If you actually are able to recreate that issue with just reliquary feel free to reopen, but please include specifics on what exact item you're trying to craft and what recipe you tried that didn't work.

**Comment by Rieze1** [comment]
I think I might know the problem I was having, Do you need JEI to use your mod properly, cause i dont have JEI.

________________________________
