### ISSUE TITLE
Wrong JEI Recipe For Bullets With Effects

### ISSUE THREAD

**Issue by ChrisLTheNerd** [P3pp3rF1y/Reliquary#442]
The JEI recipe guide is showing the wrong recipe for bullets with effects. 

JEI is showing that the Lingering Condensed Potion belongs on the bottom left 
![2020-06-21_14 55 13](https://user-images.githubusercontent.com/50182206/85232755-7e7dd780-b3cf-11ea-9d10-06429bc1e119.png)

Instead of showing that it actually belongs in the center
![2020-06-21_14 54 56](https://user-images.githubusercontent.com/50182206/85232801-f946f280-b3cf-11ea-908c-aa4dbf4019d5.png)

**Comment by P3pp3rF1y** [comment]
Not sure what version this was for, but it's fixed in the latest versions of Reliquary
