### ISSUE TITLE
[1.15.2] Shears on a pedestal do not appear to shear sheep

### ISSUE THREAD

**Issue by belathus** [P3pp3rF1y/Reliquary#443]
Running version 1.3.4.995. I've put shears and shears of winter on a pedestal next to sheep and applied a redstone signal (or set the pedestal to ignore a signal). Sheep do not get sheared.

![2020-06-29_08 47 24](https://user-images.githubusercontent.com/3826783/86007364-48e77880-b9e5-11ea-83e6-5a69a2e71993.png)

**Comment by P3pp3rF1y** [comment]
I have just tested this and it works alright for me. I assume you play this in a modpack with other mods, could you try recreating that with just Reliquary?

**Comment by belathus** [comment]
I'll give it a shot.

**Comment by belathus** [comment]
Alright, gave it a shot, and it works just fine with no other mods installed. And now I think I have an idea as to what the cause is. I'll report back.

**Comment by belathus** [comment]
Yeah, it is Minecolonies and it's colony protection. According to them, they seem to believe that the "fake player" is somehow implemented incorrectly? Or maybe I'm misunderstanding.

**Comment by P3pp3rF1y** [comment]
if you can point me to a response from them I can take a look at what they mean by that. Nothing immediately strikes me as incorrectly implemented here

**Comment by P3pp3rF1y** [comment]
closing as there's nothing I can do here without any further info and that info hasn't been provided for a while now and I can't find it in minecolonies issue tracker or discord either
