### ISSUE TITLE
[1.15.2] Lantern Of Paranoia crashes game with Storage Drawers

### ISSUE THREAD

**Issue by BeastgameTL** [P3pp3rF1y/Reliquary#445]
The Lantern Of Paranoia crashed minecraft when checking if the storage drawer at a potential torch position is replacable.

Crash Report: https://pastebin.com/mhuMW5SE

**Comment by Shados** [comment]
Can confirm, have seen the same issue on my server. Amusingly, it doesn't actually crash the server, but it does result in kicking the player causing it off, repeatedly. Fixing requires editing their player data to either move them away from the drawers or remove the lantern from their inventory.

**Comment by P3pp3rF1y** [comment]
well, this is actually storage drawers relying on player being passed in there even though it doesn't need to be. I may have a way to fix that, but it won't fix any other mod not passing player even though mods don't need to. Proper fix needs to be done on storage drawers side to fix that.

**Comment by P3pp3rF1y** [comment]
The latest version has a code change that prevents the crash with Lantern, but it won't prevent crashes with any other mod that may not be passing player there (like I saw is the case with botania). Storage drawers really need to make the fix to handle that properly.
