### ISSUE TITLE
[v1.3.4.995 for 1.15.2] Altar of Light Doesn't Work

### ISSUE THREAD

**Issue by DerekM07** [P3pp3rF1y/Reliquary#446]
Placed the altar directly under the sky, on the surface.
Hit it with redstone dust via right-click until it lit up.
Waited many days (probably weeks) in-game. Nothing.

**Comment by CastorChernobog** [comment]
I have this exact same issue.

**Comment by P3pp3rF1y** [comment]
Can you actually recreate this with just reliquary? because it works properly for me with that. So I am thinking this is a modpack issue where some other mod improperly interacts with methods that Reliquary uses to figure out that altar is under sky or that it's day at the moment

**Comment by DerekM07** [comment]
I'm running many mods, so that is possible, but I can tell you that none of the mods I have affect the day-night cycle and the daylight detectors in my redstone circuits still work normally--I would assume the altars use the same methods. Very strange.

edit: After considering this further, it occurs to me a difference between the altars and daylight detectors is size (full block vs. slab). So my intuition says it's maybe a mod conflict with either the Torch Slabs mod, Double Slabs mod, or Quark mod. These mods, which affect basic slab functionality, themselves attempt to solve lighting problems (such as when correctly lighting vertical slabs).

**Comment by P3pp3rF1y** [comment]
Closing this as there are no leads here that I could follow to recreate the issue.
