### ISSUE TITLE
Void tear issue with FTB interaction modpack  1.12

### ISSUE THREAD

**Issue by Alonn22** [P3pp3rF1y/Reliquary#447]
Hello - I war trying to make the Rending Gale in FTB Interactions by infusion crafting.  It requires Void Tear but every time I click the Arcane pedestal, the server crashes and game closes down.   Any help to solve the issue would be welcome :)

**Comment by P3pp3rF1y** [comment]
if you can provide the crash log I may be able to figure out what's wrong otherwise I am afraid I can't help with this.

**Comment by P3pp3rF1y** [comment]
without crashlog there's nothing I can do here, so closing, if you can provide it feel free to reopen
