### ISSUE TITLE
No crafting recipe for Tome of Alkahestry

### ISSUE THREAD

**Issue by Febilian** [P3pp3rF1y/Reliquary#46]
Unsure if it's supposed to have one yet anyways, but JEI shows no recipe at all for it. Thought I'd mention it just in case.

**Comment by P3pp3rF1y** [comment]
Yeah, that was my bad leaving the item in. 

Tome in alpha1 actually doesn't work and thus the recipe wasn't included, but I somehow left the item itself in. 
In an upcoming beta release (probably later this week) it will work.

This is pretty low severity issue to me so I am going to close this with the release.
