### ISSUE TITLE
[1.16.3] Crash: Failed to load description for particle 

### ISSUE THREAD

**Issue by Silvrus** [P3pp3rF1y/Reliquary#466]
Minecraft: 1.16.3
Forge: 34.1.32
Reliquary: 1.16.3-1.3.4.1042

A number of mods are crashing due to the Forge update, including Reliquary. Please see log.

https://pastebin.com/r8N8G07u

**Comment by P3pp3rF1y** [comment]
I am afraid that is an issue with your modpack. Very likely one of the many core mods you have there as I was just able to run reliquary in the latest forge without any issue.
![image](https://user-images.githubusercontent.com/2079526/97323742-66343280-1871-11eb-9c0b-ee2c9f1f96a0.png)

**Comment by Silvrus** [comment]
My apologies, you are indeed correct, the fault lies with other mods. Strangely enough, none are core mods, unless I misunderstand that term. The biggest offenders for me was Better Mineshafts, Immersive Engineering and Immersive Portals. Not sure why they're causing the crash report to finger Reliquary (and others), but thanks for taking the time to check, and sorry for wasting said time.

**Comment by P3pp3rF1y** [comment]
no worries, sometimes it's hard to tell which mod actually is the cause especially when core mods get involved.

**Comment by drakray** [comment]
@Silvrus have you found any lead on how to fix that?, I got the same trouble :'(
