### ISSUE TITLE
[1.16.3]Crash with Forge (34.1.35)

### ISSUE THREAD

**Issue by scottctd** [P3pp3rF1y/Reliquary#469]
[Crash Report](https://pastebin.com/MnsaZWvJ)

[Log](https://pastebin.com/CNnAKVfH)

**Comment by Anteater46** [comment]
See #466

**Comment by Anteater46** [comment]
Seems to be a known issue with Immersive Engineering [they have a pinned issue](https://github.com/BluSunrize/ImmersiveEngineering/issues/4410) saying to downgrade Forge until the next version.

**Comment by scottctd** [comment]
Okay, sorry for my carelessness for not check the closed isseus..
