### ISSUE TITLE
The game crashed whilst rendering overlay

### ISSUE THREAD

**Issue by Grant-K** [P3pp3rF1y/Reliquary#470]
Error: java.lang.IllegalStateException: Failed to load description for particle xreliquary:cauldron_steam
Exit Code: -1
On Versions of forge 34.1.25+
Full Crash Log
[crash-2020-11-02_16.24.12-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/5478711/crash-2020-11-02_16.24.12-client.txt)

**Comment by P3pp3rF1y** [comment]
See pinned closed issue #469
