### ISSUE TITLE
[1.15.2] Multiple alkahestry tome charging/duplicating recipes when using a datapack

### ISSUE THREAD

**Issue by IchHabeHunger54** [P3pp3rF1y/Reliquary#482]
I tried to make a glowstone block charge up the alkahestry tome by 9 units instead of 4. I did so by adding a datapack (using Openloader) that overrides the default charging recipes. That worked, but now I am seeing every charging recipe two times (with the glowstone block charging 9 units both times).

Also, I decided to make red sand dupeable using the alkahestry tome. I did it the same way as above, as I removed two other duplicating recipes and replaced the corresponding file contents with red sand/red sandstone duplicating recipes. Again, I am seeing every recipe two times (including red sand and red sandstone). The only ones I didn't see were the two I replaced.

On top of that, every time I do /reload, the recipes just add themselves, instead of replacing the already registered recipes. So I suppose that the issue might be in your recipe registry.

Forge 1.15.2-31.2.45
Reliquary 1.3.4.995

**Comment by P3pp3rF1y** [comment]
Probably a little late for you but I have this fixed in 1.16.5 dev version now - there was a problem with registry of alkahestry recipes that I keep on a side for performance reasons that it wasn't ready for reloads and data pack overrides of recipes. this is now fixed there.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
