### ISSUE TITLE
Crash tring to use the harvest rod

### ISSUE THREAD

**Issue by aburone** [P3pp3rF1y/Reliquary#483]
I've found a Pam's Lemon tree and was trying to use the staff to grow one tree. While I failed to do so I started shift -right clicking (I still don't understand the rod mechanic), that's when the game crashed.
Upon inspection. The staff had charges of "air" I believe those where some seeds from a mod I removed, hence the rod had some unknown items
I can reproduce the crash consistently If you need something from me to test.
Thanks
PS: I love the Rending Gale
mc 1.16.4
reliquary-1.16.3-1.3.4.1061.jar

[crash-2020-12-07_08.51.12-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/5652471/crash-2020-12-07_08.51.12-server.txt)

**Comment by P3pp3rF1y** [comment]
I have added a bit of code which will remove any invalid plantable items from the harvest rod when a mod is removed, but removal of mod is not really a common scenario and mod devs can't always super proof against that and the code that checks for something like that happening also brings a bit of performance degradation as additional checks need to be done in addition to the item's logic.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
