### ISSUE TITLE
Tome of Alkahestry not duping

### ISSUE THREAD

**Issue by SenCarryr** [P3pp3rF1y/Reliquary#484]
Unsure if it needs full charge or is incompatible with podzol, has about 4 or 5 stacks of redstone charge.

**Comment by SenCarryr** [comment]
Did some testing, does not work on podzol, works on other listed items

**Comment by P3pp3rF1y** [comment]
well not sure where you got the info on podzol but that doesn't seem to have ever been in as a recipe at least not by default. So must have been your modpack adding it.
