### ISSUE TITLE
1.16 Phantom Charm

### ISSUE THREAD

**Issue by jinkhya** [P3pp3rF1y/Reliquary#485]
Hello,
I saw there is a phantom charm and I'd love to craft it however the recipe uses phantom charm fragments and those don't have a recipe. Is there a specific way to get them or they're not implemented yet?
Thanks in advance,
Jin

**Comment by P3pp3rF1y** [comment]
It drops from phantoms. unfortunately just yesterday I found there was an issue in calculation of the chance which made it super small (0 chance without looting, and something like 1/200 with looting 1). this is fixed in dev and will be released soon

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
