### ISSUE TITLE
Alkahestry Tome

### ISSUE THREAD

**Issue by bschallitz** [P3pp3rF1y/Reliquary#486]
NEI isn't giving me a recipe for it, and when I use the recipe for post 1.7 reliquary on the wiki page, it doesnt work

**Comment by P3pp3rF1y** [comment]
well, not sure what version you're running when you refer to NEI. JEI is what we use these days (since 1.8) and the recipe should be there unless alkahestry is turned off. I can for sure see the recipe correctly
