### ISSUE TITLE
Visual Bug when placing pedestal (display) atop an Astral Sorcery pillar.

### ISSUE THREAD

**Issue by SlyScroll** [P3pp3rF1y/Reliquary#487]
At the gaps in the base of the pedestal, the top face of the astral pillar (one tile high varient) becomes invisible.

![image](https://user-images.githubusercontent.com/14237643/101993257-fce97100-3cb0-11eb-8f60-f2fd942beaaf.png)

**Comment by P3pp3rF1y** [comment]
You will need to report this to astral as that is an issue with their block not rendering whent there's a non full block above it.

**Comment by SlyScroll** [comment]
@P3pp3rF1y I reported this as an issue in Astral's github and they bounced me right back here saying:

> Their Bounding box is set up that it's filling the entire 12x12 box on the bottom, thus minecraft's rendering presumes that the entire area is filled with a solid model, as Reliquary's passive pedestal block is set up to count as a solid.
That's not my issue and nothing i can do about it from my end as it's their block's properties.
