### ISSUE TITLE
witch hat recipe conflict

### ISSUE THREAD

**Issue by Based199** [P3pp3rF1y/Reliquary#488]
witch hat is used to craft redstone, glowstone, and gunpowder but all 3 share the same recipe

**Comment by KikiCur** [comment]
^_^ came to report this same bug

as I understand it the old recipes used to be shaped
with one result from the left most column of the crafting grid having 3 witch hats
another with the middle column filled with 3 hats
and the last with the right most column

I can't recall which was which, sorry

funnily enough, the crafting rat from rat mod can craft all three in the 1.16 Direwolf20 pack

**Comment by Sunekaer** [comment]
@P3pp3rF1y 
This is due to the vanilla recipe shrinking system, Vanilla shrinks recipe patterns to try to optimise them ( removes air ) therefor these 3 recipes become the same input.
Youll have to make another pattern for these

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
