### ISSUE TITLE
Weird behavior on Nylium

### ISSUE THREAD

**Issue by GatoLeyo** [P3pp3rF1y/Reliquary#489]
When using the fertile potion on Nylium it doesn't follow a neat growing pattern, looks like it chooses blocks randomly. Also when you aim the potion to the lateral sides of a block instead of above it doesn't seem to work.
Let me know if this is intended

**Comment by P3pp3rF1y** [comment]
It basically applies bonemeal to all blocks in 3x3x3 box around the block that's hit - 1 block around it, 2 blocks below and one block up. And as far as I can see it works correctly on Nylium even when it hits a side of a block
