### ISSUE TITLE
Old bug persists

### ISSUE THREAD

**Issue by GatoLeyo** [P3pp3rF1y/Reliquary#491]
So i've been far away from minecraft in general for a while but now im back and by some reason (i don't know how it is even possible) an old bug persists.
https://github.com/P3pp3rF1y/Reliquary/issues/394
That is the original report, i find out that the rending gale works properly so prolly i wasn't aware of the thunder condition but there are two bugs that are still affecting all my worlds, the bug started on 1.12.2 and now i updated the minecraft to 1.16.4, i erased the old mod version and the config file of the mod but the infernal tear still doesn't work and now the config file does not work as well, whenever i try to change something it remains the same and doesn't even follow the statments established on the default config file. For example the rending gale default capability of feathers is 30000 as default but mine only allows 300 an it stays as 300 doesn't matter what i put on the config file.

i have a lot of mod and i haven't tried to erase and re install everything again (including minecraft ofc) so before i take the effort to do that to see if that solves the problem i would like to know if there is a solution for this problem that doesn't require to destroy all my minecraft data.

**Comment by P3pp3rF1y** [comment]
Not sure what was happening with your  config file. Works well for me as it seems to work well in many modpacks.

The infernal tear not working is probably a result of alkahestry being disabled as in the released version infernal tear relies on alkahestry recipes to figure out how much experience to charge the player with and when alkahestry is disabled there's basically nothing to use as reference. In dev I have a version that uses separate  config for infernal tear to define this so once that is released this will be fixed.

The charge for rending gale being 30000 is just a result of 1 feather giving you 100 units of the charge, so it shows you that 300 feathers worth of charge is in the rending gale.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
