### ISSUE TITLE
1.16.4 - Conflict with Scaling Health

### ISSUE THREAD

**Issue by DeliciousTea** [P3pp3rF1y/Reliquary#492]
Posted this over on SH's Issue tracker, but wanted to clue you in here as well since this seems to be a thing happening with Reliquary.

https://github.com/SilentChaos512/ScalingHealth/issues/295#issuecomment-751299680

**Comment by P3pp3rF1y** [comment]
The code that was causing this got refactored to something else that doesn't need entity creation on world load so once dev version is released this will be fixed.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
