### ISSUE TITLE
1.16.4 (Forge 35.1.28) Disabling parts of the mod in the config files has no effect.

### ISSUE THREAD

**Issue by Tsunamori74** [P3pp3rF1y/Reliquary#493]
Tried several installations to see if maybe it was some weird conflict, but disabling mod content seems to have no effect at all. Items are still craftable and they still show up in JEI.

**Comment by JonasDoe** [comment]
Same here, so it can be replicated.

**Comment by P3pp3rF1y** [comment]
I have a version in dev which does this differently. Not sure what items were still craftable, but they shouldn't be and they will no longer appear in JEI and nor will recipes related to blocks / items that are disabled.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
