### ISSUE TITLE
Harvest Rod + Pedestal + Sweet Berries

### ISSUE THREAD

**Issue by ghost** [P3pp3rF1y/Reliquary#496]
Harvest rod accepts sweet berries and tries to plant it, but it doesn't act correctly.
The issue seems to be around when to harvest it, as it keeps planting and breaking the berry bush instantaneously.

Using: forge 1.16.5, reliquary-1.16.3-1.3.4.1061, Custom modpack with only reliquary on MultiMC(Debian).

**Comment by P3pp3rF1y** [comment]
This is now added in dev build. should be released soon.

**Comment by P3pp3rF1y** [comment]
this is now included in the latest release on curseforge
