### ISSUE TITLE
Any Conedensed potions not giving Effects, but being used up.

### ISSUE THREAD

**Issue by SolSavvy** [P3pp3rF1y/Reliquary#498]
Plain and simple. craft the essence for regeneration, made condensed potions using them. tried them out in the field ( all of them), but was not given any potion effect at all.

Forge: 1.16.4-35.1.37
Reliquary: 1.16.3-1.3.4.1061 (which is the newest available though it says it supports 1.16.4)

**Comment by P3pp3rF1y** [comment]
I have just tried this and I am unable to recreate your issue, I just get the effects applied? Are you playing with it in a pack? if so it's likely another mod causing this or interaction with it. if you can figure out which one I can take a look if there's anything that Reliquary is doing wrong here.

**Comment by SolSavvy** [comment]
Nuclear Craft, Astral Sorcery, Bookshelf, Enchantment Description, Reliquary(obviously), Apotheosis, ObserverLib,JEI, Forge, ToroHealth, CuriosAPI, Xaero's Mini-map, Waystones, Xaero's World Map, Placebo, and Storage Drawers.

That is all the mods installed up to latest versions.

**Comment by SolSavvy** [comment]
any of these conflict. I know I have had problems with ToroHealth in the past with model rendering bugs.

**Comment by SolSavvy** [comment]
So this still isn't resolved. can find no conflicting mods that would negate any condensed potions. so they just dont work.

**Comment by P3pp3rF1y** [comment]
I have actually just retested in dw20 pack and they work correctly. I am guessing you thought they don't because they don't show particles, but that's a feature that you don't see those annoying circles in your view all the time. However you can still see the effects in player's inventory view.
