### ISSUE TITLE
Infernal Tear not working in 1.5.1 of All The Mods 6

### ISSUE THREAD

**Issue by youneedafish** [P3pp3rF1y/Reliquary#499]
Right clicking doesn't select any items and shift right clicking makes the gaining xp noise but nothing else happens. I've tried with ingots, coal/charcoal, wood, and diamonds.

**Comment by tyler489** [comment]
Can confirm. Could this be because the tomb of alkehestry is disabled there is nothing to burn?

**Comment by P3pp3rF1y** [comment]
that actually is likely as it works off of alkahestry recipes which likely don't load. I have changed this over to a list of items to experience in config. it's done in dev and should be releasing that soon

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest release on curseforge
