### ISSUE TITLE
tome of alkahestry crashing and corrupting toml files

### ISSUE THREAD

**Issue by walmartjezus** [P3pp3rF1y/Reliquary#500]
I have the an issue while playing all the mods 6. basically, when you toggle auto consume and open your inventory, your game will crash. I did this many times and im not sure if its caused by this, but after a few tries it corrupted config files to the point of the game not launching, if you need more details i can easily provide them, dm me on Nqkia#3310 and i can send you my logs, im using atlauncher and the latest version of the modpack

**Comment by P3pp3rF1y** [comment]
to fix a crash I will need a crash log, can't find your discord name either and anyway things related to issues should go on github. So if you're still active and have the crash log please attach it here.

**Comment by walmartjezus** [comment]
> to fix a crash I will need a crash log, can't find your discord name either and anyway things related to issues should go on github. So if you're still active and have the crash log please attach it here.

hey there! i changed my discord name to NOwOkia#3310 and i might've found the cause. So basically jvm hates me and it constantly crashes on me for no reason (most likely graphical issues), which leads me to cause that the culprit is my 3070 but tbh idk, I can try to find some logs.

-kind regards, Nokia

**Comment by P3pp3rF1y** [comment]
I am going to close this. if you get a crash and have a log which shows that Reliquary is at fault feel free to create a new issue.
