### ISSUE TITLE
Crash upon opening alkahestry Tome

### ISSUE THREAD

**Issue by EnderMelody** [P3pp3rF1y/Reliquary#504]
[crash-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/6145361/crash-2021-03-15_21.08.09-client.txt)
also, I have disabled the alkahestry tome, potions and pedestals, and none of them are disabled properly.

Reliquary-1.16.3-1.3.4.1061
Forge: 36.0.46

**Comment by P3pp3rF1y** [comment]
I have a change in dev environment that no longer removes the items from game, but instead disables recipes and removes them from creative tab / jei. 
Not sure what your expectation for "properly disabled items" is, but this is the way they are supposed to be disabled - they still get registered, but player can't craft them and preferably doesn't see them in creative tab / jei

**Comment by EnderMelody** [comment]
Seems like the disabling of recipes is not working then:
![image](https://user-images.githubusercontent.com/12649140/113513988-236e3900-953a-11eb-922a-ec781e1d5dc8.png)
im 100% certain it is disabled in config.

**Comment by P3pp3rF1y** [comment]
it would only disable the items/blocks before so you wouldn't be able to actually use this recipe. But the in dev version also removes this view in JEI

**Comment by P3pp3rF1y** [comment]
just released the changes on curseforge
