### ISSUE TITLE
Rename Blank.png to blank.png

### ISSUE THREAD

**Issue by aaronhowser1** [P3pp3rF1y/Reliquary#505]
Resource names are supposed to be lower case, this causes certain things to break (in particular, the Custom Image item from FTB Quests, causing the error  `[10:43:59] [Render thread/INFO] [STDERR/]: [com.feed_the_beast.ftbquests.gui.SelectImageScreen:<init>:42]: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: xreliquary:textures/templates/Blank.png`)

**Comment by P3pp3rF1y** [comment]
that png wasn't used for anything so I have just removed this. will be fixed in next release

**Comment by P3pp3rF1y** [comment]
just released a new version so closing this
