### ISSUE TITLE
Apothecary Mortar has no in-world visuals on a server, but still takes up a block space

### ISSUE THREAD

**Issue by Febilian** [P3pp3rF1y/Reliquary#51]
It's really bizarre. I tried placing in both survival and creative mode, and both times it looked like it disappeared, but I can still walk into it and get that weird glitchy movement when you try to walk into a block that hasn't rendered fully.

I can't break it in either survival or creative, because it has no visible hitbox.

As the title indicates this only seems to take place on a dedicated server. I tried in single player and it placed just fine. The server log didn't have anything out of the ordinary, but if you think it'd help I can try to get a log.

**Comment by P3pp3rF1y** [comment]
I will need a bit more info on this one as I have just tried recreating this on two different machines both connected to server and on both I see the mortar correctly. 

Are you playing with this as part of a modpack? Could you try recreating with just Reliquary in that case?
What version of minecraftforge you have? I have built this and am testing it with the latest recommended - 1.8.9 - 11.15.1.1722
Any special client video settings (not default)? Even though I don't think that this would be the case given that you can see it in single player.

**Comment by Febilian** [comment]
Yeah, I'm playing with a custom set of mods. I suppose I can try testing with just Reliquary sometime, but I'm gonna guess I'll have to set up a server on its own for that and I don't know how soon I can do that since I play with a friend and they've been playing tonight.

Let's see, the Forge version I have running with it is 1.8.9 - 11.15.1.1729, so it IS a bit later than the one you've tested it with.

The only video settings I really have changed from default to my knowledge are the render distance(7 chunks) and clouds turned off, I've tried toggling some other ones but it hasn't done anything...

I'll try changing the Forge version to a more recent version when the opportunity arises and see if the issue persists, and if nothing else, I'll see when I can test with just Reliquary.

**Comment by Febilian** [comment]
Okay, I updated Forge, it didn't solve it. I did get a log this time though, which seems to mention something about tile entities or whatever, and the error didn't show up before I updated Reliquary. Maybe you can make more sense of it than I can.

https://paste.ee/p/UCJa7

**Comment by P3pp3rF1y** [comment]
That log unfortunately doesn't point at anything specific, but there's obvious there's some issue in communication between the server and client. I assume the mods are the same between the server and client, right?
Found someone who reported something very similar on forums. Looks like recreating a world solved it for them. Perhaps you could try to backup your world and have a new one created on server just to test out if it fixes this issue.
http://www.minecraftforum.net/forums/support/modded-client-support/2603780-blocks-from-mods-can-be-placed-but-do-not-show-up

**Comment by Febilian** [comment]
Yeah, the mods are the same save for some clientside mods on the client like a minimap, health bars, WAILA, etc. If I put them on the server, the server crashes.

However, a new world did indeed solve the problem. Sorry for taking up your time!

**Comment by P3pp3rF1y** [comment]
No worries about taking my time. I am happy that people report issues here even in these cases. And happy to see someone play with potion related stuff. In case you're interested you can grab the latest unstable build of 1.3.0 (next release) from bintray. It has some new config options (under items/blocks settings - Potions) that allow you to reveal more potion combinations in JEI. There is a load of combinations in there if you enabled everything.
