### ISSUE TITLE
Disabled gold nugget recipe, version 1.3.5.1094

### ISSUE THREAD

**Issue by Novakillerdk** [P3pp3rF1y/Reliquary#510]
Hey, i just found out that the newest version of Reliquary actually ends up removing the normal minecraft gold nugget recipe. As in the one using an ingot to turn into 9 nuggets.

This was only a thing in the version 1.3.5.1094, as i downgraded to the previous version and it was all fine. I tried this with only JEI and Reliquary installed, so i made sure to isolate it.

**Comment by P3pp3rF1y** [comment]
Thanks for reporting this, I have found the derp that I did in empty bullets to gold nuggets recipe which registered under the same name that vanilla registers its gold ingot to nuggets recipe. I should have a new release out today that fixes this.

**Comment by P3pp3rF1y** [comment]
this is now fixed in the latest version on curseforge
