### ISSUE TITLE
Ender staff crash server whenever i join

### ISSUE THREAD

**Issue by Hurricaneforces** [P3pp3rF1y/Reliquary#514]
Server crash after use Ender staff and crash when i join on Atm6 sky modpack
Step to reproduce:
- Shift right click take ender pearl in inventory
- Right click then crash 

Version: 1.16.5 1.3.5

![image](https://user-images.githubusercontent.com/67704595/115957837-f86e7800-a52e-11eb-9075-13e1f7b1115e.png)

**Comment by P3pp3rF1y** [comment]
Could you add a crash log? from this it's hard to see where the code crashed

**Comment by Hurricaneforces** [comment]
[crash-2021-04-24_11.15.22-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/6371473/crash-2021-04-24_11.15.22-server.txt)

**Comment by P3pp3rF1y** [comment]
It's missing feature in forge that was added in version 36.1.3 that is one minor version after the one you have so just updating to that or later version will fix it for you. I can also make it specifically require that or later version

**Comment by P3pp3rF1y** [comment]
minimum forge version added in the latest release on curseforge
