### ISSUE TITLE
incorrect reading of requirements

### ISSUE THREAD

**Issue by Zygus42** [P3pp3rF1y/Reliquary#515]
Even though Reliquary is shown as an optional mod, now that i've added the latest version of reliquary, the game fails to start, with a message that reliquary is the wrong version for the potion descriptions mod.

**Comment by P3pp3rF1y** [comment]
You need to report this to potion descriptions mod. There's nothing I can do about that on Reliquary side

**Comment by Zygus42** [comment]
Oops - I thought I was :)  Sorry
