### ISSUE TITLE
[1.16.5] Startup crash

### ISSUE THREAD

**Issue by maicol07** [P3pp3rF1y/Reliquary#517]
Screenshot:

![](https://user-images.githubusercontent.com/9463142/116526953-6d003880-a8da-11eb-9009-72c93a4496c2.png)

Log: https://pastebin.com/Qnzx6Rxs

**Comment by P3pp3rF1y** [comment]
OpenJ9 jvm isn't supported by forge. You will need to use a different one - oracle definitely works and other openjdk builds should be fine as well.

**Comment by jordan-msftfan** [comment]
@P3pp3rF1y NO although idk is openj9 is officially supported by forge, but i can launch forge modpack with openj9 jvm, this issues is hold on Reliquary
i can play the game with openj9 jvm and reliquary installed(version reliquary-1.16.3-1.3.4.1061)
but when i switch to version 1.16.5-1.3.5.1096 it shows error like what maicol07 posted
