### ISSUE TITLE
[1.16.5]can't find config files (not even in /world/serverconfigs)

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/Reliquary#519]
where's the config in 1.16.5? At first when I didn't see it in the common config folder I thought it would be moved to the serverconfigs, but I don't see it there either... is it under a name other than "reliquary" or something?
If it weren't for the items being available and working, I would wonder if the mod was loaded. I don't normally see something run without a config, especially a mod that has a lot to configure. The only hypothesis I have currently is that it somehow having trouble writing the file and just loading with "default" options... though if that were the case, what would I look for in the log file?
~~(Speaking of which, I'll add a link to the log in a minute. Looks like I'm going to have to manually upload it due to the amount of console spam causing it to exceed automatic upload limits)~~
[debug.log](https://gist.github.com/macks2008/46b8a0a83a653f2d148daf8da421f4a8)

**Comment by Twisted-Code** [comment]
do you ever check this repo anymore P9pp3rF1y? I know you used to, but it's been a while since... 1.10 I guess was the last time I reported an issue? Could really use a hand with this since my only alternative to configuring it (if configuring is even possible possible) is to use CraftTweaker to do what I want (specifically, make mob charms repairable in a crafting grid), but I don't like overriding the intended recipes?

**Comment by P3pp3rF1y** [comment]
I am pretty busy IRL and when I have time I spend a lot of it on sophisticated backpacks. But once a month usually try to clean up issues here as well. The config should be found under xreliquary in config folder as usual and it certainly is that way in multiple modpacks I have seen. So perhaps you have something that changes this location?
The repair items for individual charms are hardcoded in the mod and then `xreliquary:mob_charm_repair` recipe uses these. So you may be able to disable that recipe

**Comment by Twisted-Code** [comment]
yeah that's understandable. By the way, I absolutely love sophisticate backpacks and didn't even notice you were part of the project. That explains why it's so good a mod in terms of stability (seriously the number of issues I've had with reliquary other than this config problem is impressively low in my opinion) :-)
### in regard to my issue 
![image](https://user-images.githubusercontent.com/7110033/123262780-43245600-d4c6-11eb-8021-e7c6341e0628.png)
yeah I don't see that folder. Any idea what I can look for in the log file to figure out who's hijacking or interfering with your config creation? Do you log anything upon successful/failed creation of the file? if not, I'd be willing to run a debug build with some more verbose logging to figure this out if you want to toss me one.
edit:
although, upon further inspection, I do have a single file named xreliquary.cfg. My mistake, apparently, was searching for "reliquary" rather than "xreliquary"?

**Comment by P3pp3rF1y** [comment]
Yup it's still called xreliquary after the original author - Xeno's Reliquary
