### ISSUE TITLE
XRTippedArrowEntity modifying ArrowEntity's data manager

### ISSUE THREAD

**Issue by stepsword** [P3pp3rF1y/Reliquary#521]
`[24May2021 19:14:28.205] [Server thread/WARN] [net.minecraft.network.datasync.EntityDataManager/]: defineId called for: class net.minecraft.entity.projectile.ArrowEntity from class xreliquary.entities.XRTippedArrowEntity
`
So it seems like on servers, Reliquary is adding stuff to all arrows. But, this doesn't seem to also happen on the client side. When I print IDs in the Data Manager, my custom arrow's ids start at 11 on the server side (when just Reliquary is present, but 13 when Ars Nouveau is also present), but they start at 10 on the client side, which basically kills the data manager's usability as it compares ids when receiving updates on the client side. Removing Reliquary (and Ars Nouveau which is also doing something similar) fixes this.

**Comment by P3pp3rF1y** [comment]
fixed in latest release
