### ISSUE TITLE
[1.12.2] Sword disappear on pedestal.

### ISSUE THREAD

**Issue by RafaelFHeringer** [P3pp3rF1y/Reliquary#523]
I am playing a 1.12.2 modpack that have reliquary, and I was automating a farm and a mob farm with pedestals, then my sword just disappears, is there a way to fix that?

(Forge version: 14.23.5.2854)

Steps to reproduce:
-> have one pedestal actively do something (for example one with a Harvest Rod planting crops) 
-> activate another that has a weapon on it
-> after a few hits, the weapon will disappear

**Comment by P3pp3rF1y** [comment]
Weapons get damaged same as when you attack mobs with them. So I would guess the sword didn't have high durability

**Comment by RafaelFHeringer** [comment]
> Weapons get damaged same as when you attack mobs with them. So I would guess the sword didn't have high durability

No, even with a brand new diamond sword, with unbreakable, it disappear in less than a minute. I'm sure that this is a glitch.
Btw, I'm playing Roguelike Adventures and Dungeon, idk if that's some kind of conflict with another mod.

**Comment by P3pp3rF1y** [comment]
I no longer support 1.12.2 but to be sure just retested in 1.16.5 and unbreakable sword just stays in pedestal indefinitely without taking any damage.
