### ISSUE TITLE
[Bug] [1.16.5] Turning off spawn eggs recipe no longer works

### ISSUE THREAD

**Issue by faeldray** [P3pp3rF1y/Reliquary#524]
I'm not sure when exactly it happened but the config option `disableSpawnEggRecipes` no longer works. Whether set to true or false, spawn fragments can still be used to craft spawn eggs.

Related: #501

**Comment by P3pp3rF1y** [comment]
Was an issue of jei integration that would still show these recipes but they wouldn't work. I have fixed this in dev to not add the recipes in jei.

**Comment by P3pp3rF1y** [comment]
fixed in the latest release on curseforge
