### ISSUE TITLE
Suggestion : Options for the Alkahestry Tome

### ISSUE THREAD

**Issue by craftish37** [P3pp3rF1y/Reliquary#526]
Hello, I was wondering if it's possible to add a parameter in the toml config to toggle a general price of duplication with the tome : Like you can dup anything for THIS price wrote in the config. Moreover, I think the actual way to add duplicable items to the mod is a bit tricky for anyone who never have used an IDE or just don't want to rebuild the mod and maybe create another way to add items and prices in power in the config too ? Or in another config 👀

**Comment by craftish37** [comment]
Oh and of course if anyone is able to tell me how it's actually possible to dup an enchanted book and keep the enchant, just answer under it 👀

**Comment by P3pp3rF1y** [comment]
So the recipes for alkahestry tome can be added as any other recipes modpacks usually add - they are just json recipe definitions that can be included in datapack.

**Comment by P3pp3rF1y** [comment]
And regarding that enchant thing you can add recipe in datapack to duplicate specific enchanted book but the way this works you will get two same books for one for a cost of tome's charge
