### ISSUE TITLE
Hero's Medallion XP retrieving

### ISSUE THREAD

**Issue by Wlnfr** [P3pp3rF1y/Reliquary#530]
Forge: 36.2.2
Reliquary: 1.16.5-1.3.5.1098 and 1.16.5-1.3.5.1100(I only tested those two versions)
Medallion sometimes gives 10 levels at once when right clicking, which can be very inconvenient when you try to only retrieve a few levels. I don't know how to classify this issue, because if it's a feature - it's quite buggy and needs fixing(and a config to control it), if it's not the intended behavior, then it's a bug and it still needs fixing. Here's a video demonstration.
https://user-images.githubusercontent.com/8050905/135517664-be51bc21-e433-4ded-9f38-42379dee4077.mp4

**Comment by P3pp3rF1y** [comment]
This has been changed in 1.18 port and I haven't heard that many complaints about it in 1.16 so I am going to just close as going forward it's taken care of.
