### ISSUE TITLE
Interdiction orches turning invisible

### ISSUE THREAD

**Issue by stromseng** [P3pp3rF1y/Reliquary#533]
The Interdiction torches turn invisible after a while on my multiplayer server. When I break the block beneath however, they drop. I do not see a hitbox outline when looking at them.

**Comment by P3pp3rF1y** [comment]
there really isn't a reason for that to be happening in the Reliquary code - they are just regular torches with slightly different texture and code that checks for entities around them and pushes them away. None of this could cause them to disappear or even stop existing on client the way you describe it. I am going to close but if you find more for example in logs feel free to let me know about that.
