### ISSUE TITLE
NPE Crash

### ISSUE THREAD

**Issue by Nerdpie** [P3pp3rF1y/Reliquary#54]
I encountered a crash trying to load MC 1.8.9 with a number of mods; crash posted at https://gist.github.com/Nerdpie/f0bf1783249b38f2f455#file-crash-2016-02-21_11-00-05-client-txt

I suspect that this issue is similar to https://github.com/ForestryMC/ForestryMC/issues/869 , with a null crafting result.

**Comment by P3pp3rF1y** [comment]
So I cannot recreate this one - tried loading up with the same version of blood magic and I have also stepped through the loading sequence to make sure that I see BM calling the same code at the same time.

One thing I can make of this is that Alkahestry Tome was somehow removed from GameRegistry through some mod. Not sure that I even want to put a code in to check for that happening as that's not what any mod should ever do.
The only other one is that BM would be trying to figure out a packing/unpacking recipe for itemstack that has no item defined, which is even harder to believe.

Anyway I wouldn't be able to figure this out with the large number of mods you have in the list. If you manage to narrow it down to what mod or config change may be causing it I will be happy to take a closer look.

**Comment by Nerdpie** [comment]
Thanks for the reply.  I've tested with just Blood Magic and Reliquary, and I can confirm that those two on their own are fine.  I'll look into it more and let you know if I find what mod introduces the issue.

**Comment by P3pp3rF1y** [comment]
It may help you that this runs fine in The pioneers pack that has plenty of mods (http://minecraft.curseforge.com/projects/the-pioneers). So excluding all that are in that pack should narrow it down.

**Comment by P3pp3rF1y** [comment]
Any luck in recreating the issue?

**Comment by Nerdpie** [comment]
Sorry, I've been distracting myself with Project Ozone.  I'll look into it tonight.

**Comment by P3pp3rF1y** [comment]
No problem, was just wondering if you had a chance to look into it.

**Comment by P3pp3rF1y** [comment]
What pack are you playing that you get this error with? I may try loading it in my dev environment and see what's happening there.

**Comment by Nerdpie** [comment]
It's a custom pack, unfortunately.  I've actually thought about setting up a dev environment for the specific build of Forge and trying that...

I'll poke it after work, honestly-won't-get-sidetracked-again-I-swear...

**Comment by P3pp3rF1y** [comment]
Closing, will release for 1.8.9 soon

**Comment by Nerdpie** [comment]
Sorry that I wasn't more help, but congrats on tracking down the issue!
