### ISSUE TITLE
[1.16.5] Pedestal with Tinker's Construct weapon does not attack

### ISSUE THREAD

**Issue by J-Dill** [P3pp3rF1y/Reliquary#540]
### Reliquary Version: reliquary-1.16.5-1.3.5.1100

When I have Tinker's Construct weapon (sword, cleaver, etc.) in the pedestal (non-display only) and the pedestal is powered with redstone, it does not attack mobs. To test, I first had a vanilla sword in the pedestal and it does attack a nearby blaze; immediately switching it out for a Tinker's sword and/or cleaver stops the attacking.

I normally wouldn't call this out, but it mentions in the Wiki that this usually should work, so it may be the 1.16.5 version of either this or Tinker's that is causing this functionality to no longer work.

**Comment by Dictatorputski** [comment]
Can confirm it's the same issue here, tried using a pre-built weapon, building one from scratch, trying different types and it doesn't seem to function as it says it should on the wiki.
Im using the same versions as the above but i'm also using the create above and beyond pack (not that that it probably matters)

**Comment by J-Dill** [comment]
@Dictatorputski I too found it initially while playing Above and Beyond (loving it), and wanted to make sure it wasn't just the modpack and sure enough it appears not to be.

**Comment by P3pp3rF1y** [comment]
fixed in the released version
