### ISSUE TITLE
Charms in belt with Mending do not repair

### ISSUE THREAD

**Issue by johtoRegion** [P3pp3rF1y/Reliquary#547]
Playing 1.16.5, and I was messing around with my blaze farm and decided to craft a charm. Noticed it broke, and decided to give another one Mending. Doesn't repair while in the belt, so I gave the belt itself Mending. No luck.

**Comment by P3pp3rF1y** [comment]
How did you actually get mending on the charm? They are not supposed to get it and as far as I can see the code is in place to prevent vanilla from applying these in enchantment table and anvil.

**Comment by P3pp3rF1y** [comment]
closing given no additional feedback
