### ISSUE TITLE
Crash on Boot

### ISSUE THREAD

**Issue by HalcyonSeas73** [P3pp3rF1y/Reliquary#551]
Minecraft Version: 1.18.2

Forge Version: 40.0.12

Mod Version: 1.18.2-2.0.0.1127

Single Player or Server: Single

Describe problem (what you were doing; what happened; what should have happened):
Reliquary crashes on load; see image below.

![Untitled](https://user-images.githubusercontent.com/84727791/157519443-cf626bcd-39e1-4d87-95c9-5fcf7caa9337.png)

**Comment by P3pp3rF1y** [comment]
could you attach your actual crash log? This screen doesn't help

**Comment by P3pp3rF1y** [comment]
I actually I was able to recreate, this is rather odd that method / field that obviously exist in code, don't seem to have changed between versions and for some reason can't be found when run out of dev. Need to look into what exactly is causing that.

**Comment by HalcyonSeas73** [comment]
(Fresh) crash log:
[crash-2022-03-09_18.46.54-fml.txt](https://github.com/P3pp3rF1y/Reliquary/files/8218979/crash-2022-03-09_18.46.54-fml.txt)

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
