### ISSUE TITLE
Crash when used with Ballistix, ElectroDynamics, Nuclear Science (unknown issue)

### ISSUE THREAD

**Issue by JankGamer** [P3pp3rF1y/Reliquary#554]
Playing through ATM6 pack (1.16.5) with no issues. Added in the mods in the title (although, think its ElectroDynamics causing it) and the pack crashes on opening load. Crash log (https://pastebin.com/DREdCSM1) refers to hellfire/astral sorcery and reliquary but I'm not sure the issue lies with these mods. Asked on Forge, was directed to ask Astral/Reliquary mod team as they are the ones referenced.

Any help in navigating would be much appreciated!

**Comment by P3pp3rF1y** [comment]
yes it's electrodynamics. was reported before in https://github.com/P3pp3rF1y/Reliquary/issues/544 and there's nothing I can do on my side.
