### ISSUE TITLE
[1.16.5] Crash when using coin of fortune with full inventory and void tear

### ISSUE THREAD

**Issue by Zenith-One** [P3pp3rF1y/Reliquary#559]
I experienced an interesting crash while playing Create: Above & Beyond while manually using the coin of fortune to suck up a bunch of items laying around on the ground. I right clicked and grabbed a bit of stuff, then went to right click again and crashed. 

Looking at the stack trace, it seems to be caused by an interaction between the coin of fortune and the void tear. I was able to replicate the crash afterward by filling up my inventory and attempting to pick up something else with the coin. Importantly, the item I was trying to pick up (and didn't have room for) was NOT the item in the tear.

Steps to replicate:
1. Have full inventory
2. Have void tear with some item in it
3. Throw some other item on the ground which you can't pick up due to full inventory (which also is not the item in the void tear)
4. Use the coin of fortune's right click vacuum feature
5. Enjoy the pleasant sight of your launcher :)

I've attached the log for the first and second crashes below.
[crash.txt](https://github.com/P3pp3rF1y/Reliquary/files/8329814/crash.txt)
[crash2.txt](https://github.com/P3pp3rF1y/Reliquary/files/8329827/crash2.txt)

Apologies if this is a duplicate, or it's already closed. I tried to search for it, but wasn't able to find anything in open or closed issues.

**Comment by P3pp3rF1y** [comment]
I can't recreate this in 1.18, haven't seen any more of these reports and this part of the code was refactored in 1.19 so I am just going to close
