### ISSUE TITLE
(1.18.2) Crash on startup 

### ISSUE THREAD

**Issue by Gavin456b** [P3pp3rF1y/Reliquary#560]
Index 2048 out of bounds for length 1025
[crash-2022-03-24_18.06.19-fml.txt](https://github.com/P3pp3rF1y/Reliquary/files/8346239/crash-2022-03-24_18.06.19-fml.txt)

**Comment by P3pp3rF1y** [comment]
Just tested to be sure, but loading the mod by itself works absolutely fine and no one else has reported an issue like this which would for sure get reported by now. So it's one of the other mods in your modpack that's causing the issue. If you can figure out which mod it is I can take one more look to see if I am doing something wrong here, but to be honest I can't see how as there's only one way to register items' dispense behavior.

**Comment by Gavin456b** [comment]
The issue appears to be gone. Not sure what fixed it but many mods updated.

**Comment by KuroPeach** [comment]
same bug，but can't find useful information. 
[crash-2022-09-21_13.40.31-fml.txt](https://github.com/P3pp3rF1y/Reliquary/files/9613341/crash-2022-09-21_13.40.31-fml.txt)
