### ISSUE TITLE
Crash on Dedicated server Load.

### ISSUE THREAD

**Issue by Darkmega18** [P3pp3rF1y/Reliquary#561]
G'day again, seems you run both Reliquary here and sophisticated backpacks. 
So, you might have also seen this issue: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/453

The same crash also makes mention of reliquary as another crashing source in both the latest log and crash report. Please take a look at them and let me know if these are user error or just something you stuffed up and need to get updated.

**Comment by P3pp3rF1y** [comment]
Same solution - you need different jvm to run forge modpacks.

**Comment by Darkmega18** [comment]
yep. thanks. soon as they realized, they checked their java and updated it and it ran just fine.
