### ISSUE TITLE
[1.18.2] Tome of Alkahestery recipes not working (empty tag)

### ISSUE THREAD

**Issue by unmoving-javi** [P3pp3rF1y/Reliquary#564]
Unsure of exactly what causes this, but in JEI a number of the [Tome of Alkahestery's recipes are labelled as 'empty tag'](https://imgur.com/a/dgqlsVe) and do not function. This might have something to do with Forge's tag system constantly getting changed, not 100% sure though.

All the recipes labelled as 'empty tag' do not work, but some of them do work, for instance, clay, soul sand, dirt, flint, and charcoal. Inexplicably, the recipe for _coal_ doesn't work, but the one for charcoal does.

In any case, this is probably worth looking into.

**Comment by P3pp3rF1y** [comment]
Not sure what version you're referring to but this is an issue in JEI and a conflict with how tags and recipes are synced to the client. if tags get synced only after the recipes this used to happen I don't believe it's the case in latest 1.18 versions. Nothing I can do about that.

**Comment by P3pp3rF1y** [comment]
Actually now I have realized my blindness to the tag in the issue name and that you're referring to 1.18, but still this is on JEI side and I can't do anything about that. the recipes should still work though if you put them in crafting grid as that's independent from JEI displaying empty tag.

**Comment by P3pp3rF1y** [comment]
And actually after taking a look at a discussion in JEI discord related to another mod let me take a step back here and take a look at code in tome crafting recipes. Seems that the issue that previously existed with these may have hidden another thing that I am doing there which may be the cause of your issue here.
