### ISSUE TITLE
[1.18.2] Storm bullets do not charge creepers

### ISSUE THREAD

**Issue by unmoving-javi** [P3pp3rF1y/Reliquary#565]
Was messing around in Creative a bit, found out that storm rounds do not charge creepers like their description says. The damage does indeed differ depending on the weather, but no matter the weather, the creepers do not get charged.

**Comment by P3pp3rF1y** [comment]
And when you say no matter the weather you mean you have tried the shots during storm and they didn't charge the crrepers? What version of the mod?

**Comment by unmoving-javi** [comment]
Newest 1.18.2 version (2.0.2.1131), I tried all weather (clear, rain, thunder) via the /weather command. If it matters, it was in a biome where it was snowing rather than raining, but there was still thunder so I assumed (maybe incorrectly) that it would still work.

**Comment by unmoving-javi** [comment]
Oh. It works fine outside of cold biomes. That's confusing, but not a bug. Sorry to waste your time.

**Comment by P3pp3rF1y** [comment]
closing...
