### ISSUE TITLE
[1.16.5] lyssarod‘s bug. copy item.

### ISSUE THREAD

**Issue by KuroPeach** [P3pp3rF1y/Reliquary#567]
The Lyssa Rod can steal items from the mimicube in Alex's Mobs, and the mimicube copy the player's equipped weapon. @[Alex-the-666](https://github.com/Alex-the-666)
![image](https://user-images.githubusercontent.com/19620848/164498606-9517dcab-5f9c-4e54-bf24-e86090e7a658.png)

**Comment by P3pp3rF1y** [comment]
I am adding a blocklist to allow specifying which entities lyssa rod can't steal from. Though this will only be available from 1.18 on as I am no longer adding features to 1.16.

**Comment by P3pp3rF1y** [comment]
The latest release has entity block list for this
