### ISSUE TITLE
1.18 version of the mod creates an infinitely recursive TranslatableComponent

### ISSUE THREAD

**Issue by diesieben07** [P3pp3rF1y/Reliquary#569]
https://github.com/P3pp3rF1y/Reliquary/blob/8097df43e0fe9fc478a6283b98da9c68cfd2f1a0/src/main/java/reliquary/items/block/BlockItemBase.java#L31
This line creates a TranslatableComponent with two parameters: null and the tooltips list. Since the list will then later contain this TranslatableComponent, the component effectively contains itself as an argument.
This causes crashes like this:
https://bytebin.lucko.me/tTiGqaNjkt

**Comment by P3pp3rF1y** [comment]
Thanks for letting me know, apparently relic of a bit of refactoring that I didn't catch in testing. Will be released soon.
