### ISSUE TITLE
Crash using Rending Gale with Pedestal

### ISSUE THREAD

**Issue by Schyler-Lowry** [P3pp3rF1y/Reliquary#571]
[crash-2022-05-28_21.05.14-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/8792433/crash-2022-05-28_21.05.14-server.txt)

World save is now corrupted. Any attempt to load the world again results in this crash.

Tested it some more with Shears, and the result is the same. Any attempt to give red stone signal to a pedestal seems to result in a crash, and corrupts the world save file.

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on curseforge
