### ISSUE TITLE
1.18.2 Game crashed when I activated coin of fortune 

### ISSUE THREAD

**Issue by Schyler-Lowry** [P3pp3rF1y/Reliquary#573]
I had a coin of fortune in a pedestal. I realized it wasn't on, so I took it out, right clicked to turn it on, and the game crashed. 
Worth nothing: I was already wearing a second coin of fortune in my curios necklace slot.
[crash-2022-05-31_10.18.39-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/8805971/crash-2022-05-31_10.18.39-client.txt)

**Comment by Schyler-Lowry** [comment]
When I say I right clicked to turn it on, I meant I had the coin in my hand and I right clicked. Then my game crashed. The server stayed running just fine however.

**Comment by P3pp3rF1y** [comment]
I can see that it crashed on void tear. Would you know what if anything was in that void tear?

**Comment by P3pp3rF1y** [comment]
I just tried testing with the void tear and fortune coin for a bit and can't recreate so I will definitely need more info on how exactly to recreate this.

**Comment by Schyler-Lowry** [comment]
The void tear having relevance to this situation is actually news to me. I didn't even realize the void tear was in my inventory at the time of this. Unfortunately I can't tell you exactly what it was holding at that time. I've only used the void tear for these few things so it could have been:

- clay
- stone
- cobblestone
- dirt

This crash hasn't happened since, but I will try to replicate it again once I'm home from traveling in the next couple of days.

**Comment by Schyler-Lowry** [comment]
Closing this issue because I have not been able to replicate this crash again.
