### ISSUE TITLE
[1.18.2] Inventory within the Harvest Rod is not consumed on use

### ISSUE THREAD

**Issue by enigmaquip** [P3pp3rF1y/Reliquary#576]
Seeds inside the harvest rod's inventory are not consumed when they are the selected usage of the rod and are planted in farmland. As well as bone meal

**Comment by enigmaquip** [comment]
Tested with only: 
Forge 40.1.31
Reliquary 1.18.2-2.0.4.1137
JEI 1.18.2-9.7.0.195

**Comment by enigmaquip** [comment]
Bone Meal seems like it may be properly being used up, but the counter doesn't update unless the tool is turned off or swapped to a different item

**Comment by P3pp3rF1y** [comment]
this was fixed in release a bit ago
