### ISSUE TITLE
[1.18.2] Alkahestry Tome cannot fuel Altars of Light

### ISSUE THREAD

**Issue by yanang007** [P3pp3rF1y/Reliquary#579]
Game version: 1.18.2
Mod version: Reliquary 1.18.2-2.0.8.1139

Step to reproduce:
1. Place an Altar of Light and charge the Alkahestry Tome with redstone.
2. Right click Altar of Light with Alkahestry Tome in hand does not fuel it.

Expected result:
Alkahestry Tome can successfully fuel the altar.

Possible cause is that Alkahestry Tome puts its charge data under "charge" tag: 
https://github.com/P3pp3rF1y/Reliquary/blob/bb6919165fca50d380fc3e8bb39fc3d78089c158/src/main/java/xreliquary/items/AlkahestryTomeItem.java#L114-L117
but Altar of Light get its charge through "redstone" tag:
https://github.com/P3pp3rF1y/Reliquary/blob/bb6919165fca50d380fc3e8bb39fc3d78089c158/src/main/java/xreliquary/blocks/AlkahestryAltarBlock.java#L102-L112

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release
