### ISSUE TITLE
[1.18.2] Mob charm fragments' JEI description placeholders not replaced correctly 

### ISSUE THREAD

**Issue by yanang007** [P3pp3rF1y/Reliquary#580]
Game version: 1.18.2
Mod version: Reliquary 1.18.2-2.0.8.1139

Step to reproduce:
1. Open usages for Skeleton Charm Fragment (any other Mob Charm Fragment also works)
2. The item description shows that "Skeleton Charm Fragment is a crafting component of  Charm"

Possible cause is this:
https://github.com/P3pp3rF1y/Reliquary/blob/b018bf4f56ee2042e230517c9da68d6b1c188bdb/src/main/java/reliquary/compat/jei/ItemDescriptionBuilder.java#L174-L187
where 
https://github.com/P3pp3rF1y/Reliquary/blob/b018bf4f56ee2042e230517c9da68d6b1c188bdb/src/main/java/reliquary/compat/jei/ItemDescriptionBuilder.java#L185
doesn't replace the second placeholder in the description "%s Charm Fragment is a crafting component of %s Charm"

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release

**Comment by yanang007** [comment]
Thanks!
