### ISSUE TITLE
[1.16.5, v1.3.5.1124] Crash after drinking an instant damage condensed potion

### ISSUE THREAD

**Issue by Catomax262** [P3pp3rF1y/Reliquary#583]
Crash log was so big that i had to upload a file: https://www.mediafire.com/file/x2nv6ggpja1ifun/crash-2022-07-05_13.16.00-server.txt/file

**Comment by P3pp3rF1y** [comment]
Looks like better invisibility mod is the one where it crashes and their code isn't even public please report to them. I can't help with this one until I know what I may be doing wrong here

**Comment by P3pp3rF1y** [comment]
closing as there was no additional response to follow up on
