### ISSUE TITLE
[1.18.2] Items from Reliquary cannot be hidden in JEI by TH Item Stages

### ISSUE THREAD

**Issue by NyvexOfShadows** [P3pp3rF1y/Reliquary#584]
TH Item Stages is a relatively new Game Stages alternative that is allows devs to hide items in JEI. I tried to enable this for Reliquary, but it appears that items will still be displayed. The disabling of a whole mod only requires its modid to be used, so I put in "reliquary", but items continued to appear. I'm either using the wrong modid (and would be delighted to learn the right one), or there's a fix from one of the mods to be made.

**Comment by P3pp3rF1y** [comment]
Could you point me to that mod? by you saying it's relatively new game stages alternative to Game Stages I don't suppose you mean https://www.curseforge.com/minecraft/mc-mods/item-stages which is Game Stages addon and was created 5 years ago. 

I will need to understand what that mod does to know what may be wrong on my side.

**Comment by NyvexOfShadows** [comment]
Sure, here's the mod I'm referring to: https://www.curseforge.com/minecraft/mc-mods/totally-harmonious-item-stages#:~:text=Totally%20Harmonious%20Item%20Stages%20(T.H.I.S.,is%20item%20gating%20behind%20stages.

This mod is able to create stages for items, dimensions, and blocks through config files. A particular feature of the mod is the ability is to hide items in JEI, something that Reliquary appears to not be compatible with.

**Comment by P3pp3rF1y** [comment]
And what version of Reliquary are you trying this with and what mod id have you put in config to hide the items?

**Comment by NyvexOfShadows** [comment]
I'm using reliquary-1.18.2-2.0.12.1143.jar, using "reliquary" as the mod id.

**Comment by NyvexOfShadows** [comment]
Anything else you might need?
