### ISSUE TITLE
[1.18.2] Hero's Medallion not absorbing EXP and EXP gauge in bottom right Broken when looking at blocks.

### ISSUE THREAD

**Issue by Dystinct** [P3pp3rF1y/Reliquary#587]
I do not know if you would like me to split these issues into 2 separate tickets, but since I noticed both issues at the same time they may be related. As stated in the title; for some unknown reason after crafting the Hero's Medallion it will not absorb EXP from the player nor the ground when activated. It will not absorb EXP even when deactivated (just in case). The entire time I have been testing this, the EXP gauge in the lower right corner would turn into a gradient whenever you look at a block but looking at an entity does not cause the same issue.

As I am using it in my own custom modpack (80 mods) attempting to test it against every single mod to see what mods might be causing some compatibility issues has become slightly... laborious. Would like your insight if possible and can provide a full list of mods if necessary.

Forge | v40.1.73
Reliquary Reincarnations | v2.0.12.1143

Image attached is showing the Gauge broken, and to a minor extent, how the Medallion does not absorb EXP.
![image](https://user-images.githubusercontent.com/17397791/183961703-7fd53aac-7c36-4ef6-ada0-2619202abfcc.png)

**Comment by P3pp3rF1y** [comment]
I am unable to recreate the issue with hero medallion not draining palyer's xp, I believe that one is another mod incorrectly updating current player's xp where it doesn't update the xp points being tracked behind the scenes, but only levels and progression to the next level.

However I have fixed the xp bar display.
