### ISSUE TITLE
[Reliquary Reincarnations--1.18.2-2.0.12.1143][1.18.2-Forge 40.1.73] Occasional Startup Crash

### ISSUE THREAD

**Issue by TheWitherlord** [P3pp3rF1y/Reliquary#590]
I have a mod pack with several other mods, but Reliquary Reincarnations is occasionally crashing on startup giving me this error.

Link: https://gist.github.com/TheWitherlord/0af82e3cc4d18a1d449042bb961e52bc

The game is still playable, however, this weird crash happens on startup randomly and you have to reset the game every time to hope that it doesn't fail.

Love Reliquary keep up the good work

**Comment by P3pp3rF1y** [comment]
All that Reliquary does there is register a new dispenser behavior and it's crashing on getting the space in collection of dispenser behavior for the reliquary one. And I can see that you have ton mods there where many seem to change the vanilla registry there and it's one of them causing this simple registry logic to fail. Nothing I can do from my side.
