### ISSUE TITLE
[1.16.5] Inventory within the Harvest Rod is not consumed on use

### ISSUE THREAD

**Issue by Mexano222** [P3pp3rF1y/Reliquary#593]
Seeds inside the harvest rod's inventory are not consumed when they are the selected usage of the rod and are planted in farmland.

Tested with only:
Forge 36.2.34
reliquary-1.16.5-1.3.5.1124

**Comment by P3pp3rF1y** [comment]
This works in newer versions and at this point I am too busy to be fixing things like this in version that has been out for a very long time. So I am closing and you can consider it a benefit of the rod. Also make sure that you are not in creative when testing something like this as in creative it actually doesn't consume anything.
