### ISSUE TITLE
[Bug] Charm Belt causing crash to desktop

### ISSUE THREAD

**Issue by tjmiller3551** [P3pp3rF1y/Reliquary#599]
In allthemods 7, Charm Belt is currently uncraftable and causes the game to crash back to Minecraft Launcher. Attempting to put the crafting recipe into the crafting grid from Refined Storage through JEI causes the game to crash to desktop. Manually putting in the items shows no craftable in the table and then crashes to desktop after a few seconds. All The Mods 7 game version is 0.4.32, Minecraft version is 1.18.2
[crash-2022-09-24_22.57.01-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/9646506/crash-2022-09-24_22.57.01-client.txt)

**Comment by P3pp3rF1y** [comment]
This crash looks just like polymorph trying to get recipe at incorrect moment, I don't see any mention of Reliquary / charm belt in there and don't see how Reliquary could be a cause of this issue. Is there another crash you have that you wanted to share here?

**Comment by tjmiller3551** [comment]
That was the crash report generated, I can easily replicate it by accessing my crafting grid in refined storage and clicking the button to move the recipe into the crafter. This is the only item I've found that causes this to happen. Here is a crash report from a crash I just had by replicating the issue. Unless the issue is an issue with Refined storage but this is the only item I've had this issue with.
[charm belt crash report.txt](https://github.com/P3pp3rF1y/Reliquary/files/9670066/charm.belt.crash.report.txt)

**Comment by P3pp3rF1y** [comment]
I am unable to recreate this with all the mods 7 so I will need more details from you on how I can
- are you playing on a server?
- have you tried redownloading the pack to possibly fix any corruption issues?
- have you added any mods to the pack?

**Comment by P3pp3rF1y** [comment]
@TheIllusiveC4 just fyi on the issue I mentioned

**Comment by tjmiller3551** [comment]
I am playing on a server that's just being hosted on a friends personal computer, we haven't added any additional mods to the pack. I have not tried redownloading the pack yet but I can try that tonight when I get home from work

**Comment by P3pp3rF1y** [comment]
closing this as it was some kind of quirk that not only doesn't seem to affect other players who play with Reliquary but not even other players that play with atm7
