### ISSUE TITLE
[Bug] Coal listed twice as potion ingredient

### ISSUE THREAD

**Issue by Archmage-Erebus** [P3pp3rF1y/Reliquary#600]
I was trying to brew potions of withering using JEI, but the coal recipes weren't working. I checked the config file and noticed that coal was listed twice for the ingredients list.

**Comment by Schattengaenger** [comment]
I found a way to fix it and thought I should probably post it here for others and you to find:
change the entries of coal into `"minecraft:coal=blindness|1|0;absorption|3|0;invisibility|1|0;wither|0|0"`
this should now fix the bug of the invisibility essence and wither essence being uncraftable with the right recipe.

**Comment by Archmage-Erebus** [comment]
Shouldn't it be different by default?

**Comment by P3pp3rF1y** [comment]
fixing the default for 1.19
