### ISSUE TITLE
Emperor's Chalice can't drink

### ISSUE THREAD

**Issue by 5tarsfury** [P3pp3rF1y/Reliquary#602]
FTB ultimate anniversary edition uses Reliquary version 1.16.5-1.3.5.1100. I can place water with the chalice, switch modes, and remove water.  I cannot drink to restore hunger.  I tried both at full health and while missing about half.  I ran around holding right click while staring at the sky until I was missing 4 hunger bars.  No eating/drinking the whole time.  Still holding right click I looked at the ground and it started placing water.

**Comment by Hranitel** [comment]
also a problem
