### ISSUE TITLE
Pedestal sounds playing at y=0

### ISSUE THREAD

**Issue by belathus** [P3pp3rF1y/Reliquary#605]
I have a pedestal with a sword on it at y=59. I hear the mobs it attacks getting hit, but when I dig down to y=0 beneath it, I hear the whoosh of the sword being swung. Turning the pedestal off stops the sounds.

On version 1.18.2-2.0.19.1161.

**Comment by P3pp3rF1y** [comment]
This was the way I solved the issue with creepers exploding trying to kill the fake player that actually swings the sword. Was almost going to say this is not possible to be done otherwise, but have figured out a different way and fixed this sound for next 1.19 release.
