### ISSUE TITLE
[1.19.2] Twilight Cloak crashes the server randomly.

### ISSUE THREAD

**Issue by Gbergz** [P3pp3rF1y/Reliquary#606]
Title^

Wearing the Twilight Cloak whilst anywhere really seems to crash the server. Not entirely sure why.

**Crash-Report:** https://gist.githubusercontent.com/Gbergz/fee336d7f7bf16f0d94f14d1419e8421/raw/784e6a60dcf7f5cb60d2e0f5d4afa0fbc6627540/gistfile1.txt

**Minecraft:** 1.19.2
**Forge:** 43.1.47
**Reliquary Version:** 1.19.2-2.0.20.1166

**-** Gbergz

**Comment by izofar** [comment]
Fixed in [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31)

Issue can be closed.
