### ISSUE TITLE
some functions don't work. @bug

### ISSUE THREAD

**Issue by Hranitel** [P3pp3rF1y/Reliquary#607]
the ender staff cannot change the operating modes (shift+LBM)

I can't drink from the endless bowl

**Comment by aelfwyne** [comment]
I can't get the ender staff to charge either. Holding a stack of pearls, shift right click and it makes the particle effects but nothing happens. It won't charge.

**Comment by P3pp3rF1y** [comment]
What version are you on?

**Comment by P3pp3rF1y** [comment]
this was likely on 1.18 + version because in those the mode changing has changed to shift scroll. Closing ...
