### ISSUE TITLE
Rending Gale not granting flight

### ISSUE THREAD

**Issue by Nyauster** [P3pp3rF1y/Reliquary#608]
It is listed that a rending gale when placed on a pedestal will grant flight, however it isnt working. Tried both display and non-display pedestals, fully charged with feathers. Playing on 1.18 version (ATM7 modpack). Thought it might be disabled but I checked the config and it doesnt seem to be, though I'm not really sure either.

**Comment by P3pp3rF1y** [comment]
It's working for me so the only thought I have is that you only had it in display pedestal which doesn't provide any special function to the items. It needs to be in more expensive regular pedestal and that pedestal needs to be powered with redstone or turned on using right click. Anyway closing this now as it's quite dated, feel free to reopen if you happen to run into the same issue in 1.19.
