### ISSUE TITLE
Tome of Alkahestry can't be removed from AntiBarrel

### ISSUE THREAD

**Issue by Rusthicc** [P3pp3rF1y/Reliquary#609]
The Tome of Alkahestry can't be removed from YABBA AntiBarrels. The icon will show that it is out of storage but it will immediately disappear if you replace it with an item in your inventory or try to use it.

**Comment by P3pp3rF1y** [comment]
it's just a regular item, doesn't even have any special interaction on click so this is definitely up to Yabba to fix.
