### ISSUE TITLE
NullPointerException when using Seeker/Ender Shot against Shulkers

### ISSUE THREAD

**Issue by Andstar** [P3pp3rF1y/Reliquary#610]
As the title says. Using any other magazines doesn't crash the game. Playing Enigmatica 8 - 1.18. Attached are the crash reports from the server and a single player world
[crash-2022-11-21_00.01.38-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/10050998/crash-2022-11-21_00.01.38-server.txt)
[crash-2022-11-20_22.56.36-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/10051000/crash-2022-11-20_22.56.36-server.txt)

**Comment by P3pp3rF1y** [comment]
Fixed this for 1.19
