### ISSUE TITLE
Witch Hats.

### ISSUE THREAD

**Issue by Kevin-Marsh** [P3pp3rF1y/Reliquary#611]
I am playing AlltheMods 8 which includes a mod for farming mobs called gateways to eternity. This mod generates resources out of a gate after fighting a wave of enemies. The witch gate can become problematic since witch hats are unstackable. This is further compounded by the fact is is effected by severing and looting. The end result is a lot of entities being generated since Witch hats are unstackable. 

Would it be possible to change them to ensure that they could be stacked and generate less entities in game?

**Comment by P3pp3rF1y** [comment]
they are also an armor piece and as such cannot be stacked so that's unfortunately not possible.
