### ISSUE TITLE
Midas Touchstone Config does not work. 

### ISSUE THREAD

**Issue by 4AC11** [P3pp3rF1y/Reliquary#612]
Title. Though I can easily change the glowstone charge limit and count per glowstone, adding items to the repair list just doesn't work.
It's also possible that I'm getting something wrong with the format, but it seems the same as any other config list...

The offending section:
#Gold items that can be repaired by the touchstone
goldItems = ["hammers:golden_hammer", "spades_extension:golden_spade", "kubejs:excalibur", "kubejs:true_excalibur", "spades_extension:netherite_spade", "spades_extension:enhanced_netherite_spade", "hammers:netherite_hammer", "hammers:enhanced_netherite_hammer", "kubejs:paxel", "kubejs:truepaxel", "immersive_armors:divine_helmet", "immersive_armors:divine_chestplate", "immersive_armors:divine_leggings", "immersive_armors:divine_boots", "kubejs:drax", "rainbowcompound:shadow_steel_pickaxe", "immersive_armors:steampunk_helmet", "immersive_armors:steampunk_chestplate", "immersive_armors:steampunk_leggings", "immersive_armors:steampunk_boots"]

**Comment by P3pp3rF1y** [comment]
There was a bit of issue in the code part that's responsible for check this config and it skipped checking that if the item was armor or tool, in that case it only checked if it was made out of gold material. I have fixed that for next 1.19 release.
