### ISSUE TITLE
[BUG]1.19.2 server: slimes not dropping pearls

### ISSUE THREAD

**Issue by robbenrose** [P3pp3rF1y/Reliquary#615]
I'm running a server on my computer with the mod in addition to a lot of others. I went looking with 2 friends for slime pearls and after an hour of farming a swamp we had over 4 stacks of slime balls but not a single slime pearl.
I ended up going into creative and exchanging them manually at a 1:6 ratio.

**Comment by Mistmage** [comment]
Same problem killed 650 slimes - zero pearls.

**Comment by P3pp3rF1y** [comment]
They properly drop for me in dev as well as in multiple packs I played in the meantime so the only reason I see for them not dropping is your modpack intentionally changing slime drops or some mod causing this additional loot to not register for slimes. 
you would want to report that to modpack maker or figure out which mod does this and report the issue to them. I am closing this one given that it is dated by now, but feel free to open a new issue in case modpack maker / the other mod will have some info that shows what I am doing wrong that the drops don't work in this case.
