### ISSUE TITLE
[1.18.2] Can't get custom recipies on Tome of Alkahestry

### ISSUE THREAD

**Issue by UnWisestLime** [P3pp3rF1y/Reliquary#618]
I just got done playing on my 1.12.2 world and decided to move to 1.18.2. I had done some research before and found out how to override the crafting recipe by going though alkahestry_overrides. I tried to just move the config over and see if that carried over the overrides, but it seems like 1.18.2 doesn't even generate its on config? I tried putting the files in multiple different spots and couldn't get anything to work. 

The files are currently xreliquary\alkahestry_overrides\crafting, so I have no idea what I could be doing wrong. Could I get some help please?

**Comment by P3pp3rF1y** [comment]
Sorry only getting to this now but if you didn't find out back then there's no more alkahestry_overrides as alkahestry just uses custom recipes that can be overriden / added to using regular datapacks https://github.com/P3pp3rF1y/Reliquary/tree/1.18.x/src/generated/resources/data/reliquary/recipes/alkahestry
