### ISSUE TITLE
Potions don't work on servers

### ISSUE THREAD

**Issue by NathanInThailand** [P3pp3rF1y/Reliquary#622]
I'm playing with the Create Above and Beyond modpack, 16.5. I've tried crafting a handful of different potions and so far as I can tell none of them have worked on my private server. I press right click and the potion simply disappears from my inventory with no sound/animation/effect. This happens with both ingest and splash potions. Ingest potions don't play any animation, and splash potions don't fly towards the ground or create any kind of effect.
If I switch to a single player game, potions work a lot more reliably, but still have a pretty high chance of simply vanishing from my inventory on use. I did a bit of probing to try and work out the cause, and I want to say being on creative game mode and switching between creative and survival modes was a trigger, but potions not working wasn't consistent enough in my single player world to confirm that.

**Comment by P3pp3rF1y** [comment]
I am pretty sure potions worked in 1.16.5 and definitely work in 1.19 (and I don't remember needing to fix them when porting from 1.16.5 to later versions. so it's likely some mod in your modpack that causes this issue for you. I am not really supporting 1.16.5 anymore but if you are able to recreate with just reliquary in pack let me know more specifics of what potion you have tried and I may fix that.
