### ISSUE TITLE
[1.19.x/1.18.x/1.16.x] Injected entity loot pools have bonus rolls

### ISSUE THREAD

**Issue by gamrguy** [P3pp3rF1y/Reliquary#623]
Title. Causes massive loot explosions of Reliquary drops when the player has access to Luck, notably Apotheosis.
Added bonus rolls override anything manually placed in the JSON file.

Caused by this line, which is called for both entity and chest loot injections:
(1.19.x/1.18.x)
https://github.com/P3pp3rF1y/Reliquary/blob/80984f60ae16eceb15d3ecbb6ee67f168551ea1f/src/main/java/reliquary/init/ModLoot.java#L48
(1.16.x)
https://github.com/P3pp3rF1y/Reliquary/blob/e4c0e7e2b29a0e2edbbdd28b0036c45ee504b04b/src/main/java/xreliquary/init/ModLoot.java#L39

Related issues: #611 

How to replicate symptoms:
1. Run this command to max out your Luck: `/attribute @p minecraft:generic.luck base set 1024`
2. Kill any mob that has Reliquary-injected drops (such as a Witch).

**Comment by P3pp3rF1y** [comment]
Have this fixed in dev for 1.19 which is the only version I support with lower priority fixes like this.
