### ISSUE TITLE
[Enhancement request] Tiered Magicbane-style enhancement of other weapons

### ISSUE THREAD

**Issue by kurai01** [P3pp3rF1y/Reliquary#624]
Magicbane is great, and the damage scaling lines up pretty well with where someone is in their gameplay experience.  At early game you are limited by XP and general availability of higher tier enchants.  By late game you have access to an abundance of both of those, depending on the modpack.  The one downside of Magicbane is that it tends to require trading off of other weapon/mod systems, and while this is not terrible it is a shame that most of the time there isn't an option to interoperate.  (An exception to that is Apotheosis' adventure module.)  

What I'd like to see is more flexibility to mix and match between weapons systems, and one way to accomplish that would be for Reliquary to include a method of bestowing the Magicbane-effect  onto other weapons.  This could occur through a ritual and require appropriate amounts of resources.  Additionally, it would probably be a good idea to have a tier structure in place, to create a trade-off between using an actual Magicbane weapon, and a weapon from another mod or even vanilla.  Perhaps there could be 3-6 tiers of configurable upgrades which unlock some set amount of enchantment-levels, which might match the types of resources a player might have at different stages of their gameplay.  

I wouldn't advocate for the enhanced item to be inferior to Magicbane at the upper end, but maybe it requires blocks of late-game materials or even an end-game type of mcguffin like an ATM Star, to unlock full equivalency to the original.  If the feature is added with a healthy amount of configurability, then modpack authors can setup appropriate tiers themselves, based on their vision of their packs.  Thank you for considering my suggestion, and for making such a great mod.

**Comment by P3pp3rF1y** [comment]
I don't intend to extend this functionality to other items. It's really supposed to be just a quirk of magicbane and player can decide if they want to use it or not. So I am clsoing this one
