### ISSUE TITLE
Can't switch Rending Gale mode

### ISSUE THREAD

**Issue by Twisted-Code** [P3pp3rF1y/Reliquary#626]
Might be related to #608?
I'm not sure if it's just because I'm using a virtual keyboard, but if I hold shift and left click, my main hand moves as if trying to use the item... but nothing else happens.
This is the case regardless of whether it's raining or the sun is shining. I also made sure I have like 63 or more feathers charged into it, because FOR SOME REASON the shift-right-click control to charge is working.

Reliquary version: 2.0.20.1166
Forge version: 23.2.6

**Comment by P3pp3rF1y** [comment]
you may have figured out that it has actually changed to shift + scroll in latest versions, but I can see some issues in descriptions / tooltips so I am going to fix these and only close this ticket once that change is released.

**Comment by Twisted-Code** [comment]
Any chance you can make it a keybind that doesn't involve the scroll wheel, or add an alternate keyboard bind that ties to the same function? I play the game with a rather severe spinal cord injury, and complicated control gestures, especially those combining mouse and keyboard gestures or multiple non-modifier keys, are nigh impossible for me without third-party software (or at least SOMEONE coding SOMETHING somewhere along the way).
(For an example of existing adaptations that allow me to play the game, take AutoRun (Fabric))
