### ISSUE TITLE
Energy lost with no error log

### ISSUE THREAD

**Issue by tiny-phoenix** [P3pp3rF1y/Reliquary#628]
Hello there~
Basically I was running my server based on Create:Above and Beyond modback, which contains reliquary-1.16.5-1.3.5.1100. At first Im running a forge server, and everything works fine. Few days ago I have to switch to catserver due to some fatal connections issues that could not be fixed on forge server. Then, players on my server are reporting weirld energy lost for all reliquary items, especially rendering gale and ender staff (mostly used items). Its like they got a charged item in the inventory in the last second, and in the next second the energy of that item suddenly drops to 0 without being used! It is an occasionally happening issue, and I cannot find any bug reports from server or client. Personally I don't have any idea how to fix it...

Have you got any reports like this? Is this a known issue of catserver only? Any helps if I upgrade the version of this mod?

**Comment by tiny-phoenix** [comment]
Based on further observation results, the energy lost happens usually when a player moves from one dimension to another. Any ideas?

**Comment by P3pp3rF1y** [comment]
That sounds like catserver is somehow clearing capability data from those items when this happens, but really hard to tell how / why, but you will need to follow up with them on this as the data works correctly with forge and only breaks with that server which honestly I had no idea even exists until this issue.
