### ISSUE TITLE
"Could not find a matching ingredient to remove" for Mob Charms, Witch Hat, Harvest Rod, and a few other items

### ISSUE THREAD

**Issue by sharkweekthings** [P3pp3rF1y/Reliquary#630]
Forge 1.19.2 // reliquary-1.19.2-2.0.20.1166

[latest.log](https://github.com/P3pp3rF1y/Reliquary/files/12002389/latest.log)

Any ideas what might be occurring here starting at Line 222  and ending around Line 590, then goes into another block of the same thing, and again after that block.

"Could not find a matching ingredient to remove:" is the error spit out hundreds of times, and multiplies items in JEI.

![image](https://github.com/P3pp3rF1y/Reliquary/assets/134178249/440175a4-3f58-4b13-80ff-3da01c0fc920)

![image](https://github.com/P3pp3rF1y/Reliquary/assets/134178249/d121616d-24fc-497d-a84f-85b23b27d38e)

![image](https://github.com/P3pp3rF1y/Reliquary/assets/134178249/7991144e-9822-4fdc-8021-c891fdc41855)

Any help on this, short of just removing Reliquary would be awesome.

Thank you!

**Comment by P3pp3rF1y** [comment]
looks like the pack has items setup to be removed from jei and the setup seems to be incorrect. That message definitely logs only when items are setup to be removed from JEI which Reliquary isn't doing for sure. I have no idea why you get duplicates of items in jei - possibly it's adding them or it's failing so hard that when jei reloads it doesn't clear list of items first and just readds the same items. Anyway I am not seeing these errors in my environment at all and am playing a pack with reliquary where this is definitely not happening either so something related to setup in your modpack.
