### ISSUE TITLE
Void tear on a pedestal no longer stores items

### ISSUE THREAD

**Issue by belathus** [P3pp3rF1y/Reliquary#633]
I recall this being a thing in previous versions of Reliquary, but in the 1.19.2 version of Reliquary, I can no longer hopper items into a pedestal that has a void tear on it. I can still pull items out of it, though.

**Comment by P3pp3rF1y** [comment]
This works correctly for me. 
I assume you haven't tried inserting into empty void tear, right?

I will need more detailed steps how I can recreate this.

**Comment by belathus** [comment]
I made a couple screenshots below. The void tear has several stacks of oak logs in it. I'm trying to put more in it via hoppers -- both hoppers have oak logs in them, but they don't feed into it. But if I put a hopper underneath (and fill each slot with oak logs so it doesn't pull the tear out of the hopper), pulling the oak logs out works as expected.

![2023-07-21_19 41 36](https://github.com/P3pp3rF1y/Reliquary/assets/3826783/f749ca78-260c-4a16-bbf7-b5b97ef9623b)
![2023-07-21_19 44 28](https://github.com/P3pp3rF1y/Reliquary/assets/3826783/55a725c5-0d5a-42d5-b75a-d4ab2f239dff)

**Comment by P3pp3rF1y** [comment]
turns out the bug was that it didn't accept anything once it was on or over max stack size (so usually 64) and that bug was there for a very long time since forge made a change on their side like 5 years ago. I have fixed that in the latest release.
