### ISSUE TITLE
Spawn Egg Recipes  Do Not Support Mob Spawn Eggs From Other Mods

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [P3pp3rF1y/Reliquary#636]
Not sure if it is even possible to fix this so it adds the correct eggs automatically, but building support for The Twilight Forest, Alex's mobs, & Divine RPG to name a few would be better than chicken spawn eggs

**Comment by P3pp3rF1y** [comment]
this was actually expected to happen and I found out why it didn't work. Fixed that in the latest release and so it should now work most if not all of the modded spawn eggs.
