### ISSUE TITLE
Issue Regarding Apothecary Cauldron

### ISSUE THREAD

**Issue by TiredArts** [P3pp3rF1y/Reliquary#641]
![2023-08-13_15 07 32](https://github.com/P3pp3rF1y/Reliquary/assets/142177009/51367965-c13c-429b-beae-9128d95dc1ba)
Server Info: 1.19.2, 148-big pack

Last night (as of writing this), I was working on making some potions with the mortar and cauldron. The cauldron accepted the essence and nether wart, but never bubbled to signify I could remove the potions. I tried r-clicking with the vials anyways, to no avail. 

I decided to call it a night and logged off the server, and when I came back just now, the attached screenshot happened. The cauldron was chunkloaded on a 24/7 server, but I guess relogging did something? Still can't get the potions out tho

**Comment by P3pp3rF1y** [comment]
There should be error logged in log related to this. Can you check and add link to that error (on paste in or similar)

**Comment by TiredArts** [comment]
[2023-08-12-1.log.gz](https://github.com/P3pp3rF1y/Reliquary/files/12330572/2023-08-12-1.log.gz)
Only recent one I can see... it's from yesterday, so hopefully this is the right one

**Comment by TiredArts** [comment]
Oh wait, hold on, there's also this from Jade, which is the view-thingy that said to report this
[JadeErrorOutput.txt](https://github.com/P3pp3rF1y/Reliquary/files/12330577/JadeErrorOutput.txt)

**Comment by P3pp3rF1y** [comment]
this looks like Jade may have updated back then, anyway this works in other mc versions, I don't support 1.19 anymore and don't feel this is critical to fix there so closing.
