### ISSUE TITLE
Issue regarding Piglins Attack AI and twilight Cloak

### ISSUE THREAD

**Issue by 7Kav** [P3pp3rF1y/Reliquary#642]
The modpack im playing when this crash occurs is ATM 9 (V9.0.0.51)
The mods version is 1.20.1-2.0.36.1199

When flying around with a twilight cloak (in inventory or curio slots) if a piglin's AI Attempts to attack you. the server will crash with an error.

Steps to reproduce
1: Get a twilight cloak
2: Find a piglin in survival
3: stand close to the piglin (and make sure that the area surrounding is dark) and wait for the piglin to attempt to attack you
4: server should crash near instantly on the piglin seeing you. (you wont be able to get back into that world although you can be Tped out of it into the overworld with a repeating command block)

Server Crash log -> https://gist.github.com/Kavy10/0ac04f94b1cfe1f71eb20e1e444418c5

**Comment by 7Kav** [comment]
for an extra note this also affects piglin brutes
![image](https://github.com/P3pp3rF1y/Reliquary/assets/75175706/fd3502e0-3c74-498b-812e-66cf8d8c9d97)
(Added this mod to help temporarily fix crashes)
Edit: 
![image](https://github.com/P3pp3rF1y/Reliquary/assets/75175706/43875f1b-ce70-4a38-a9ce-542d3b731bf9)
Hoglins too!

**Comment by Leonniclass** [comment]
It's already reported: https://github.com/P3pp3rF1y/Reliquary/issues/640
