### ISSUE TITLE
Witch Hat Missing Recipe

### ISSUE THREAD

**Issue by TookUrSweetRoll** [P3pp3rF1y/Reliquary#643]
I changed configs to disable mob drops and allow crafting. All other mob drop recipes are showing in JEI.

forge-47.1.43
reliquary-1.20.1-2.0.36.1199
jei-1.20.1-forge-15.2.0.25

**Comment by P3pp3rF1y** [comment]
I am adding recipe for that in 1.20.4+ as I don't feel this is critical to add in older version given the years it has been that way without any report.
