### ISSUE TITLE
Game breaking bug (ATM9)

### ISSUE THREAD

**Issue by skyx700** [P3pp3rF1y/Reliquary#645]
When right clicking a bucket of water into the apothecary cauldron it crashes the client game (not the server) and it breaks the chunk at and below the cauldron up to 16 blocks (probably isolated to the chunk section based on chunk viewing) causing existing and new blocks placed to not appear. Restarting doesn't fix the chunk only restoring a backup. The current modpack installed is All the Mods 9 pack version 0.0.65. 

Context probably isn't relevant but I was trying to figure out why potion mixing wasn't working with certain mods, and trying to add water to cauldron's was part of the testing.

![chunk broken2](https://github.com/P3pp3rF1y/Reliquary/assets/76631175/edf6956a-6de0-41ab-a468-b64ae8fae539)
![chunk broken1](https://github.com/P3pp3rF1y/Reliquary/assets/76631175/022db2e5-700f-4dcb-bf16-c1f11c5b19f8)
![chunkbroken3](https://github.com/P3pp3rF1y/Reliquary/assets/76631175/8a27c3c9-7a83-4e48-b027-e96781845f2b)

**Comment by skyx700** [comment]
[crash-2023-09-07_18.32.55-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/12554308/crash-2023-09-07_18.32.55-client.txt)
[crash-2023-09-07_17.58.53-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/12554309/crash-2023-09-07_17.58.53-client.txt)
Forgot to leave the crash logs, here-

**Comment by P3pp3rF1y** [comment]
Looks like potion blender mod broke the cauldron please report to them

**Comment by P3pp3rF1y** [comment]
closing as there isn't anything to fix in reliquary here.
