### ISSUE TITLE
Mod compatibility request

### ISSUE THREAD

**Issue by Tenchu98** [P3pp3rF1y/Reliquary#647]
I am wondering if it would be possible to add silent gear compatibility, namely having some of the items abilities registered as silent gear traits for pack makers to use. I am working on a pack and wanted to use things like the magicbane attack increase effect as a silent gear trait, and haven't been able to figure out how to make it work on my own.

**Comment by P3pp3rF1y** [comment]
This is much more about an implementation on silent gear side where this capability would need to be implemented so more of an addon to that mod. Definitely not something I would be aiming to add and better to ask silent gear dev about this kind of trait.

**Comment by Tenchu98** [comment]
Not really on their side, but I understand if you don't want to do it. Mainly trying to figure out how to access the effects involved, or replicate them.

**Comment by P3pp3rF1y** [comment]
well it really is more on silent gear side as the logic that just affects damage based on number of enchantments and levels is really simple, the more complicated part here is creating all the trait related stuff. Which actually may not be much either but there's definitely more of that than there is of the damage code.
