### ISSUE TITLE
Void Tear working in chests

### ISSUE THREAD

**Issue by Vashta** [P3pp3rF1y/Reliquary#648]
like the title it would really help if the void tear if put in an inventory or on a pillar next to it would grab appropriate items as i have a chicken egg farm with a bunch of chickens on top of a hopper thing is the chest constantly fills up quickly it would be helpful if i could just leave my void tear in the chest and it would suck up the eggs

**Comment by Vashta** [comment]
another idea is make it so the tear can be used in place of a recipe ingredient for automation like with cooking for blockheads it would pull from the tear though i dont know how difficult that would be to program but cooking for blockheads does something similar or like the drives from applied energistics

**Comment by P3pp3rF1y** [comment]
Making tiers work in chests would be pretty intrusive change to vanilla code and that still wouldn't do anything for any modded chests and honestly I don't want that functionality to exist. you can use pedestals with tiers in them if you want to store items in stationery tiers.

And making tier work with any kind of recipe is even more complicated, would involve changing recipes added by vanilla / other mods and then dealing with any kind of issue that can happen with that if mods had any kind of special handling for their recipes. So no I am not going to do this one either.

**Comment by cube8848** [comment]
For anyone else stumbling onto this, using the Coin of Fortune alongside the Void Tear on pedestals works so well.
