### ISSUE TITLE
Mob drops aren't dropping

### ISSUE THREAD

**Issue by darthvader45** [P3pp3rF1y/Reliquary#649]
This is mostly happening for the skeleton's rib bone and creeper catalyzing gland.  How rarely do these things drop?

Using Forge 47.2.0 for 1.20.1, with mod version 2.0.36.1199

**Comment by P3pp3rF1y** [comment]
They are pretty rare if you don't have any looting or severing on your weapon, but they definitely drop. In that case the average drop rate is 1 in 50 skeletons or creepers killed. you really want to be using severing / looting if you want higher chance.

**Comment by darthvader45** [comment]
Thanks.

**Comment by darthvader45** [comment]
Also, do the drops require the mob to be killed by a player?

**Comment by P3pp3rF1y** [comment]
Yes they require player kill
