### ISSUE TITLE
Twilight Cloak isn't doing anything discernible

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/Reliquary#65]
Running around in a completely unlit area at night, full of monsters, with the cloak in my inventory - and they still all notice me, even when I go into even darker areas like under trees and whatnot.

Are there some requirements for the invisibility it's supposed to give that I'm not understanding?

Like, does it not work if you're wearing armor, or holding an item in your hand? Does it need to be in your action bar, or just somewhere in your inventory?

I'm on a server, by the way. Using the latest 1.8.9 version that ends in .261...

**Comment by Not-February** [comment]
Okay, I'm an idiot. I checked the code a little bit and from what I found, you actually have to toggle the item with shift-right-click. None of the documentation indicated this, so I didn't think it was necessary. Whoops.

**Comment by P3pp3rF1y** [comment]
Actually let me reopen this one. I need to update JEI description and wiki to be clear about this.

**Comment by megablock** [comment]
Do you still working on Jei description or i'm doing something wrong here
Reliquary-1.10.2-1.3.3.496
![2016-09-05_18 09 30](https://cloud.githubusercontent.com/assets/10563052/18241427/7531083e-7394-11e6-8708-3c333d79cac2.png)

**Comment by P3pp3rF1y** [comment]
Try later version of Reliquary, I was standardizing translations and it broke JEI descriptions. in later version it works.

And btw, this issue was logged for twilight cloak description so please log issues for other stuff separately.

**Comment by P3pp3rF1y** [comment]
the latest release has the note included in JEI description on turning on twilight cloak and I have updated wiki as well

**Comment by Neospell** [comment]
this is still a bug and its 2021? i think at this point its a feature lol 
![image](https://user-images.githubusercontent.com/16720258/107882062-53437d80-6eb5-11eb-83d9-912742a72d37.png)

**Comment by P3pp3rF1y** [comment]
That is not a JEI description - JEI description is what you see when you click on twilight cloak there and then on the information tab. 
And btw, if you have issues with the mod log a new issue for it rather than trying to dig up 5 years old resolved ones and commenting on those.

**Comment by Neospell** [comment]
> That is not a JEI description - JEI description is what you see when you click on twilight cloak there and then on the information tab.
> And btw, if you have issues with the mod log a new issue for it rather than trying to dig up 5 years old resolved ones and commenting on those.

you're right i should of opened a new ticket but also when i googled the problem this was the first link my apologies and thank you for the great mod
