### ISSUE TITLE
Slime Pearls and Catalyzing Glands no longer drop

### ISSUE THREAD

**Issue by shadow0316** [P3pp3rF1y/Reliquary#651]
So, long story short I made a custom modpack that is run on a server. Catalyzing glands and slime pearls would drop like no tomorrow but for some reason they're so rare now (after a server wipe which was world files) that people would be lucky to have just 1 in their storage. Is there any chance to resolve this issue as soon as possible since its making it harder for people to progress.

It's always been enabled (I've never touched the config for reliquary until now):
![image_2023-10-26_062227657](https://github.com/P3pp3rF1y/Reliquary/assets/111378470/a7033035-d64a-41fd-a91c-60b036021bb4)

**Comment by P3pp3rF1y** [comment]
They were made more rare back in 1.19 but severing enchant was included that increases drop rates significantly. Are you using that? Are they not dropping at all? And is this with just reliquary and no other mod in the pack?

**Comment by shadow0316** [comment]
Oh we were using mob mashers to farm them, so we need severing to get them? Is there a way to disable that?

**Comment by shadow0316** [comment]
also the glands drop from ghasts and other drops will drop without the enchantment from blazes etc etc, just slimes and creepers

**Comment by P3pp3rF1y** [comment]
The 1.19 change just made all drops much rarer but they still drop even without any enchantment. So if you're not getting them at all that sounds like some mod is messing with loot tables. Can you recreate that with just Reliquary?

**Comment by P3pp3rF1y** [comment]
closing given no feedback
