### ISSUE TITLE
reliquary.items.GlacialStaffItem.inventoryTick() taking 45.12% of server thread. 

### ISSUE THREAD

**Issue by dylanketterer** [P3pp3rF1y/Reliquary#653]
Hello!

I recently had a mysterious server lag issue. Using the spark profiler, I was able to track it down to this reliquary.items.GlacialStaffItem.inventoryTick() process, taking up a seemingly huge amount of CPU on it's own at 45.12% . Causing rubber banding and general "Server couldn't keep up" instability. For reference, my AE2 server thread is only taking 1.9%, mekanism is taking up 5.7%.  

![Screenshot from 2023-11-22 19-52-47](https://github.com/P3pp3rF1y/Reliquary/assets/123212830/b6a4befb-678c-404b-9a2d-b994e0e1ea80)

This server is using the AbePack. Here is a link to the spark profiler dump for reference. You can click on mods at the top of the report to see a breakdown with Reliquary at the top.  https://spark.lucko.me/a3TA6jigI3

I started noticing it after teleporting to the nether with the glacial staff, but it could have been happening before that.
I solved the issue by simply removing the glacial staff from my inventory, which I assume gets rid of the inventoryTick call.

I just won't be using the item, it's not like it's game breaking. But I wanted to call this to your attention.

**Comment by dylanketterer** [comment]
Ah sorry, here's the expanded reliquary profile report 
![image](https://github.com/P3pp3rF1y/Reliquary/assets/123212830/bfaf2e9f-9bad-43b1-a8b1-fabb846ef5a5)

**Comment by P3pp3rF1y** [comment]
I am guessing you have teleported in some way to a different part of the world because this shows that Glacial staff is trying to melt ice in unloaded areas possibly in incorrect dimension. I have added something in code to prevent that from happening.
