### ISSUE TITLE
Blaze charm crashing

### ISSUE THREAD

**Issue by NoxScimitar** [P3pp3rF1y/Reliquary#654]
I have a blaze spawner in the real world, and I have a blaze charm to make me invisible while hunting them. I think something happened as a result and I was kicked from the game and it won't load now due to a ticking error. I have the crash log attached.
[crash-2023-11-25_18.36.09-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/13465492/crash-2023-11-25_18.36.09-server.txt)

**Comment by P3pp3rF1y** [comment]
Looks like the player wasn't in the world for some reason, no idea how you can get into that state. if you know how I can recreate reliably (other than spending hours and hours just waiting for it to possibly happen close to blaze) I can take a look

**Comment by P3pp3rF1y** [comment]
closing given no feedback
