### ISSUE TITLE
Hero's Medallion retrieves spent EXP Reliquary Version 1.20.1-2.0.36.1199

### ISSUE THREAD

**Issue by Mediocre-Charlotte** [P3pp3rF1y/Reliquary#657]
As said in the title, the Hero's Medallion allows players to "Recycle" experience indefinitely after spending it, allowing them to use the experience they have infinitely, and could potentially allow for experience duping in combination with experience storage methods from other mods. However, the issue has been replicated standalone without other mods.

How to replicate:
1. Have any decent amount of EXP
2. Absorb the EXP into the talisman
3. Retrieve the EXP from the talisman
4. Spend the EXP on something (For example, enchanting table, anvil, etc.)
5. Absorb your EXP into the talisman

Rather than the expected behavior of just reabsorbing any remaining experience, it returns to the level of experience you had before using it up during step 4.

**Comment by P3pp3rF1y** [comment]
Are you able to recreate with just reliquary in the pack? What version is this?

**Comment by Mediocre-Charlotte** [comment]
As I said in the original report,

Yes, this was recreated with just reliquary in the pack

This was tested in version 2.0.36.1199 (The most recent 1.20.1 version released on curseforge)
