### ISSUE TITLE
Ender Staff loses texture after cycling modes

### ISSUE THREAD

**Issue by Not-February** [P3pp3rF1y/Reliquary#66]
https://i.gyazo.com/5f1097c9bb09ccca30165e31284bd419.png

It looked fine at first after it was crafted. And it still functions properly, it just looks like a big glowy purple-and-black cube now, haha.

I just shift-right-clicked on the ground and it immediately lost its held texture/model, though it still functions and can throw ender pearls, absorb them, change modes etc.

EDIT: I keep forgetting to mention my Forge and mod version!

Forge: 11.15.1.1808
Reliquary: 1.8.9-1.3.1.261

**Comment by P3pp3rF1y** [comment]
I can't recreate this one. Have you tried recreating it with another staff? 
And what other mods you have in the modpack? It may be the kind of block that's clicked or more likely some other mod interacting with it. I can't really think of reason why it would lose its model like this as in any of its states it just points to the same texture.

**Comment by Not-February** [comment]
I'll try doing it again more carefully keeping track of what happened; I don't think it would've been the block type unless it freaked out on Biomes O Plenty Loamy Dirt, because I'm in a little cave house with nothing but vanilla rock and the loamy dirt around me, and this is where I was when it happened.

EDIT: Okay, that's weird. I can't reproduce with one taken from the creative inventory. Crafting another one doesn't seem to do it either. I don't know what even happened there, that's really bizarre.

If something like this happens again I'll try to compare the common factors.

EDIT 2: OKAY so apparently shift-LEFT-clicking on loamy grass/dirt with the staff makes the model disappear for some bizarre reason. So it was the loamy dirt/grass block. I don't know WHY it would do that, but there you go. I've done it three more times now and it only seems to happen with the Ender Staff. Didn't do it with Rending Gale, anyways.

EDIT 3: I don't think it's BOP specific. Doing the exact same thing on a growing wheat plant from vanilla also destroyed the texture/model.

It's shift-left-clicking on any block while in survival, I suppose.

EDIT 4: Gosh. I completely missed the "what other mods do you have" part. Here's a list:

Biomes O Plenty
Bow Infinity Fix
Chisels and Bits
Cosmetic Armor Reworked
Dense Ores
Ding
Grimoire of Gaia
Infernal Mobs
Iron Chests
JEI
Journeymap
Just What I Needed
Loot++(and some custom additions via this mod, but I doubt that's related)
Mod Name Tooltip
More Swords 3
Neat
Not Enough Potions
Packing Tape
Potion Core
Reliquary
Underp Hangables

**Comment by P3pp3rF1y** [comment]
Actually nvm, just recreated that. It's not on shift right, but shift left click. Going to take a look at what the heck is going there.

**Comment by P3pp3rF1y** [comment]
Closing, will be in the next release, some time next week likely
