### ISSUE TITLE
Molten Core mob drop conflict?

### ISSUE THREAD

**Issue by awbuckst11181999** [P3pp3rF1y/Reliquary#660]
So there is a bit of a conflict, in the description of the item it says it is a blaze/magma cube drop, however in JEI it is only listed as a magma cube drop:
![image](https://github.com/P3pp3rF1y/Reliquary/assets/55675794/a9d1438c-7600-46b2-82fb-c824ca150131)
![image](https://github.com/P3pp3rF1y/Reliquary/assets/55675794/13dc5f30-b204-403e-8a81-588cda9165d6)

**Comment by P3pp3rF1y** [comment]
this doesn't strike me as important for previous releases but I am adding info from 1.20.4 on
