### ISSUE TITLE
(1.18.2) Interdiction Torches do not possess the minecraft:wall_post_override tag

### ISSUE THREAD

**Issue by puncrafter** [P3pp3rF1y/Reliquary#661]
Interdiction Torches do not possess the `minecraft:wall_post_override` tag, which makes them look funny when placed on walls. Manually adding this tag via CraftTweaker causes the torch to interact with the wall as expected.

![2024-01-16_14 46 30](https://github.com/P3pp3rF1y/Reliquary/assets/53954921/6c3be9ea-2af1-4b3d-b0ba-8295684c4534)

Forge Version: 40.2.1
Reliquary Version: 1.18.2-2.0.19.1161

**Comment by P3pp3rF1y** [comment]
Added this from 1.20.4 on.
