### ISSUE TITLE
About the collapse of Apotkari Calderen

### ISSUE THREAD

**Issue by AWAKEN-1** [P3pp3rF1y/Reliquary#665]
MC:1.20.1
MOD:up-to-date
FORGE:up-to-date

After the game has been running for a certain period of time, the player will crash directly after passing by or jumping on the upper part of the Apothecary's Cauldron.
A tool told me that the game couldn't run because of an anomalous entity, but the entity was the player himself, which didn't make sense. It should be caused by some kind of bug in the Apothecary's Crucible.
Here are my crash logs
[crash-2024-03-23_11.36.58-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/14730110/crash-2024-03-23_11.36.58-client.txt)

**Comment by P3pp3rF1y** [comment]
I don't know how but somehow you have apothecary **mortar** block entity in that same position. If you have steps how I can recreate getting into that state I can take a look and fix, but I am unable to recreate this crash otherwise. Perhaps you have moved the blocks using some other mod or something similar to that?

**Comment by AWAKEN-1** [comment]
Probably not, this time I entered the save and jumped into the Apothecary's Cauldron (like the vanilla cauldron, standing in the middle of the pot), and for the first few minutes everything was fine, and I was able to walk and jump in a small area inside the pot. But he will crash at some point afterward, and here's my latest crash log https://pastebin.com/raw/4ChHWK3R

**Comment by AWAKEN-1** [comment]
Let me try to only enable this mod and see if I can reproduce this crash again

**Comment by P3pp3rF1y** [comment]
there was no follow up on this and I just double checked to make sure the code doesn't for some reason try to treat mortar as  cauldron but everything looks to be correct, so closing
