### ISSUE TITLE
Is the Tome supposed to work with diamonds?

### ISSUE THREAD

**Issue by AnasterianSunstrider** [P3pp3rF1y/Reliquary#667]
JEI shows this recipe and I'm not sure if it's there by mistake or because it is supposed to work with diamonds but doesn't for some reason
![kép](https://github.com/P3pp3rF1y/Reliquary/assets/26551993/e41ae6ea-d07b-4b5b-9e47-b61cbc508ea6)

**Comment by P3pp3rF1y** [comment]
looks like you have some pack that's having problems synchronizing tags / jei having problems refreshing after tags are synced to client (potentially because the correct event isn't triggered for whatever reason). Sounds like a case for the pack developer to figure out. I will keep this open for a bit just in case you get any info that shows why this is on Reliquary, but given that it almost universally works I doubt there's anything to solve on my side.

**Comment by AnasterianSunstrider** [comment]
I tried it just with this mod and it worked fine
Do you have a guess about which mod could be causing it?
I have 
another_furniture-forge-1.20.1-3.0.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
artifacts-forge-9.3.0.jar
balm-forge-1.20.1-7.2.2.jar
BarteringStation-v8.0.0-1.20.1-Forge.jar
basicweapons-forge-mc1.20.1+1.2.0.jar
baubley-heart-canisters-1.20.1-1.0.5.jar
BetterAdvancements-1.20.1-0.3.2.162.jar
betterarcheology-1.1.7-1.20.1.jar
bettercombat-forge-1.8.4+1.20.1.jar
Bookshelf-Forge-1.20.1-20.1.9.jar
BotanyPots-Forge-1.20.1-13.0.26.jar
BotanyTrees-Forge-1.20.1-9.0.11.jar
bygonenether-1.3.2-1.20.x.jar
caelus-forge-3.1.0+1.20.jar
catalogue-forge-1.20.1-1.8.0.jar
citadel-2.5.4-1.20.1.jar
citresewn-1.20.1-5.jar
clickadv-1.20.1-3.7.jar
cloth-config-11.1.118-forge.jar
Cognition-v2.0.3-1.20.1.jar
ColdSweat-2.2.5.1.jar
collective-1.20.1-7.40.jar
Connector-1.0.0-beta.40+1.20.1.jar
ConnectorExtras-1.10.0+1.20.1.jar
Controlling-forge-1.20.1-12.0.2.jar
corn_delight-1.0.3-1.20.1.jar
Craftable Saddles [1.20 All]-1.4.jar
creeperoverhaul-3.0.2-forge.jar
cupboard-1.20.1-2.6.jar
curios-forge-5.7.2+1.20.1.jar
Divine_Weaponry_v1.7_1.20.1.jar
domesticationinnovation-1.7.1-1.20.1.jar
DrawersTooltip-1.20.1-forge-8.0.0.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar
dynamicvillagertrades-1.3.1-forge-1.20.jar
EasyAnvils-v8.0.2-1.20.1-Forge.jar
embeddium-0.3.11+mc1.20.1.jar
embeddiumextras-1.20.1-v2.0.0.jar
emissive-plugin-1.20.1-2.0.4-forge.jar
EnchantingInfuser-v8.0.2-1.20.1-Forge.jar
entity_model_features_forge_1.20.1-1.3.jar
entity_texture_features_forge_1.20.1-5.2.3.jar
environmentalcreepers-fabric-1.20.1-1.6.0.jar
everycomp-1.20-2.6.40.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
fabric-api-0.92.0+1.11.3+1.20.1.jar
fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
FarmersDelight-1.20.1-1.2.4.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
fixedanvilrepaircost-1.20.1-3.3.jar
forgivingvoid-forge-1.20-10.0.0.jar
framedcompactdrawers-1.20-6.0.0.jar
fruitsdelight-1.0.8.jar
fusion-1.1.1-forge-mc1.20.1.jar
geckolib-forge-1.20.1-4.4.4.jar
gemsnjewels-1.20.1-1.2.5.jar
glassbreaker-neoforge-1.4.0+1.20.jar
gpumemleakfix-1.20.1-1.8.jar
handcrafted-forge-1.20.1-3.0.6.jar
hybrid-aquatic-1.2.2.jar
iceandfire-2.1.13-1.20.1-beta-4.jar
invhud.forge.1.20.1-3.4.18.jar
irons_spellbooks-1.20.1-3.1.1.jar
Jade-1.20.1-forge-11.7.1.jar
JAVD-Forge-5.0.1+mc1.20.1.jar
jei-1.20.1-forge-15.3.0.4.jar
Jewelry-1.6.2.jar
journeymap-1.20.1-5.9.20-forge.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
keepcuriosinventory-1.20.1-0.0.1.jar
MagnumTorch-v8.0.2-1.20.1-Forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.1.1-mc1.20.1forge.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-roofs-2.3.0-mc1.20.1forge.jar
mcw-trapdoors-1.1.2-mc1.20.1forge.jar
mcw-windows-2.2.1-mc1.20.1forge.jar
minecells-1.7.1.jar
minecraft-comes-alive-7.5.14+1.20.1-universal.jar
modmenu-2.0.17.jar
modonomicon-1.20.1-forge-1.67.0.jar
mods.txt
moonlight-1.20-2.11.9-forge.jar
moremcmeta-1.20.1-4.4.7-forge.jar
mysterious_mountain_lib-1.4.5-1.20.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
nerb-1.20.1-0.3-FORGE.jar
nocube's_villagers_sell_animals_1.2.1_forge_1.20.1.jar
occultism-1.20.1-1.124.3.jar
owo-lib-0.11.2+1.20.jar
passiveendermen-1.20.1-4.6.jar
Patchouli-1.20.1-84-FORGE.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.3+1.20.1.jar
PresenceFootsteps-1.20.1-1.9.1-beta.1.jar
PuzzlesLib-v8.1.18-1.20.1-Forge.jar
Quark-4.0-439.jar
Rats-1.20.1-8.1.2.jar
RegionsUnexploredForge-0.5.5+1.20.1.jar
reliquary-1.20.1-2.0.36.1199.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.24.jar
sawmill-1.20-1.3.11.jar
screenshot_viewer-1.2.1-forge-mc1.20.1.jar
Searchables-forge-1.20.1-1.0.2.jar
simpleconfig-1.20.1-1.0.8.jar
sleeping_bags-1.20.1-1.0.3.jar
SmartBrainLib-forge-1.20.1-1.13.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
sootychimneys-1.20.1-1.2.1.jar
sophisticatedbackpacks-1.20.1-3.20.3.1034.jar
sophisticatedcore-1.20.1-0.6.12.589.jar
sophisticatedstorage-1.20.1-0.10.12.768.jar
spawnbalanceutility-1.20-46.13.3.jar
spyglass_improvements-1.5+mc1.20+forge.jar
stacksizeedit-1.0.0-fabric.jar
storagedrawers-1.20.1-12.0.3.jar
StrawStatues-v8.0.3-1.20.1-Forge.jar
sunflowerdelight-1.20.1-1.0.2.jar
TerraBlender-forge-1.20.1-3.0.1.4.jar
Terralith_1.20.4_v2.4.11.jar
textrues_embeddium_options-0.1.5+mc1.20.1.jar
ThirstWasTaken-1.20.1-1.3.6.jar
totw_additions-1.3.1-1.20.x-forge.jar
totw_modded-forge-1.20.1-1.0.4.jar
trade-cycling-forge-1.20.1-1.0.7.jar
TradingPost-v8.0.2-1.20.1-Forge.jar
treasuredistance-1.20-1.2.jar
TreeChop-1.20.1-forge-0.19.0.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
untameddelight-1.20.1-1.1.0.jar
untamedwilds-1.20.1-4.0.4.jar
vintagedelight-0.0.11.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
waystones-forge-1.20-14.1.3.jar
whats-that-slot-forge-1.3.4+1.20.1.jar
youre-in-grave-danger-2.0.0-beta.10.jar
YungsApi-1.20-Forge-4.0.4.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
Zeta-1.0-14.jar

**Comment by P3pp3rF1y** [comment]
I have no idea, have seen this happening from time to time (not specifically with Reliquary recipes but they would be affected as well as any other that use tags) but don't recall ever knowing what exact mod caused it. mezz (the author of JEI) may have a better idea about that.

**Comment by AnasterianSunstrider** [comment]
I did a little elimination game with the mods (i disabled half of them and then went 5 by 5 so i dont go insane) and it turned out to be Sawmill
I'm going to make a post on that mod's github as well
Thanks for the replies ^_^

**Comment by P3pp3rF1y** [comment]
closing given the finding
