### ISSUE TITLE
1.9-1.3.1-beta.253 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [P3pp3rF1y/Reliquary#68]
Issue: reliquary-1.9-1.3.1-beta.253 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/a60f692ff87e20b4f3749420d184caad

fml server latest:
https://gist.github.com/503795fbb4cb98063f84a22930b6182a

**Comment by P3pp3rF1y** [comment]
Looks like a change in forge. I built it with 1816 yesterday which works on dedicated server as well. will likely release a patch for the new version of forge later today.

**Comment by P3pp3rF1y** [comment]
Actually just built and it doesn't even build successfully with 1821 so definitely forge change that wasn't there yesterday.

**Comment by P3pp3rF1y** [comment]
this is now resolved with the new build on CF
