### ISSUE TITLE
Charm Belt won't accept charms

### ISSUE THREAD

**Issue by border999** [P3pp3rF1y/Reliquary#680]
reliquary-1.20.1-2.0.40.1224
I noticed there was an update today but didn't see this issue mentioned in the changelog so I'm still submitting this.
Perhaps I'm doing something wrong, but when I attempt to open the charm belt and insert any of the slew of charms I've gotten off my mob grinder they simply won't insert. Is there some special was I have to add them to the charm?

**Comment by P3pp3rF1y** [comment]
you can't get charms in mob grinder, you're getting charm fragments which need to be crafted into the given mob charm
