### ISSUE TITLE
Modded Mc Server 

### ISSUE THREAD

**Issue by Chippxi** [P3pp3rF1y/Reliquary#681]
Hey there, ive got a server with chosens moded adventure and it kept crashing. When reliquary to latest update within client (curseforge) it says its not compatible with "chosens modded adventure" but the prior version is. so i used the prior version and still get kicked with in 5-10 minute of having 2 or more people. crash report says Reliqaury.jar

**Comment by P3pp3rF1y** [comment]
I need the crash report to be able to help at all. And don't understand what it means that the pack is not compatible with the latest? Any message to that effect?

**Comment by Chippxi** [comment]
[crash-2024-04-12_13.45.22-server.txt](https://github.com/P3pp3rF1y/Reliquary/files/14959496/crash-2024-04-12_13.45.22-server.txt)


Hi there, heres the crash report.

**Comment by P3pp3rF1y** [comment]
just update to the latest version this has already been fixed
