### ISSUE TITLE
Drop issues

### ISSUE THREAD

**Issue by Aoimina** [P3pp3rF1y/Reliquary#683]
I'm having a problem with the drops from all the mobs, none of them drop any reliquary stuff, i killed over 1k of each of the mobs non drop, i play on 1.20.1

**Comment by P3pp3rF1y** [comment]
I play 1.20.1 at the moment as well and they drop for me without any issue, though having Severing enchantment helps immensely with getting the drops. 
Anyway in your case it sounds like something in your pack is affecting the drops so you would need to figure that out or report to the modpack author.

**Comment by Aoimina** [comment]
Could you give me some mods name that you might think are the corporate? like they messed with the drops.
![image](https://github.com/P3pp3rF1y/Reliquary/assets/128810513/31236699-d0d0-4c6b-bc5b-df61ef24ade2)
![image](https://github.com/P3pp3rF1y/Reliquary/assets/128810513/18e3d8b2-ae7d-4efc-b7b5-e90f49dbff78)
![image](https://github.com/P3pp3rF1y/Reliquary/assets/128810513/3564ac1f-7223-478d-ae36-819fe141d0b2)
![image](https://github.com/P3pp3rF1y/Reliquary/assets/128810513/4b86d7bb-9bc1-48a5-811f-f64a6a174048)
![image](https://github.com/P3pp3rF1y/Reliquary/assets/128810513/e73399bb-dee3-4eed-aed7-9afd107116a0)
those are the mods in the modpack if that help

Edit : what is severing enchantment?, i cant seem to find it in JEI or commands.
edit 2 : nvm i found it, didn't have the mod enabled, tho im still not getting any drops despite having level 9 severing

**Comment by P3pp3rF1y** [comment]
I can't help you with the mod because I am not aware of any specific mod causing the issue though I have seen this happening in one 1.20.1 pack. 
However I am playing with TNP limitless 7 where it works properly so you can use the list of mods there as ones that don't do it likely (because it may also be a configuration setting in one of the mods that's causing it)

**Comment by Aoimina** [comment]
After Trail And Error it was not reliquary Fault but a mod by the name Botania: Garden Of Glass, idk if that information is helpful but il drop it here, Thank you
