### ISSUE TITLE
Crash with Horror mods.

### ISSUE THREAD

**Issue by Maxi90909** [P3pp3rF1y/Reliquary#686]
Hi, I noticed that the charms of the mod cause crashes with some horror mods. Mods from CEOofAUTIZMZ like wendigo or the rake and the mod "The knocker" by M_Productions. I was wearing a zombie, skeleton, creeper and spider charm when the crash happened. The crash report is the same for the mods of CEOofAutizmz exept with the respective mod name. 

https://pastebin.com/BHPFsAwu

**Comment by Maxi90909** [comment]
I just saw this error/bug report: https://github.com/P3pp3rF1y/Reliquary/issues/682 Is this issue fixed or am I doing something wrong with my modpack? I have the most recent version of the mod (this one: reliquary-1.20.1-2.0.41.1229.jar) but it still crashes with mobs like the ones mentioned above. If I am doing something wrong please tell me. If it is an issue with the mod please fix.

**Comment by P3pp3rF1y** [comment]
This is a different issue than in that ticket even just by the type of the exception and it's also different stack trace. I am seeing the_knocker in the stack and seeing that it's a mcreator mod makes it a primary suspect that it is causing this issue. Something basically seems to be running this logic in multiple threads when it's only supposed to run in a single one. 
I tried looking at their code but it's a really really hard to understand mess so my recommendation is to remove the mod and see if this keeps happening.

**Comment by P3pp3rF1y** [comment]
And now I noticed you mentioned the mod up there, but really I don't see anything wrong in my code and don't want to be trying to debug the issue with that kind of code on the other side especially given that it works well with tens if not hundreds of other mods out there. 

So best route would be to report that issue to them.

**Comment by P3pp3rF1y** [comment]
And as an additional note given that the other mod you mentioned is closed source there's nothing I can do there and you need to report to them to fix or provide information I can use to fix on my side.

**Comment by P3pp3rF1y** [comment]
And maybe one note here, I am probably starting to understand how this is happening. The exception happens client side which I didn't realize before and yes on client side the render logic can be happening in multiple threads. But setting an entity target on client first of all shouldn't be happening - should be done on server only so that's something those mods should fix.

**Comment by Maxi90909** [comment]
Thank you for taking your time and giving me this information. I will be reporting the issues to each mod respectively. Sorry I thought this was an issue of your mod since it happened with these other mods and happened more than once. It could also be an issue with my mod list, maybe there is a third or even fourth mod which is causing this to happen. I don't really know, since I am not a modder  myself (I am almost incapable of coding, litterally something missing in my brain to understand it).

**Comment by Maxi90909** [comment]
One thing, maybe I got confused with the mods by CEOofautism and I listed the wrong one. Let me see if I can find the crash report of the same issue but with one of his mods.

**Comment by Maxi90909** [comment]
https://pastebin.com/4Yr6D68g
https://pastebin.com/pEcMLJ6w

Litterally the second and the third crash report in the crashfolder. They should be similar. It is the goatman mod. Not the rake one (I think, since the rake spawned and attacked me when it crashed and not the goat man)

**Comment by P3pp3rF1y** [comment]
yeah that's the same thing - entities have their target set on client side. I will leave this ticket open and add something on my side as well to prevent my code from being triggered like this on client side but there's really no reason for their code to be setting the target client side. That is why this has never come up until now.

**Comment by Maxi90909** [comment]
Thank you, maybe because these are horror mods and the Ai of these entities is special. I don't really know their code. It is also very hard to know how they work since most of the don't even have a config file, which is very weird.

**Comment by P3pp3rF1y** [comment]
They are special in a way that they are mcreator mods which basically means created in a tool that's meant for someone who doesn't have a good enough understanding of coding to create regular mod. And mcreator mods are usually source of all kinds of issues. And this is likely the reason they don't have config either - not sure if configs are even supported in mcreator or it's likely that the authors are not aware of that feature / not used to making stuff configurable.

**Comment by Maxi90909** [comment]
I am not really sure if M_Productions created the knocker with MCcreator. I reported the issue in both their discord and their github page. I don't think they did since the knocker has a config file, although the only thing it allows you to change is the spawn rate of the knocker. On the top of the config it does say "server and client" even though there isn't a config file in the world folder of it, only in the config folder.

**Comment by Maxi90909** [comment]
Forget what I said with the knocker not being created with MCcreator. I just looked at the source code and the last file is a Mccreator file. .-.

https://github.com/MProductionsmado/The-Knocker

**Comment by P3pp3rF1y** [comment]
Added the check on client side in the latest release to prevent charm targeting code running if a mod happens to trigger it
