### ISSUE TITLE
[BUG] Cannot drink out of Emperor's Chalice (1.18.2)

### ISSUE THREAD

**Issue by AlexTheDolphin0** [P3pp3rF1y/Reliquary#687]
Mod version: 2.0.19.1161
Forge version: 40.2.0
Minecraft version: 1.18.2
Other mods installed: None
Current behavior: Holding right-click with a chalice in hand while not looking at a block does nothing, regardless of hunger level or chalice mode.
Expected behavior: Holding right click with a chalice in hand while not looking at a block should start drinking, then lose health and gain hunger/saturation once completed.

**Comment by P3pp3rF1y** [comment]
Yes that bug was fixed in 1.20.1. 
1.18.2 hasn't been supported for almost 2 years now and I would only release a new fix version for some kind of critical world breaking bug and this is not one of them so I am going to close.
