### ISSUE TITLE
alkahestryTome Dupe & Negative Dura with Create Mixer Crafting

### ISSUE THREAD

**Issue by ChosenArchitect** [P3pp3rF1y/Reliquary#692]
Using a setup like this
![image](https://github.com/user-attachments/assets/c2726fa8-4ff4-4d89-abc9-09f282720068)

Toss in the Tome and nether stars and it will send double the stars and make the dura go negative
![image](https://github.com/user-attachments/assets/afbf3ce4-2c1d-44e2-a4a7-5bc1dc4d6086)

Forge Version: 47.3.0
Versions: 1.20.1
Mod Version: 1.20.1-2.0.41.1229

**Comment by P3pp3rF1y** [comment]
Forgot to close this when I fixed the bug early in October. So yeah if you haven't noticed the release back then just letting you know that this is now fixed.
