### ISSUE TITLE
Concurrent Modification Exception with upgrade aquatic by team abnormals

### ISSUE THREAD

**Issue by superdude808** [P3pp3rF1y/Reliquary#693]
minecraft version: 1.20.1.
forge version: 37.3.5.
reliquary version: 2.0.41.1229.

So every time I get picked up and attacked by the thrasher from upgrade aquatic the game crashes **every single time** no exceptions.

Now to cut a line of inquiry off I do not have a reliquary charm equipped nor do I have one in my inventory.

now from what the crash log says I think it is an interaction between reliquary's mob charm system that screws with how mobs can see and track the player and the thrasher's unique way of targeting things to attack them but that's all I know since I don't code enough to figure out more than that.

[crash-2024-08-08_14.35.44-client.txt](https://github.com/user-attachments/files/16539041/crash-2024-08-08_14.35.44-client.txt)

**Comment by P3pp3rF1y** [comment]
In the new release there's a bit of code that stops charm code from running on client if some mod (like in this case upgrade aquatic) happens to run targeting code on client for some reason.
