### ISSUE TITLE
Emperor's Chalice

### ISSUE THREAD

**Issue by aliuqwq** [P3pp3rF1y/Reliquary#694]
Issue Description:

I'm experiencing an issue with the Emperor's Chalice in the Reliquary mod. The chalice cannot be used to drink water as intended. When I right-click with it in hand, nothing happens, even when my hunger bar is not full. I have confirmed that the chalice is in its inactive mode. I've also checked for mod conflicts and ensured that I'm using the correct version, but the issue persists. Could you please assist in resolving this?

**Comment by P3pp3rF1y** [comment]
I am not sure what version you are on, but this was fixed in 1.20 some time ago and I don't consider it as critical to fix in previous versions.
