### ISSUE TITLE
Void Tear not working in crafting recipes

### ISSUE THREAD

**Issue by MGP-Galaxy** [P3pp3rF1y/Reliquary#696]
Every item using the void tear is completely uncraftable. You can input the correct recipe and the output will be just a blank box. I have only noticed this issue with the void tear so far.

**Comment by P3pp3rF1y** [comment]
Not sure what version, but in 1.20 I can craft with the void tear without any issues if it doesn't have any items in it which is expected behavior because you don't want the items it contains to just be wasted. Is that what you're seeing?

**Comment by P3pp3rF1y** [comment]
closing given no response
