### ISSUE TITLE
Only register color handlers if the item is not disabled

### ISSUE THREAD

**Issue by Joe12o** [P3pp3rF1y/Reliquary#75]
After disabling a few items in the config the game crashed on startup with an error saying `Item must be registered before assigning color handler.` It seems that in [ModItemColors](https://github.com/P3pp3rF1y/Reliquary/blob/1.9/src/main/java/xreliquary/client/init/ModItemColors.java) you don't make sure that the item isn't disabled before registering a color handler for it which causes this crash.

**Comment by P3pp3rF1y** [comment]
Yeah I guess there will be issues like this. I usually don't test disabling items too much as I actually want people to use all the items. Will look into this and fix probably in the next 1.9 release.
