### ISSUE TITLE
Reliquary gives you super strength [1.9]

### ISSUE THREAD

**Issue by plnqux** [P3pp3rF1y/Reliquary#90]
I've been helping to test a pack for 1.9 and when I have Reliquary installed you can hit mobs for five hearts of damage with an empty hand.

Environment:
Java 1.8.0_77
MC 1.9
Forge 12.16.0.1863
Reliquary 1.9-1.3.1.279 and the 1.9-dev branch in this repository.

Steps to Repro:
Create a new world
Set time to 15000
Go into creative and spawn some zombies with mob eggs
Use an empty hand to kill zombies

**Comment by P3pp3rF1y** [comment]
Thanks for reporting. Apparently I derped and players were getting mercy cross damage applied when their main hand was empty. Will release fix for this pretty soon.

**Comment by plnqux** [comment]
Thanks, I tested with the latest code in my dev deobf environment and it's fixed :+1:
