### ISSUE TITLE
game crashes when u try to brew potions

### ISSUE THREAD

**Issue by Sailren** [P3pp3rF1y/Reliquary#92]
at xreliquary.blocks.tile.TileEntityCauldron.getColor(TileEntityCauldron.java:119)
    at xreliquary.blocks.tile.TileEntityCauldron.spawnBoilingParticles(TileEntityCauldron.java:99)
    at xreliquary.blocks.tile.TileEntityCauldron.func_73660_a(TileEntityCauldron.java:70)

full report here: http://paste.ubuntu.com/15820163/

**Comment by P3pp3rF1y** [comment]
What potion essence have you put in the cauldron? 
Or even better what combination of ingredients you have used to make it in the mortar? 

I am pretty sure this works correctly with many (as I have just confirmed by retesting). Looking at the code there's a possibility that if invalid potion essence was made it would crash, but I don't see how that would be made.

**Comment by Sailren** [comment]
lemme check client, i think i can give u a screen

**Comment by Sailren** [comment]
weird, i tested a few mins ago and it didnt crash, the essence was speed, yesterday it crashed but i found out that u get a cauldron w/o a texture when u use pick block on it

http://abload.de/img/2016-04-14_17.27.28c3uwj.png

http://abload.de/img/2016-04-14_17.27.30rzupb.png
